-- BACIA
-- Hebert Falcão
ALTER TABLE "GSAN_ADMIN"."BACIA"
ADD ("BACI_CDBACIA" NUMBER (4) NULL,
     "BACI_DSABREVBACIA" VARCHAR2(6) NULL,
	 "SSES_ID" NUMBER NULL);

COMMENT ON COLUMN BACIA.BACI_CDBACIA IS 'CODIGO DA BACIA';
COMMENT ON COLUMN BACIA.BACI_DSABREVBACIA IS 'DESCRICAO DA BACIA';
COMMENT ON COLUMN BACIA.SSES_ID IS 'ID DA TABELA SUBSISTEMA_ESGOTO';

ALTER TABLE "GSAN_ADMIN"."BACIA"
MODIFY (SESG_ID NULL);

ALTER TABLE "GSAN_ADMIN"."BACIA"
ADD CONSTRAINT FK2_BACIA FOREIGN KEY (SSES_ID)
REFERENCES "GSAN_ADMIN"."SUBSISTEMA_ESGOTO" (SSES_ID) ENABLE;

-- Hebert Falcão
-- CR81410
ALTER TABLE GSAN_ADMIN.BACIA ADD
( BACI_NNUNIDADE NUMBER(15, 4) DEFAULT 0 NOT NULL,
  BACI_NNADUCAO NUMBER(15, 4) DEFAULT 0 NOT NULL,
  BACI_NNDEMANDAENERGIA NUMBER(15,4) DEFAULT 0 NOT NULL,
  BACI_NNIMOVEL CHAR(5 BYTE),
  BACI_DSCOMPLEMENTOENDERECO VARCHAR2(25 BYTE),
  EDRF_ID NUMBER(*, 0),
  LGBR_ID NUMBER(*, 0),
  LGCP_ID NUMBER(*, 0),
  BACI_NNCOTA NUMBER(9, 0),
  BACI_NNLATITUDE NUMBER(9, 0),
  BACI_NNLONGITUDE NUMBER(9, 0));

COMMENT ON COLUMN BACIA.BACI_NNUNIDADE IS 'UNIDADE (M3/H)';
COMMENT ON COLUMN BACIA.BACI_NNADUCAO IS 'ADUÇÃO';
COMMENT ON COLUMN BACIA.BACI_NNDEMANDAENERGIA IS 'DEMANDA DE ENERGIA (KW)';
COMMENT ON COLUMN BACIA.BACI_NNIMOVEL IS 'NUMERO DO IMOVEL';
COMMENT ON COLUMN BACIA.BACI_DSCOMPLEMENTOENDERECO IS 'COMPLEMENTO DO ENDERECO';
COMMENT ON COLUMN BACIA.EDRF_ID IS 'ENDERECO';
COMMENT ON COLUMN BACIA.LGBR_ID IS 'BAIRRO';
COMMENT ON COLUMN BACIA.LGCP_ID IS 'CEP';
COMMENT ON COLUMN BACIA.BACI_NNCOTA IS 'ALTITUDE';
COMMENT ON COLUMN BACIA.BACI_NNLATITUDE IS 'LATITUDE';
COMMENT ON COLUMN BACIA.BACI_NNLONGITUDE IS 'LONGITUDE';

ALTER TABLE GSAN_ADMIN.BACIA
ADD CONSTRAINT FK3_BACIA FOREIGN KEY (EDRF_ID)
REFERENCES GSAN_ADMIN.ENDERECO_REFERENCIA (EDRF_ID) ENABLE;

ALTER TABLE GSAN_ADMIN.BACIA
ADD CONSTRAINT FK4_BACIA FOREIGN KEY (LGBR_ID)
REFERENCES GSAN_ADMIN.LOGRADOURO_BAIRRO (LGBR_ID) ENABLE;

ALTER TABLE GSAN_ADMIN.BACIA
ADD CONSTRAINT FK5_BACIA FOREIGN KEY (LGCP_ID)
REFERENCES GSAN_ADMIN.LOGRADOURO_CEP (LGCP_ID) ENABLE;
