-- DISTRITO_OPERACIONAL
-- PÉRICLES TAVARES

ALTER TABLE GSAN_ADMIN.DISTRITO_OPERACIONAL ADD
(SABS_ID NUMBER NULL,
  LOCA_ID NUMBER NULL,
  DIOP_NNIMOVEL NUMBER NULL,
  DIOP_DSCOMPLEMENTOENDERECO VARCHAR2(30) NULL,
  DIOP_NNFONE NUMBER(9, 0) NULL,
  DIOP_NNFONERAMAL NUMBER(4, 0) NULL,
  DIOP_NNFAX NUMBER(9, 0) NULL,
  DIOP_DSEMAIL VARCHAR2(40) NULL,
  EDRF_ID NUMBER NULL,
  LGBR_ID NUMBER NULL,
  LGCP_ID NUMBER NULL,
  DIOP_NNCOTA NUMBER(9, 0) NULL,
  DIOP_NNLATITUDE NUMBER(9, 0) NULL,
  DIOP_NNLONGITUDE NUMBER(9, 0) NULL,
  DOUT_ID NUMBER NULL);


ALTER TABLE GSAN_ADMIN.DISTRITO_OPERACIONAL
ADD CONSTRAINT FK2_DISTRITO_OPERACIONAL FOREIGN KEY (EDRF_ID) 
REFERENCES GSAN_ADMIN.ENDERECO_REFERENCIA (EDRF_ID) ENABLE;

ALTER TABLE GSAN_ADMIN.DISTRITO_OPERACIONAL 
ADD CONSTRAINT FK3_DISTRITO_OPERACIONAL  FOREIGN KEY (LGBR_ID) 
REFERENCES GSAN_ADMIN.LOGRADOURO_BAIRRO (LGBR_ID) ENABLE;

ALTER TABLE GSAN_ADMIN.DISTRITO_OPERACIONAL 
ADD CONSTRAINT FK4_DISTRITO_OPERACIONAL FOREIGN KEY (LGCP_ID) 
REFERENCES GSAN_ADMIN.LOGRADOURO_CEP (LGCP_ID) ENABLE;

ALTER TABLE GSAN_ADMIN.DISTRITO_OPERACIONAL 
ADD CONSTRAINT FK5_DISTRITO_OPERACIONAL FOREIGN KEY (SABS_ID) 
REFERENCES GSAN_ADMIN.SISTEMA_ABASTECIMENTO (SABS_ID) ENABLE;

UPDATE DISTRITO_OPERACIONAL SET SABS_ID = 1;

ALTER TABLE DISTRITO_OPERACIONAL MODIFY SABS_ID NOT NULL;

ALTER TABLE GSAN_ADMIN.DISTRITO_OPERACIONAL 
ADD CONSTRAINT FK6_DISTRITO_OPERACIONAL FOREIGN KEY (LOCA_ID) 
REFERENCES GSAN_ADMIN.LOCALIDADE (LOCA_ID) ENABLE;

UPDATE DISTRITO_OPERACIONAL SET LOCA_ID = 1;

ALTER TABLE DISTRITO_OPERACIONAL MODIFY LOCA_ID NOT NULL;

ALTER TABLE GSAN_ADMIN.DISTRITO_OPERACIONAL 
ADD CONSTRAINT FK7_DISTRITO_OPERACIONAL FOREIGN KEY (DOUT_ID) 
REFERENCES GSAN_ADMIN.DISTRITO_OPER_UNID_TIPO (DOUT_ID) ENABLE;

UPDATE DISTRITO_OPERACIONAL SET DOUT_ID = 1;

ALTER TABLE DISTRITO_OPERACIONAL MODIFY DOUT_ID NOT NULL;
