-- HIDROMETRO
-- Hebert Falcão
ALTER TABLE "GSAN_ADMIN"."HIDROMETRO"
ADD ("HIDI_ICHIDROMETROCONPOSTO" NUMBER(1,0) NULL,
     "HIDI_NNFATORCONVERSAO" NUMBER(6,3) NULL);

COMMENT ON COLUMN HIDROMETRO.HIDI_ICHIDROMETROCONPOSTO IS 'INDICADOR DE HIDROMETRO COMPOSTO';
COMMENT ON COLUMN HIDROMETRO.HIDI_NNFATORCONVERSAO IS 'FATOR DE CONVERSAO DO HIDROMETRO';
