ALTER TABLE IMOVEL_AGUA_PARA_TODOS ADD PRIMARY KEY (IAPT_ID, IAPT_NNIDENTIFCONTRIBUINTE);

ALTER TABLE IMOVEL_AGUA_PARA_TODOS
ADD CONSTRAINT FK1_IMOVEL_AGUA_PARA_TODOS FOREIGN KEY (IAPT_USUARIO_ID_INCL)
REFERENCES USUARIO (USUR_ID) ENABLE;

ALTER TABLE IMOVEL_AGUA_PARA_TODOS
ADD CONSTRAINT FK2_IMOVEL_AGUA_PARA_TODOS FOREIGN KEY (IAPT_USUARIO_ID_EXCL)
REFERENCES USUARIO (USUR_ID) ENABLE; 

ALTER TABLE IMOVEL_AGUA_PARA_TODOS
ADD CONSTRAINT FK3_IMOVEL_AGUA_PARA_TODOS FOREIGN KEY (IAPT_ID)
REFERENCES IMOVEL (IMOV_ID) ENABLE; 