-- IMOVEL
-- Hebert Falcão
ALTER TABLE "GSAN_ADMIN"."IMOVEL"
ADD ("IMOV_NNROTA" NUMBER(4,0) NULL,
     "IMOV_NNSEGUIMENTO" NUMBER(4,0) NULL,
	 "IMOV_ICCONTRATOCONSUMO" NUMBER(1,0) NULL,
	 "IMOV_CDTARIFATEMP" NUMBER(4,0) NULL,
	 "IMOV_DATAVALIDADETARIFATEMP" DATE NULL);

COMMENT ON COLUMN IMOVEL.IMOV_NNROTA IS 'NUMERO DA ROTA (INSCRICAO)';
COMMENT ON COLUMN IMOVEL.IMOV_NNSEGUIMENTO IS 'NUMERO DO SEGUIMENTO (INSCRICAO)';
COMMENT ON COLUMN IMOVEL.IMOV_ICCONTRATOCONSUMO IS 'INDICADOR DE CONTRATO DE CONSUMO';
COMMENT ON COLUMN IMOVEL.IMOV_CDTARIFATEMP IS 'CODIGO DA TARIFA';
COMMENT ON COLUMN IMOVEL.IMOV_DATAVALIDADETARIFATEMP IS 'DATA DE VALIDADE DA TARIFA TEMPORARIA';

ALTER TABLE IMOVEL ADD (IMOV_ICAGUAPARATODOS NUMBER(1));
COMMENT ON COLUMN IMOVEL.IMOV_ICAGUAPARATODOS IS 'INDICADOR DE AGUA PARA TODOS';