-- CR84384
-- Hebert Falcão
ALTER TABLE "GSAN_ADMIN"."LIGACAO_AGUA"
ADD (LAGU_IDFUNCCORTE          NUMBER(*,0),
     LAGU_IDFUNCLIGACAOAGUA    NUMBER(*,0),
     LAGU_IDFUNCSUPRESSAOAGUA  NUMBER(*,0),
     LAGU_IDFUNCRELIGACAOAGUA  NUMBER(*,0),
     LAGU_IDFUNCRESTABEL       NUMBER(*,0),
     LAGU_NNCORTE              NUMBER(*,0),
     LAGU_NNCORTEADM           NUMBER(*,0),
     LAGU_NNSUPRESSAOAGUA      NUMBER(*,0)
	);

ALTER TABLE "GSAN_ADMIN"."LIGACAO_AGUA" ADD CONSTRAINT "FK11_LIGACAO_AGUA" FOREIGN KEY ("LAGU_IDFUNCCORTE") REFERENCES "GSAN_ADMIN"."FUNCIONARIO" ("FUNC_ID") ENABLE;
ALTER TABLE "GSAN_ADMIN"."LIGACAO_AGUA" ADD CONSTRAINT "FK12_LIGACAO_AGUA" FOREIGN KEY ("LAGU_IDFUNCLIGACAOAGUA") REFERENCES "GSAN_ADMIN"."FUNCIONARIO" ("FUNC_ID") ENABLE;
ALTER TABLE "GSAN_ADMIN"."LIGACAO_AGUA" ADD CONSTRAINT "FK13_LIGACAO_AGUA" FOREIGN KEY ("LAGU_IDFUNCSUPRESSAOAGUA") REFERENCES "GSAN_ADMIN"."FUNCIONARIO" ("FUNC_ID") ENABLE;
ALTER TABLE "GSAN_ADMIN"."LIGACAO_AGUA" ADD CONSTRAINT "FK14_LIGACAO_AGUA" FOREIGN KEY ("LAGU_IDFUNCRELIGACAOAGUA") REFERENCES "GSAN_ADMIN"."FUNCIONARIO" ("FUNC_ID") ENABLE;
ALTER TABLE "GSAN_ADMIN"."LIGACAO_AGUA" ADD CONSTRAINT "FK15_LIGACAO_AGUA" FOREIGN KEY ("LAGU_IDFUNCRESTABEL") REFERENCES "GSAN_ADMIN"."FUNCIONARIO" ("FUNC_ID") ENABLE;

COMMENT ON COLUMN "GSAN_ADMIN"."LIGACAO_AGUA"."LAGU_IDFUNCCORTE" IS 'ID FUNCIONARIO QUE REALIZOU O CORTE';
COMMENT ON COLUMN "GSAN_ADMIN"."LIGACAO_AGUA"."LAGU_IDFUNCLIGACAOAGUA" IS 'ID FUNCIONARIO QUE REALIZOU O LIGACAO';
COMMENT ON COLUMN "GSAN_ADMIN"."LIGACAO_AGUA"."LAGU_IDFUNCSUPRESSAOAGUA" IS 'ID FUNCIONARIO QUE REALIZOU A SUPRESSAO';
COMMENT ON COLUMN "GSAN_ADMIN"."LIGACAO_AGUA"."LAGU_IDFUNCRELIGACAOAGUA" IS 'ID FUNCIONARIO QUE REALIZOU O RELIGACAO';
COMMENT ON COLUMN "GSAN_ADMIN"."LIGACAO_AGUA"."LAGU_IDFUNCRESTABEL" IS 'ID FUNCIONARIO QUE REALIZOU O RESTABELECIMENTO';
COMMENT ON COLUMN "GSAN_ADMIN"."LIGACAO_AGUA"."LAGU_NNCORTE" IS 'QUANTIDADE DE CORTE REALIZADO';
COMMENT ON COLUMN "GSAN_ADMIN"."LIGACAO_AGUA"."LAGU_NNCORTEADM" IS 'QUANTIDADE DE CORTE ADM REALIZADO';
COMMENT ON COLUMN "GSAN_ADMIN"."LIGACAO_AGUA"."LAGU_NNSUPRESSAOAGUA" IS 'QUANTIDADE DE SUPRESSAO REALIZADO';
