-- LOCALIDADE
-- Hebert Falcão
ALTER TABLE "GSAN_ADMIN"."LOCALIDADE"
ADD ("LOCA_CDLOCALVINCULADA" NUMBER NULL,
     "LOCA_CDLOCALCEF" NUMBER(4,0) NULL,
	 "LOCA_ICABASTECIMENTOSUSPENSO" NUMBER(4,0) NULL,
	 "LOCA_ICABASTECIMENTOMINIMO" NUMBER(4,0) NULL,
	 "LOCA_CDLOCALCONTABIL" NUMBER(4,0) NULL,
	 "LOCA_NNULTIMAQUADRA" NUMBER(4,0) NULL);

COMMENT ON COLUMN LOCALIDADE.LOCA_CDLOCALVINCULADA IS 'CODIGO LOCALIDADE VINCULADA';
COMMENT ON COLUMN LOCALIDADE.LOCA_CDLOCALCEF IS 'COD. LOCAL. P/ C.E.F.';
COMMENT ON COLUMN LOCALIDADE.LOCA_ICABASTECIMENTOSUSPENSO IS 'INDICADOR ABASTECIMENTO SUSPENSO NUMERICO';
COMMENT ON COLUMN LOCALIDADE.LOCA_ICABASTECIMENTOMINIMO IS 'INDICADOR DE ABASTECIMENTO MINIMO';
COMMENT ON COLUMN LOCALIDADE.LOCA_CDLOCALCONTABIL IS 'CODIGO DA LOCALIDADE CONTABIL';
COMMENT ON COLUMN LOCALIDADE.LOCA_NNULTIMAQUADRA IS 'NUMERO DA ULTIMA QUADRA CADASTRADA PARA A LOCALIDADE';
COMMENT ON COLUMN LOCALIDADE.MUNI_ID IS 'CODIGO DO MUNICIPIO';

ALTER TABLE "GSAN_ADMIN"."LOCALIDADE"
MODIFY (UNEG_ID NULL);

ALTER TABLE "GSAN_ADMIN"."LOCALIDADE"
MODIFY (LOCA_CDELO NULL);

ALTER TABLE "GSAN_ADMIN"."LOCALIDADE"
ADD CONSTRAINT FK11_LOCALIDADE FOREIGN KEY (LOCA_CDLOCALVINCULADA)
REFERENCES "GSAN_ADMIN"."LOCALIDADE" (LOCA_ID) ENABLE;

ALTER TABLE LOCALIDADE DROP COLUMN CLIE_ID

ALTER TABLE LOCALIDADE ADD FUNC_ID NUMBER NULL;

COMMENT ON COLUMN LOCALIDADE.FUNC_ID IS 'CODIGO DO FUNCIONARIO';

ALTER TABLE "GSAN_ADMIN"."LOCALIDADE"
ADD CONSTRAINT FK12_LOCALIDADE FOREIGN KEY (FUNC_ID)
REFERENCES "GSAN_ADMIN"."FUNCIONARIO" (FUNC_ID) ENABLE;


