-- MUNICIPIO
-- Péricles Tavares
ALTER TABLE "GSAN_ADMIN"."MUNICIPIO"
ADD ("MUNI_NMPREFEITURA" VARCHAR(50) NULL,
     "MUNI_EDPPREFEITURA" VARCHAR(50) NULL,
	 "MUNI_NNCNPJPREFEITURA" VARCHAR(14) NULL,
	 "MUNI_NNCONTABANCARIA" NUMBER(9) NULL,
	 "MUNI_NMPREFEITO" VARCHAR(30) NULL,
	 "MUNI_NNCPFPREFEITO" VARCHAR(11) NULL,
	 "MUNI_NMPARTIDOPREFEITO" VARCHAR(5) NULL,
	 "MUNI_NACIONALIDADEPREFEITO" VARCHAR(10) NULL,
	 "MUNI_ESTADOCIVILPREFEITO" VARCHAR(10) NULL,
	 "MUNI_CDCEPPADRAO" NUMBER(8) NULL,
	 "AGEN_ID" NUMBER NULL);

ALTER TABLE "GSAN_ADMIN"."MUNICIPIO"
ADD CONSTRAINT FK4_MUNICIPIO FOREIGN KEY (AGEN_ID)
REFERENCES "GSAN_ADMIN"."AGENCIA" (AGEN_ID) ENABLE;

COMMENT ON COLUMN MUNICIPIO.MUNI_NMPREFEITURA IS 'NOME PREFEITURA DO MUNICIPIO';
COMMENT ON COLUMN MUNICIPIO.MUNI_EDPPREFEITURA IS 'ENDEREÇO DO PREFEITURA';
COMMENT ON COLUMN MUNICIPIO.MUNI_NNCNPJPREFEITURA IS 'NUM. CNPJ DA PREFEITURA';
COMMENT ON COLUMN MUNICIPIO.AGEN_ID IS 'CÓDIGO DA AGENCIA BANCARIA';
COMMENT ON COLUMN MUNICIPIO.MUNI_NMPREFEITO IS 'NOME DO PREFEITO';
COMMENT ON COLUMN MUNICIPIO.MUNI_NNCPFPREFEITO IS 'CPF DO PREFEITO';
COMMENT ON COLUMN MUNICIPIO.MUNI_NACIONALIDADEPREFEITO IS 'NACIONALIDADE DO PREFEITO';
COMMENT ON COLUMN MUNICIPIO.MUNI_ESTADOCIVILPREFEITO IS	'ESTADO CIVIL DO PREFEITO';
COMMENT ON COLUMN MUNICIPIO.MUNI_NMPARTIDOPREFEITO IS 'SIGLA DO PARTIDO POLÍTICO DO PREFEITO';
COMMENT ON COLUMN MUNICIPIO.MUNI_CDCEPPADRAO IS 'CEP PADRAO DO MUNICIPIO';
COMMENT ON COLUMN MUNICIPIO.MUNI_NNCONTABANCARIA IS 'NUMERO DA CONTA BANCARIA DA PREFEITURA';
