-- REGISTRO_ATENDIMENTO_SOLCTT
-- PÉRICLES TAVARES
ALTER TABLE "GSAN_ADMIN"."REGISTRO_ATENDIMENTO_SOLCTT"
ADD ("RASO_ICPESSOAFISICAJURIDICA" NUMBER NULL,
      "RASO_NNCPF" VARCHAR(11) NULL,
      "RASO_NNRG" VARCHAR(13) NULL,
      "OERG_ID" NUMBER NULL,
      "UNFE_ID" NUMBER NULL,
      "RASO_NNCNPJ" VARCHAR(14) NULL);
      

ALTER TABLE "GSAN_ADMIN"."REGISTRO_ATENDIMENTO_SOLCTT"  
ADD CONSTRAINT "FK8_REGISTRO_ATENDIMENTO_SOLIC" FOREIGN KEY ("OERG_ID") 
REFERENCES "GSAN_ADMIN"."ORGAO_EXPEDIDOR_RG" ("OERG_ID") ENABLE;

ALTER TABLE "GSAN_ADMIN"."REGISTRO_ATENDIMENTO_SOLCTT" 
ADD CONSTRAINT "FK9_REGISTRO_ATENDIMENTO_SOLIC" FOREIGN KEY ("UNFE_ID")
REFERENCES "GSAN_ADMIN"."UNIDADE_FEDERACAO" ("UNFE_ID") ENABLE;
      
COMMENT ON COLUMN "GSAN_ADMIN"."REGISTRO_ATENDIMENTO_SOLCTT"."RASO_ICPESSOAFISICAJURIDICA" IS 'INDICADOR PESSOA FÍSICA OU JURÍDICA – 1 FÍSICA, 2 JURÍDICA';
COMMENT ON COLUMN "GSAN_ADMIN"."REGISTRO_ATENDIMENTO_SOLCTT"."RASO_NNCPF" IS 'NUMERO DO CPF - PESSOA FISICA';
COMMENT ON COLUMN "GSAN_ADMIN"."REGISTRO_ATENDIMENTO_SOLCTT"."RASO_NNRG" IS 'NUMERO DO RG - PESSOA FISICA';
COMMENT ON COLUMN "GSAN_ADMIN"."REGISTRO_ATENDIMENTO_SOLCTT"."OERG_ID" IS 'ORGAO EXPEDIDOR DO RG (TABELA ORGAO_EXPEDIDOR_RG) - PESSOA FISICA';
COMMENT ON COLUMN "GSAN_ADMIN"."REGISTRO_ATENDIMENTO_SOLCTT"."UNFE_ID" IS 'UNIDADE DE FEDERACAO DO ORGAO EXPEDIDOR/INSCRICAO ESTADUAL (TABELA UNIDADE_FEDERACAO)';
COMMENT ON COLUMN "GSAN_ADMIN"."REGISTRO_ATENDIMENTO_SOLCTT"."RASO_NNCNPJ" IS 'NUMERO DO CNPJ - PESSOA JURIDICA';
