-- SETOR_ABASTECIMENTO
-- PÉRICLES TAVARES
ALTER TABLE "GSAN_ADMIN"."SETOR_ABASTECIMENTO"
ADD ("STAB_CDSETORABASTECIMENTO" NUMBER(2) NULL,
	 "ZABS_ID" NUMBER NULL,
	 "UNOP_ID" NUMBER NULL
	 );
ALTER TABLE "GSAN_ADMIN"."SETOR_ABASTECIMENTO" MODIFY STAB_DSSETORABASTECIMENTO VARCHAR(30)
	 
COMMENT ON COLUMN SETOR_ABASTECIMENTO.STAB_ID IS 'ID DA TABELA SETOR_ABASTECIMENTO.';
COMMENT ON COLUMN SETOR_ABASTECIMENTO.STAB_CDSETORABASTECIMENTO IS 'CODIGO DO SETOR DE ABASTECIMENTO';
COMMENT ON COLUMN SETOR_ABASTECIMENTO.STAB_DSSETORABASTECIMENTO IS 'DESCRICAO DO SETOR DE ABASTECIMENTO';
COMMENT ON COLUMN SETOR_ABASTECIMENTO.STAB_DSABREVIADO IS 'DESCRICAO ABREVIADA DO SETOR DE ABASTECIMENTO';
COMMENT ON COLUMN SETOR_ABASTECIMENTO.ZABS_ID IS 'ID DA ZONA DE ABASTECIMENTO';
COMMENT ON COLUMN SETOR_ABASTECIMENTO.SABS_ID IS 'ID DO SISTEMA DE ABASTECIMENTO';
COMMENT ON COLUMN SETOR_ABASTECIMENTO.UNOP_ID IS 'ID DO UNIDADE OPERACIONAL';
COMMENT ON COLUMN SETOR_ABASTECIMENTO.STAB_TMULTIMAALTERACAO IS	'DATA DA ULTIMA ALTERACAO';
COMMENT ON COLUMN SETOR_ABASTECIMENTO.STAB_ICUSO IS 'INDICADOR DE ATIVO  1 – ATIVO   2 – INATIVO';

ALTER TABLE "GSAN_ADMIN"."SETOR_ABASTECIMENTO"
ADD CONSTRAINT FK2_SETOR_ABASTECIMENTO FOREIGN KEY (ZABS_ID)
REFERENCES "GSAN_ADMIN"."ZONA_ABASTECIMENTO" (ZABS_ID) ENABLE;

ALTER TABLE "GSAN_ADMIN"."SETOR_ABASTECIMENTO"
ADD CONSTRAINT FK3_SETOR_ABASTECIMENTO FOREIGN KEY (UNOP_ID)
REFERENCES "GSAN_ADMIN"."UNIDADE_OPERACIONAL" (UNOP_ID) ENABLE;