-- Alteração feita para permitir a retirada dos campos da tela para o Cliente DESO
-- Ailton Junior.
ALTER TABLE GSAN_ADMIN.SISTEMA_ESGOTO MODIFY DVES_ID null;

ALTER TABLE GSAN_ADMIN.SISTEMA_ESGOTO MODIFY SETT_ID null;

-- Hebert Falcão
-- CR81356
ALTER TABLE GSAN_ADMIN.SISTEMA_ESGOTO ADD 
(GREG_ID NUMBER(*, 0) DEFAULT 1 NOT NULL);

COMMENT ON COLUMN SISTEMA_ESGOTO.GREG_ID IS 'GERENCIA REGIONAL';

ALTER TABLE GSAN_ADMIN.SISTEMA_ESGOTO 
ADD CONSTRAINT FK3_SISTEMA_ESGOTO FOREIGN KEY (GREG_ID) 
REFERENCES GSAN_ADMIN.GERENCIA_REGIONAL (GREG_ID) ENABLE;

ALTER TABLE GSAN_ADMIN.SISTEMA_ESGOTO ADD 
(SESG_CDSISTEMAESGOTO NUMBER(3));

COMMENT ON COLUMN SISTEMA_ESGOTO.SESG_CDSISTEMAESGOTO IS 'Código do Sistema de Esgoto';
