-- SOLICITACAO_TIPO_ESPECIFICACAO
-- Isaac Silva
ALTER TABLE "GSAN_ADMIN"."SOLICITACAO_TIPO_ESPECIFICACAO"
ADD ("STEM_ID" NUMBER NULL);

ALTER TABLE "GSAN_ADMIN"."SOLICITACAO_TIPO_ESPECIFICACAO"
ADD CONSTRAINT FK5_SOLICITACAO_TIPO_ESPECIFIC FOREIGN KEY (STEM_ID)
REFERENCES "GSAN_ADMIN"."SOLICITACAO_TIPO_ESPECIF_MENS" (STEM_ID) ENABLE;

COMMENT ON COLUMN SOLICITACAO_TIPO_ESPECIFICACAO.STEM_ID IS 'CÓDIGO DA MENSAGEM AUTOMÁTICA';

-- Anderson Italo
ALTER TABLE "GSAN_ADMIN"."SOLICITACAO_TIPO_ESPECIFICACAO"
ADD ("STEP_ICCOLOCACONTASEMREVISAO" NUMBER NULL);

ALTER TABLE "GSAN_ADMIN"."SOLICITACAO_TIPO_ESPECIFICACAO"
ADD ("STEP_MENSAGEMALERTAREVISAO" NUMBER NULL);

COMMENT ON COLUMN SOLICITACAO_TIPO_ESPECIFICACAO.STEP_ICCOLOCACONTASEMREVISAO IS 'Apenas DESO. Coloca Contas em Revisão (1- SIM 2, - NÃO)';
COMMENT ON COLUMN SOLICITACAO_TIPO_ESPECIFICACAO.STEP_MENSAGEMALERTAREVISAO IS 'Apenas DESO. Exibe Mensagem Alerta Contas em Revisão (1- SIM, 2 - NÃO)';

-- Ailton Sousa
ALTER TABLE "GSAN_ADMIN"."SOLICITACAO_TIPO_ESPECIFICACAO"
ADD ("STEP_ICRG" NUMBER NULL);

ALTER TABLE "GSAN_ADMIN"."SOLICITACAO_TIPO_ESPECIFICACAO"
ADD ("STEP_ICCPFCNPJ" NUMBER NULL);
      
      
COMMENT ON COLUMN GSAN_ADMIN.SOLICITACAO_TIPO_ESPECIFICACAO.STEP_ICRG
IS   'INDICADOR DE OBRIGATORIADADE DO RG NA ABERTURA DO RA (1- SIM 2, - NÃO)';
COMMENT ON COLUMN GSAN_ADMIN.SOLICITACAO_TIPO_ESPECIFICACAO.STEP_ICCPFCNPJ
IS   'INDICADOR DE OBRIGATORIADADE DO CPF OU CNPJ NA ABERTURA DO RA (1- SIM 2, - NÃO)';
