ALTER TABLE SUBBACIA
ADD CONSTRAINT FK1_SUBBACIA FOREIGN KEY (BACI_ID)
REFERENCES BACIA (BACI_ID) ENABLE;

-- Ailton Sousa
ALTER TABLE GSAN_ADMIN.SUBBACIA ADD 
( SBAC_NNEXTENSAO NUMBER(9, 4) DEFAULT 1 NOT NULL,
  SBAC_NNDIAMETRO NUMBER(6, 4) DEFAULT 1 NOT NULL,
  MRDE_ID NUMBER(*,0) DEFAULT 1 NOT NULL);

ALTER TABLE GSAN_ADMIN.SUBBACIA 
ADD CONSTRAINT FK2_SUBBACIA FOREIGN KEY (MRDE_ID) 
REFERENCES GSAN_ADMIN.MATERIAL_REDE_ESGOTO (MRDE_ID) ENABLE;

-- Hebert Falcão
-- CR81411
COMMENT ON COLUMN SUBBACIA.SBAC_NNEXTENSAO IS 'EXTENSAO';
COMMENT ON COLUMN SUBBACIA.SBAC_NNDIAMETRO IS 'DIAMETRO';
COMMENT ON COLUMN SUBBACIA.MRDE_ID IS 'MATERIAL';
