ALTER TABLE GSAN_ADMIN.SUBSISTEMA_ESGOTO ADD 
(LOCA_ID NUMBER(*, 0) NULL);

ALTER TABLE GSAN_ADMIN.SUBSISTEMA_ESGOTO 
ADD CONSTRAINT FK1_ SUBSISTEMA_ESGOTO FOREIGN KEY (LOCA_ID) 
REFERENCES GSAN_ADMIN.LOCALIDADE (LOCA_ID) ENABLE;

UPDATE SUBSISTEMA_ESGOTO SET LOCA_ID = 1;

ALTER TABLE SUBSISTEMA_ESGOTO MODIFY LOCA_ID NOT NULL;

ALTER TABLE GSAN_ADMIN.SUBSISTEMA_ESGOTO ADD 
(ESTT_ID NUMBER(*, 0) NULL);

ALTER TABLE GSAN_ADMIN.SUBSISTEMA_ESGOTO 
ADD CONSTRAINT FK3_ SUBSISTEMA_ESGOTO FOREIGN KEY (ESTT_ID) 
REFERENCES GSAN_ADMIN.ESGOTO_TRATAMENTO_TIPO (ESTT_ID) ENABLE;

UPDATE SUBSISTEMA_ESGOTO SET ESTT_ID = 1;

ALTER TABLE SUBSISTEMA_ESGOTO MODIFY ESTT_ID NOT NULL;