ALTER TABLE TRAMITE ADD (TRMT_ID NUMBER);

COMMENT ON COLUMN TRAMITE.TRMT_ID IS 'IDENTIFICADOR DO MOTIVO DO TRAMITE';

ALTER TABLE TRAMITE
ADD CONSTRAINT FK10_TRAMITE FOREIGN KEY (TRMT_ID)
REFERENCES TRAMITE_MOTIVO (TRMT_ID) ENABLE;