ALTER TABLE ZONA_ABASTECIMENTO
ADD (ZABS_CDZONAABASTECIMENTO NUMBER (2) NULL,
	 UNOP_ID NUMBER NULL);

COMMENT ON COLUMN ZONA_ABASTECIMENTO.ZABS_CDZONAABASTECIMENTO IS 'CODIGO DA ZONA DE ABASTECIMENTO';
COMMENT ON COLUMN ZONA_ABASTECIMENTO.UNOP_ID IS 'IDENTIFICADOR DA UNIDADE OPERACIONAL ASSOCIADA A ZONA DE ABASTECIMENTO';

ALTER TABLE ZONA_ABASTECIMENTO
ADD CONSTRAINT FK2_ZONA_ABASTECIMENTO FOREIGN KEY (UNOP_ID)
REFERENCES UNIDADE_OPERACIONAL (UNOP_ID) ENABLE;

alter table zona_abastecimento modify (zabs_dszonaabastecimento varchar2(30))