CREATE SEQUENCE GSAN_ADMIN.SQ_CONSUMO_FAIXA_AREA_CATEG 
INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

GRANT ALL PRIVILEGES ON GSAN_ADMIN.SQ_CONSUMO_FAIXA_AREA_CATEG TO GSAN_OPER;
CREATE OR REPLACE PUBLIC SYNONYM SQ_CONSUMO_FAIXA_AREA_CATEG FOR GSAN_ADMIN.SQ_CONSUMO_FAIXA_AREA_CATEG;