-- Ailton Sousa
CREATE SEQUENCE GSAN_ADMIN.SQ_ESPECIFICACAO_TRAMITE 
INCREMENT BY 1 MAXVALUE 9223372036854775807 START WITH 1;

GRANT ALL PRIVILEGES ON GSAN_ADMIN.SQ_ESPECIFICACAO_TRAMITE TO GSAN_OPER;
CREATE OR REPLACE PUBLIC SYNONYM SQ_ESPECIFICACAO_TRAMITE FOR GSAN_ADMIN.SQ_ESPECIFICACAO_TRAMITE;