-- Isaac Silva

CREATE SEQUENCE GSAN_ADMIN.SQ_IMOV_ESGOT_JUDIC
INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

GRANT ALL PRIVILEGES ON GSAN_ADMIN.SQ_IMOV_ESGOT_JUDIC TO GSAN_OPER;
CREATE OR REPLACE PUBLIC SYNONYM SQ_IMOV_ESGOT_JUDIC FOR GSAN_ADMIN.SQ_IMOV_ESGOT_JUDIC;