CREATE SEQUENCE GSAN_ADMIN.SQ_LOCALIDADE_DADO_OPER 
INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

GRANT ALL PRIVILEGES ON GSAN_ADMIN.SQ_LOCALIDADE_DADO_OPER TO GSAN_OPER;
CREATE OR REPLACE PUBLIC SYNONYM SQ_LOCALIDADE_DADO_OPER FOR GSAN_ADMIN.SQ_LOCALIDADE_DADO_OPER;