CREATE SEQUENCE GSAN_ADMIN.SQ_SOLICITACAO_TIPO_ESPEC_MENS
INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

GRANT ALL PRIVILEGES ON GSAN_ADMIN.SQ_SOLICITACAO_TIPO_ESPEC_MENS TO GSAN_OPER;
CREATE OR REPLACE PUBLIC SYNONYM SQ_SOLICITACAO_TIPO_ESPEC_MENS FOR GSAN_ADMIN.SQ_SOLICITACAO_TIPO_ESPEC_MENS;