-- Anderson Italo
INSERT INTO PROCESSO (PROC_ID,PROC_DSPROCESSO,PROC_DSABREVIADO,PROC_ICUSO,PROC_TMULTIMAALTERACAO,PRTP_ID) 
VALUES (SQ_PROCESSO.nextVal,'GERAR RELATORIO LOGRADOURO GERAL','RELOGE',1,{ts '2011-01-27 15:13:08.399'},5);

-- Ailton Sousa
INSERT INTO PROCESSO (PROC_ID,PROC_DSPROCESSO,PROC_DSABREVIADO,PROC_ICUSO,PROC_TMULTIMAALTERACAO,PRTP_ID) 
VALUES (179,'GERAR RELATORIO SUBSISTEMA ESGOTO','RESUBSES',1,current_timestamp,5);

-- Hebert Falcão
INSERT INTO PROCESSO (PROC_ID,PROC_DSPROCESSO,PROC_DSABREVIADO,PROC_ICUSO,PROC_TMULTIMAALTERACAO,PRTP_ID)
VALUES (180,'GER. REL. MANTER SISTEMA ESGOTAMENTO','GEREMSE',1,current_timestamp,5);

-- Bruno Ferreira dos Santos
INSERT INTO PROCESSO (PROC_ID, PROC_DSPROCESSO, PROC_DSABREVIADO, PROC_ICUSO, PROC_TMULTIMAALTERACAO, PRTP_ID) 
VALUES ('181', 'GER. REL. MANTER SUB-BACIA', 'GEREMSB', '1', TO_TIMESTAMP('01/02/11 14:19:29,447000000', 'DD/MM/RR HH24:MI:SS,FF'), '5');
INSERT INTO PROCESSO (PROC_ID, PROC_DSPROCESSO, PROC_DSABREVIADO, PROC_ICUSO, PROC_TMULTIMAALTERACAO, PRTP_ID) 
VALUES ('182', 'GER. REL. MANTER ZONA DE ABASTECIMENTO', 'GEREMZA', '1', TO_TIMESTAMP('02/02/11 14:19:29,447000000', 'DD/MM/RR HH24:MI:SS,FF'), '5');

-- Péricles Tavares
INSERT INTO PROCESSO (PROC_ID, PROC_DSPROCESSO, PROC_DSABREVIADO, PROC_ICUSO, PROC_TMULTIMAALTERACAO, PRTP_ID) 
VALUES ('183', 'GER. REL. MANTER UNIDADE_OPERACIONAL', 'GEREMUO', 1 ,current_timestamp, 5);

-- Isaac Silva
INSERT INTO PROCESSO (PROC_ID,PROC_DSPROCESSO,PROC_DSABREVIADO,PROC_ICUSO,PROC_TMULTIMAALTERACAO,PRTP_ID) 
VALUES (149,'GERAR RELATORIO BACIA','RELOBAC',1,{ts '2011-01-27 15:13:08.399'},5);

-- Péricles Tavares
INSERT INTO PROCESSO (PROC_ID, PROC_DSPROCESSO, PROC_DSABREVIADO, PROC_ICUSO, PROC_TMULTIMAALTERACAO, PRTP_ID) 
VALUES ('185', 'GER. REL. MICROMEDICAO ASSOCIADOS', 'GEREMIC', 1 ,current_timestamp, 5);

INSERT INTO PROCESSO (PROC_ID, PROC_DSPROCESSO, PROC_DSABREVIADO, PROC_ICUSO, PROC_TMULTIMAALTERACAO, PRTP_ID) 
VALUES ('186', 'GER. REL. MACROMEDICAO CONSUMOS', 'GEREMAC', 1 ,current_timestamp, 5);

-- Anderson Italo
INSERT INTO PROCESSO (PROC_ID,PROC_DSPROCESSO,PROC_DSABREVIADO,PROC_ICUSO,PROC_TMULTIMAALTERACAO,PRTP_ID) 
VALUES (SQ_PROCESSO.nextVal,'GERAR RELATORIO GRANDES CONSUMIDORES','REGRCO',1,current_timestamp,5);

-- Anderson Italo
INSERT INTO PROCESSO (PROC_ID,PROC_DSPROCESSO,PROC_DSABREVIADO,PROC_ICUSO,PROC_TMULTIMAALTERACAO,PRTP_ID) 
VALUES (SQ_PROCESSO.nextVal,'GERAR REL. USUARIOS EM DEBITO AUTOMATICO','GEREUDAU',1,current_timestamp,5);

-- Isaac Silva
INSERT INTO PROCESSO (PROC_ID,PROC_DSPROCESSO,PROC_DSABREVIADO,PROC_ICUSO,PROC_TMULTIMAALTERACAO,PRTP_ID) 
VALUES (213,'GERAR REL ESTATIST ATENDIM POR ATENDENTE','GEREESATAT',1,current_timestamp,5);

INSERT INTO PROCESSO (PROC_ID, PROC_DSPROCESSO, PROC_DSABREVIADO, PROC_ICUSO, PROC_TMULTIMAALTERACAO, PRTP_ID) 
VALUES ('214', 'GERAR REL. PRODUTIVIDADE EQUIPES', 'GRPE', '1', TO_TIMESTAMP(SYSDATE, 'DD/MM/RR HH24:MI:SS,FF'), '5')

INSERT INTO PROCESSO (PROC_ID, PROC_DSPROCESSO, PROC_DSABREVIADO, PROC_ICUSO, PROC_TMULTIMAALTERACAO, PRTP_ID) 
VALUES ('215', 'GERAR REL. OS NAO EXECUTADAS EQUIPES', 'GROSNE', '1', current_timestamp, '5')