INSERT INTO PROCESSO_FUNCIONALIDADE (PRFN_ID,PROC_ID,PRFN_TMULTIMAALTERACAO,UNPR_ID,PRFN_NNSEQUENCIALEXECUCAO,FNCD_ID)
VALUES (SQ_PROCESSO_FUNCIONALIDADE.nextVal,131,{ts '2011-01-27 15:23:11.961'},4,1,2016);
 
-- Ailton Sousa
INSERT INTO PROCESSO_FUNCIONALIDADE (PRFN_ID,PROC_ID,PRFN_TMULTIMAALTERACAO,UNPR_ID,PRFN_NNSEQUENCIALEXECUCAO,FNCD_ID)
VALUES (169,179,current_timestamp,4,1,1099);

-- Hebert Falcão
INSERT INTO PROCESSO_FUNCIONALIDADE (PRFN_ID,PROC_ID,PRFN_TMULTIMAALTERACAO,UNPR_ID,PRFN_NNSEQUENCIALEXECUCAO,FNCD_ID)
VALUES (SQ_PROCESSO_FUNCIONALIDADE.nextVal,180,current_timestamp,4,1,618);

-- Péricles Tavares
INSERT INTO PROCESSO_FUNCIONALIDADE (PRFN_ID,PROC_ID,PRFN_TMULTIMAALTERACAO,UNPR_ID,PRFN_NNSEQUENCIALEXECUCAO,FNCD_ID)
VALUES (SQ_PROCESSO_FUNCIONALIDADE.nextVal,183,current_timestamp,4,1,2010);

INSERT INTO PROCESSO_FUNCIONALIDADE (PRFN_ID,PROC_ID,PRFN_TMULTIMAALTERACAO,UNPR_ID,PRFN_NNSEQUENCIALEXECUCAO,FNCD_ID)
VALUES (SQ_PROCESSO_FUNCIONALIDADE.nextVal,185,current_timestamp,4,1,2010);

INSERT INTO PROCESSO_FUNCIONALIDADE (PRFN_ID,PROC_ID,PRFN_TMULTIMAALTERACAO,UNPR_ID,PRFN_NNSEQUENCIALEXECUCAO,FNCD_ID)
VALUES (SQ_PROCESSO_FUNCIONALIDADE.nextVal,185,current_timestamp,4,1,2099); 

INSERT INTO PROCESSO_FUNCIONALIDADE (PRFN_ID,PROC_ID,PRFN_TMULTIMAALTERACAO,UNPR_ID,PRFN_NNSEQUENCIALEXECUCAO,FNCD_ID)
VALUES (SQ_PROCESSO_FUNCIONALIDADE.nextVal,186,current_timestamp,4,1,2101);

-- Anderson Italo
INSERT INTO PROCESSO_FUNCIONALIDADE (PRFN_ID,PROC_ID,PRFN_TMULTIMAALTERACAO,UNPR_ID,PRFN_NNSEQUENCIALEXECUCAO,FNCD_ID)
VALUES (SQ_PROCESSO_FUNCIONALIDADE.nextVal,169,current_timestamp,4,1,2100);

-- Anderson Italo
INSERT INTO PROCESSO_FUNCIONALIDADE (PRFN_ID,PROC_ID,PRFN_TMULTIMAALTERACAO,UNPR_ID,PRFN_NNSEQUENCIALEXECUCAO,FNCD_ID)
VALUES (SQ_PROCESSO_FUNCIONALIDADE.nextVal,189,current_timestamp,4,1,2117);
 
-- Isaac Silva
insert into processo_funcionalidade (prfn_id,proc_id,prfn_tmultimaalteracao,unpr_id,prfn_nnsequencialexecucao,fncd_id)
VALUES (228,213,current_timestamp,4,1,2158);

-- Bruno Ferreira dos Santos
INSERT
INTO processo_funcionalidade
  (
    PRFN_ID,
    PROC_ID,
    PRFN_TMULTIMAALTERACAO,
    UNPR_ID,
    PRFN_NNSEQUENCIALEXECUCAO,
    FNCD_ID
  )
  VALUES
  (
    sq_processo_funcionalidade.nextval ,
    214,
    TO_TIMESTAMP(sysdate,'DD/MM/RR HH24:MI:SS,FF'),
    4,1,2197
  );

INSERT
INTO processo_funcionalidade
  (
    PRFN_ID,
    PROC_ID,
    PRFN_TMULTIMAALTERACAO,
    UNPR_ID,
    PRFN_NNSEQUENCIALEXECUCAO,
    FNCD_ID
  )
  VALUES
  (
    sq_processo_funcionalidade.nextval ,
    215,
    current_timestamp,
    4,1,2198
  );