-- Anderson Italo
INSERT INTO RELATORIO (RELA_ID,RELA_DSRELATORIO,RELA_DSABREVIADA,RELA_ICUSO,RELA_TMULTIMAALTERACAO) 
VALUES (SQ_RELATORIO.nextVal,'Relatorio Logradouro Geral','RELOGE',1,{ts '2011-01-27 13:32:31.877'});

-- Ailton Sousa
INSERT INTO RELATORIO (RELA_ID,RELA_DSRELATORIO,RELA_DSABREVIADA,RELA_ICUSO,RELA_TMULTIMAALTERACAO) 
VALUES (110,'Relatorio Subsistema de Esgoto','RESUBSES',1,current_timestamp);

-- Hebert Falcão
INSERT INTO RELATORIO (RELA_ID,RELA_DSRELATORIO,RELA_DSABREVIADA,RELA_ICUSO,RELA_TMULTIMAALTERACAO) 
VALUES (111,'Relatorio Sistema de Esgotamento','GEREMSE',1,current_timestamp);

-- Péricles Tavares
INSERT INTO RELATORIO (RELA_ID,RELA_DSRELATORIO,RELA_DSABREVIADA,RELA_ICUSO,RELA_TMULTIMAALTERACAO) 
VALUES (112,'Relatorio Unidade Operacional','GEREMUO',1,current_timestamp);

-- Péricles Tavares
INSERT INTO RELATORIO (RELA_ID,RELA_DSRELATORIO,RELA_DSABREVIADA,RELA_ICUSO,RELA_TMULTIMAALTERACAO) 
VALUES (113,'Relatorio Município','GEREMMU',1,current_timestamp);

-- Anderson Italo
INSERT INTO RELATORIO (RELA_ID,RELA_DSRELATORIO,RELA_DSABREVIADA,RELA_ICUSO,RELA_TMULTIMAALTERACAO) 
VALUES (SQ_RELATORIO.nextVal,'Relatorio Manter Sistema Abastecimento','GEMASAB',1,current_timestamp);

-- Isaac Silva
INSERT INTO RELATORIO (RELA_ID,RELA_DSRELATORIO,RELA_DSABREVIADA,RELA_ICUSO,RELA_TMULTIMAALTERACAO) 
VALUES (143,'Relatorio Manter Bacia','GEMABAC',1,current_timestamp);

-- Péricles Tavares
INSERT INTO RELATORIO (RELA_ID,RELA_DSRELATORIO,RELA_DSABREVIADA,RELA_ICUSO,RELA_TMULTIMAALTERACAO) 
VALUES (144,'Relatorio Manter Setor Abastecimento','GEMASAB',1,current_timestamp);

INSERT INTO RELATORIO (RELA_ID,RELA_DSRELATORIO,RELA_DSABREVIADA,RELA_ICUSO,RELA_TMULTIMAALTERACAO) 
VALUES (145,'Relatorio Micromedidores','RELMICRO',1,current_timestamp);

INSERT INTO RELATORIO (RELA_ID,RELA_DSRELATORIO,RELA_DSABREVIADA,RELA_ICUSO,RELA_TMULTIMAALTERACAO) 
VALUES (147,'Relatório de Macromedidores e Micromedidos Consumos','RELMACRO',1,current_timestamp);

-- Anderson Italo
INSERT INTO RELATORIO (RELA_ID,RELA_DSRELATORIO,RELA_DSABREVIADA,RELA_ICUSO,RELA_TMULTIMAALTERACAO) 
VALUES (SQ_RELATORIO.nextVal,'Relatório Usuários em Débito Automático','REUSDEA',1,current_timestamp);

-- Ailton Sousa
INSERT INTO RELATORIO (RELA_ID,RELA_DSRELATORIO,RELA_DSABREVIADA,RELA_ICUSO,RELA_TMULTIMAALTERACAO) 
VALUES (146,'Relatório Consumo por Faixa de Área e Categoria','REGRUUSU',1,current_timestamp);

-- Isaac Silva
insert into relatorio (rela_id,rela_dsrelatorio,rela_dsabreviada,rela_icuso,rela_tmultimaalteracao) 
VALUES (206,'Relat Estatística Atendim por Atendente','RESAT',1,current_timestamp);

INSERT INTO RELATORIO (RELA_ID,RELA_DSRELATORIO,RELA_DSABREVIADA,RELA_ICUSO,RELA_TMULTIMAALTERACAO) VALUES (207,'Relatorio Produtividade Equipe','RPE',1,TO_TIMESTAMP('08/11/06 17:54:48,465828000','DD/MM/RR HH24:MI:SS,FF'));

INSERT INTO RELATORIO (RELA_ID,RELA_DSRELATORIO,RELA_DSABREVIADA,RELA_ICUSO,RELA_TMULTIMAALTERACAO) VALUES (SQ_RELATORIO.nextVal,'Relatorio OS Não Executadada Equipe','RPOSNEE',1,current_timestamp);
