INSERT INTO TABELA (TABE_ID,TABE_TMULTIMAALTERACAO,TABE_NMTABELA,TABE_DSTABELA) VALUES (604,current_timestamp,'UNIDADE_OPERACIONAL','UNIDADE_OPERACIONAL');

-- Bruno Ferreira dos Santos
INSERT INTO TABELA VALUES (627, SYSDATE, 'subbacia', 'SUBBACIA');
INSERT INTO TABELA VALUES (584, SYSDATE, 'imovel_agua_para_todos', 'IMOVEL AGUA PARA TODOS');

-- Isaac Silva
INSERT INTO TABELA VALUES (628, SYSDATE, 'imovel_esgoto_judicial', 'IMOVEL_ESGOTO_JUDICIAL');

-- Isaac Silva
INSERT INTO TABELA VALUES (629, SYSDATE, 'localidade_dado_operacional', 'LOCALIDADE_DADO_OPERACIONAL');

-- Isaac Silva
INSERT INTO TABELA VALUES (630, SYSDATE, 'bacia', 'BACIA');

-- Isaac Silva
INSERT INTO TABELA VALUES (631, SYSDATE, 'subsistema_esgoto', 'SUBSISTEMA_ESGOTO');

-- Isaac Silva
INSERT INTO TABELA VALUES (663, SYSDATE, 'cliente_responsavel', 'CLIENTE_RESPONSAVEL');

-- Ailton Sousa
INSERT INTO TABELA VALUES (632, SYSDATE, 'setor_comercial_vencimento', 'SETOR_COMERCIAL_VENCIMENTO');
