-- Anderson Italo
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,437,{ts '2011-01-31 09:15:02.991'},'SABS_CDSISTEMAABASTECIMENTO','Código',2,NULL);

-- Péricles Tavares
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'unop_id','ID',1,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'unop_cdunidadeopracional','Codigo',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'unop_dsunidadeoperacional','Descricao',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'unop_dsabrevunidadeoperacional','Descricao Abreviada',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'sabs_id','Sistema de Abastecimento',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'loca_id','Localidade',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'unop_nnimovel','Numero do Imovel',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'unop_nnfone','Numero do Telefone',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'unop_nnfoneramal','Numero do Ramal',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'unop_nnfax','Numero do Fax',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'unop_dsemail','Email',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'logr_id','Logradouro',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'bair_id','Bairro',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'cep_id','Cep',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'unop_dstipoinstalacao','Descricao do tipo de Instalacao',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'unop_nncota','Numero da Cota',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'unop_nnlatitude','Latitude',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'unop_nnlongitude','Longitude',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'unop_icuso','Indicador de Uso',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'unop_dscomplementoendereco','Complemento do Endereco',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,604,current_timestamp,'edrf_id','Endereco de ReferEncia',2,NULL);

--SETOR ABASTECIMENTO
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,435,current_timestamp,'stab_cdsetorabastecimento','Codigo do Setor de Abastecimento',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,435,current_timestamp,'zabs_id','ID da Zona de Abastecimento',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,435,current_timestamp,'unop_id','ID do Unidade Operacional',2,NULL);

-- BRUNO FERREIRA DOS SANTOS

INSERT INTO TABELA_COLUNA VALUES (45907, 627, SYSDATE, 'sbac_id', 'IDENTIFICADOR DE SUBBACIA', 1, NULL);
INSERT INTO TABELA_COLUNA VALUES (45908, 627, SYSDATE, 'sbac_cdsubbacia', 'CODIGO DE SUBBACIA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45909, 627, SYSDATE, 'sbac_dssubbacia', 'DESCRICAO DE SUBBACIA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45910, 627, SYSDATE, 'sbac_dsabrevsubbacia', 'DESC. ABREV. DE SUBBACIA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45911, 627, SYSDATE, 'baci_id', 'IDENTIFICADOR DE BACIA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45912, 627, SYSDATE, 'sbac_icuso', 'IDENTIFICADOR DE USO DE SUBBACIA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45913, 627, SYSDATE, 'sbac_tbultimaalteracao', 'ULTIMA ALTERACAO DE SUBBACIA', 2, NULL);

--

INSERT INTO TABELA_COLUNA VALUES (45914, 584, SYSDATE, 'iapt_id', 'IDENTIFICADOR DE IMOVEL AGUA PARA TODOS', 1, NULL);
INSERT INTO TABELA_COLUNA VALUES (45915, 584, SYSDATE, 'iapt_nnidentifcontribuinte', 'IDENTIFICACAO DO CONTRIBUINTE', 1, NULL);
INSERT INTO TABELA_COLUNA VALUES (45916, 584, SYSDATE, 'iapt_nmparticipante', 'NOME DO PARTICIPANTE', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45917, 584, SYSDATE, 'iapt_usuario_id_incl', 'IDENTIFICAÇÃO DO USUARIO DA INCLUSAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45918, 584, SYSDATE, 'iapt_usuario_id_excl', 'IDENTIFICAÇÃO DO USUARIO DA EXCLUSAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45919, 584, SYSDATE, 'iapt_tmcadastramentoprog', 'DATA DE CADASTRAMENTO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45920, 584, SYSDATE, 'iapt_tmhabilitacaoprograma', 'DATA DE HABILITACAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45921, 584, SYSDATE, 'iapt_tmexclusaooprograma', 'DATA DE EXCLUSAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45922, 584, SYSDATE, 'iapt_tmultimaalteracao', 'DATA DE ULTIMA ALTERACAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45923, 584, SYSDATE, 'iapt_ano_mes_referencia_ini', 'REFERENCIA INICIAL', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45924, 584, SYSDATE, 'iapt_ano_mes_referencia_fim', 'REFERENCIA FINAL', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45925, 584, SYSDATE, 'iapt_cdsituacao', 'SITUACAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45926, 584, SYSDATE, 'iapt_cdmotivoexclusao', 'MOTIVO EXCLUSAO', 2, NULL);

--

INSERT INTO TABELA_COLUNA VALUES (46000, 294, SYSDATE, 'muni_id', 'IDENTIFICADOR DE MUNICIPIO', 1, NULL);
INSERT INTO TABELA_COLUNA VALUES (46001, 294, SYSDATE, 'muni_nmmunicipio', 'NOME MUNICIPIO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46002, 294, SYSDATE, 'muni_cdcepinicio', 'CODIGO INICIAL DO CEP', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46003, 294, SYSDATE, 'muni_cdcepfim', 'CODIGO FINAL DO CEP', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46004, 294, SYSDATE, 'muni_cdddd', 'DDD DO MUNICIPIO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46005, 294, SYSDATE, 'rdes_id', 'IDENTIFICAÇÃO DA REGIAO EM DESENVOLVIMENTO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46006, 294, SYSDATE, 'mreg_id', 'IDENTIFICAÇÃO DA MICRO-REGIAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46007, 294, SYSDATE, 'unfe_id', 'IDENTIFICAÇÃO DA UNIDADE FEDERATIVA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46008, 294, SYSDATE, 'muni_icuso', 'INDICADOR DE USO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46009, 294, SYSDATE, 'muni_tmultimaalteracao', 'DATA DE ULTIMA ALTERAÇÃO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46010, 294, SYSDATE, 'muni_dtconcessaoinicio', 'DATA DE INICIO DE CONCESSAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46011, 294, SYSDATE, 'muni_dtconcessaofim', 'DATA FINAL DE CONCESSAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46012, 294, SYSDATE, 'muni_nmprefeitura', 'NOME DA PREFEITURA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46013, 294, SYSDATE, 'muni_edpprefeitura', 'ENDEREÇO DA PREFEITURA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46014, 294, SYSDATE, 'muni_nncnpjprefeitura', 'NUMERO CNPJ DA PREFEITURA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46015, 294, SYSDATE, 'muni_nncontabancaria', 'NUMENRO DA CONTA BANCÁRIA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46016, 294, SYSDATE, 'muni_nmprefeito', 'NOME DO PREFEITO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46017, 294, SYSDATE, 'muni_nncpfprefeito', 'NUMERO CPF DO PREFEITO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46018, 294, SYSDATE, 'muni_nmpartidoprefeito', 'NOME DO PARTIDO DO PREFEITO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46019, 294, SYSDATE, 'muni_nacionalidadeprefeito', 'NACIONALIDADE DO PREFEITO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46020, 294, SYSDATE, 'muni_estadocivilprefeito', 'ESTADO CIVIL DO PREFEITO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46021, 294, SYSDATE, 'muni_cdceppadrao', 'CODIGO DO CEP PADRAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46022, 294, SYSDATE, 'agen_id', 'AGENCIA', 2, NULL);

--

INSERT INTO TABELA_COLUNA VALUES (46048, 479, SYSDATE, 'zabs_id', 'IDENTIFICADOR DE ZONA DE ABASTECIMENTO', 1, NULL);
INSERT INTO TABELA_COLUNA VALUES (46049, 479, SYSDATE, 'zabs_dszonaabastecimento', 'DESCRIÇÃO DE ZONA DE ABASTECIMENTO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46050, 479, SYSDATE, 'zabs_dsabreviado', 'DESCRIÇÃO ABREVIADA DE ZONA DE ABASTECIMENTO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46051, 479, SYSDATE, 'zabs_icuso', 'INDICADOR DE USO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46052, 479, SYSDATE, 'zabs_tbultimaalteracao', 'ULTIMA ALTERACAO DE ZONA DE ABASTECIMENTO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46053, 479, SYSDATE, 'sabs_id', 'IDENTIFICADOR DE SISTEMA DE ABASTECIMENTO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46054, 479, SYSDATE, 'zabs_cdzonaabastecimento', 'CÓDIGO DE ZONA DE ABASTECIMENTO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46055, 479, SYSDATE, 'unop_id', 'IDENTIFICADOR DE UNIDADE OPERACIONAL', 2, NULL);


-- Ailton Sousa
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,503,current_timestamp,'IMOV_NNROTA','NUMERO DA ROTA',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,503,current_timestamp,'IMOV_NNSEGUIMENTO','NUMERO DO SEGMENTO',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,503,current_timestamp,'IMOV_ICCONTRATOCONSUMO','INDICADOR DE CONTRATO DE CONSUMO',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,503,current_timestamp,'IMOV_CDTARIFATEMP','CODIGO DA TARIFA',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,503,current_timestamp,'IMOV_DATAVALIDADETARIFATEMP','DATA DE VALIDADE DA TARIFA TEMPORARIA',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
VALUES (SQ_TABELA_COLUNA.nextVal,503,current_timestamp,'IMOV_ICAGUAPARATODOS','INDICADOR DO AGUA PARA TODOS',2,NULL);

-- Isaac Silva
INSERT INTO TABELA_COLUNA VALUES (46023, 628, SYSDATE, 'imej_id', 'IDENTIFICADOR DE IMOVEL ESGOTO JUDICIAL', 1, NULL);
INSERT INTO TABELA_COLUNA VALUES (46024, 628, SYSDATE, 'imov_id', 'IDENTIFICADOR DE IMOVEL', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46025, 628, SYSDATE, 'imej_cdsitesginc', 'CÓDIGO DA SITUAÇÃO DE ESGOTO NA INCLUSÃO DO PROCESSO JUDICIAL, COM 1 DÍGITOS', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46026, 628, SYSDATE, 'imej_amrefproxfatinc', 'ANO E MÊS DO PRÓXIMO FATURAMENTO PARA O IMÓVEL NA INCLUSÃO DO PROCESSO JUDICIAL, COM 6 DÍGITOS.', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46027, 628, SYSDATE, 'imej_tminc', 'Time Stamp do momento da inclusão do processo judicial, Tipo TimeStamp 26 Caracteres.', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46028, 628, SYSDATE, 'imej_cdsitesgexc', 'CÓDIGO DA  SITUAÇÃO DE ESGOTO NO MOMENTO DA EXCLUSÃO DO IMÓVEL DO PROCESSO JUDICIAL, COM 1 DÍGITOS.', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46029, 628, SYSDATE, 'imej_amrefproxfatexc', 'ANO/MÊS DO PRÓXIMO FATURAMENTO P/ O IMOVEL NO MOMENTO DA EXCLUSÃO DO PROCESSO JUDICIAL, C/ 6 DÍGITOS', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46030, 628, SYSDATE, 'imej_tmexc', 'TIME STAMP DO MOMENTO DA EXCLUSÃO DO IMÓVEL DO PROCESSO JUDICIAL, TIPO TIMESTAMP 26 CARACTERES', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46031, 628, SYSDATE, 'imej_icuso', 'IDENTIFICADOR DE USO DE IMOVEL ESGOTO JUDICIAL', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46032, 628, SYSDATE, 'imej_tmultimaalteracao', 'ULTIMA ALTERACAO DE IMOVEL ESGOTO JUDICIAL', 2, NULL);

-- Isaac Silva
INSERT INTO TABELA_COLUNA VALUES (45953, 629, SYSDATE, 'ldop_id', 'ID DA LOCALIDADE DADO OPERACIONAL', 1, NULL);
INSERT INTO TABELA_COLUNA VALUES (45954, 629, SYSDATE, 'ldop_amreferencia', 'ANO MES REFERENCIAL', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45955, 629, SYSDATE, 'loca_id', 'ID DA LOCALIDADE (TABELA LOCALIDADE)', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45956, 629, SYSDATE, 'ldop_volumeproduzido', 'VOLUME PRODUZIDO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45957, 629, SYSDATE, 'ldop_extensaoredeagua', 'EXTENSAO DA REDE DE AGUA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45958, 629, SYSDATE, 'ldop_extensaoredeesgoto', 'EXTENSAO DA REDE DE ESGOTO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45959, 629, SYSDATE, 'ldop_qtfuncadm', 'QTD. DE FUNCIONÁRIOS DA ADMINISTRAÇÃO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45960, 629, SYSDATE, 'ldop_qtfuncadmterceiro', 'QTD. DE FUNCIONÁRIOS DA ADMINISTRAÇÃOTERCERIZADOS', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45961, 629, SYSDATE, 'ldop_qtfuncopr', 'QTD. DE FUNCIONÁRIOS DA OPERAÇÃO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45962, 629, SYSDATE, 'ldop_qtfuncoprterceiro', 'QTD. DE FUNCIONÁRIOS DA OPERAÇÃO TERCERIZADOS', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45963, 629, SYSDATE, 'ldop_qtsulfatoaluminio', 'QTD. SULFATO DE ALUMINIO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45964, 629, SYSDATE, 'ldop_qtclorogasoso', 'QTD. CLORO GASOSO.', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45965, 629, SYSDATE, 'ldop_qthipoclorsodio', 'QTD. HIPOCLORETO DE SÓDIO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45966, 629, SYSDATE, 'ldop_qtfluor', 'QTD. DE FLÚOR', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45967, 629, SYSDATE, 'ldop_qtconsumoeneergia', 'QTD. DE ENERGIA CONSUMIDA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45968, 629, SYSDATE, 'ldop_qthorasparalizadas', 'QTD. HORAS PARALIZADAS', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45969, 629, SYSDATE, 'ldop_icuso', 'INDICADOR DE USO. 1 - ATIVO (DEFAULT) 2 - INATIVO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45970, 629, SYSDATE, 'ldop_tmultimaalteracao', 'DATA/HORA DA ULTIMA ALTERACAO', 2, NULL);

-- Isaac Silva
INSERT INTO TABELA_COLUNA VALUES (45986, 630, SYSDATE, 'baci_id', 'ID DA BACIA (GERADO PELO SISTEMA)', 1, NULL);
INSERT INTO TABELA_COLUNA VALUES (45987, 630, SYSDATE, 'sesg_id', 'ID DO SISTEMA DE ESGOTO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45988, 630, SYSDATE, 'baci_dsbacia', 'DESCRICAO DA BACIA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45989, 630, SYSDATE, 'baci_icuso', '"INDICADOR DE USO. 1 - ATIVO (DEFAULT) 2 - INATIVO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45990, 630, SYSDATE, 'baci_tmultimaalteracao', 'DATA/HORA DA ULTIMA ALTERACAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45991, 630, SYSDATE, 'baci_cdbacia', 'CODIGO DA BACIA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45992, 630, SYSDATE, 'baci_dsabrevbacia', 'DESCRICAO ABREVIADA BACIA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45993, 630, SYSDATE, 'sses_id', 'ID DA TABELA SUBSISTEMA_ESGOTO', 2, NULL);

-- Isaac Silva
INSERT INTO TABELA_COLUNA VALUES (45994, 631, SYSDATE, 'sses_id', 'ID DO SUBSISTEMA DE ESGOTO', 1, NULL);
INSERT INTO TABELA_COLUNA VALUES (45995, 631, SYSDATE, 'sses_cdsubsistema', 'CODIGO DO SUBSISTEMA DE ESGOTO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45996, 631, SYSDATE, 'sses_dssubsistema', 'DESCRICAO DO SUBSISTEMA DE ESGOTO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45997, 631, SYSDATE, 'sses_dsabrevsubsistema', 'DESCRICAO ABREVIADA DO SUBSISTEMA DE ESGOTO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (45998, 631, SYSDATE, 'sesg_id', 'ID DO SISTEMA DE ESGOTO AO QUAL O SUBSISTEMA ESTA VINCULADO', 2, NULL);
insert into tabela_coluna values (45999, 631, sysdate, 'sses_icuso', 'INDICADOR DE USO. 1 - ATIVO (DEFAULT) 2 - INATIVO', 2, null);
insert into tabela_coluna values (46033, 631, sysdate, 'sses_tmultimaalteracao', 'DATA/HORA DA ULTIMA ALTERACAO', 2, null);

-- Hebert Falcão
DELETE FROM TABELA_COLUNA WHERE TABE_ID = 201;
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (42554,201,SYSDATE,'hicm_id','ID DA CLASSE METROLÓGICA DO HIDRÔMETRO (TABELA HIDROMETRO_CLASSE_METROLOGICA)',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (42543,201,SYSDATE,'hicp_id','ID DA CAPACIDADE DE HIDROMETRO (TABELA HIDROMETRO_CAPACIDADE)',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (46034,201,SYSDATE,'hidi_ichidrometroconposto','INDICADOR DE HIDROMETRO COMPOSTO',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (46035,201,SYSDATE,'hidi_nnfatorconversao','FATOR DE CONVERSAO DO HIDROMETRO',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (42556,201,SYSDATE,'hidm_id','CODIGO DO DIAMETRO DE HIDROMETRO (TABELA HIDROMETRO_MARCA)',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (42547,201,SYSDATE,'hidr_dtaquisicao','DATA DE AQUISICAO DO HIDROMETRO',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (42551,201,SYSDATE,'hidr_dtbaixa','DATA DA BAIXA DO HIDROMETRO',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (42550,201,SYSDATE,'hidr_dtultimarevisao','DATA DA ULTIMA REVISAO DO HIDROMETRO',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (42549,201,SYSDATE,'hidr_icmacro','INDICADOR DE MACROMEDIDOR;1 - COMERCIAL;2 - OPERACIONAL',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (42545,201,SYSDATE,'hidr_id','ID DO HIDROMETRO',1,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (42548,201,SYSDATE,'hidr_nnanofabricacao','ANO DE FABRICACAO DO HIDROMETRO',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (42553,201,SYSDATE,'hidr_nndigitosleitura','NUMERO DE DIGITOS PARA LEITURA',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (42546,201,SYSDATE,'hidr_nnhidrometro','NUMERO DO HIDROMETRO',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (42552,201,SYSDATE,'hidr_nnleituraacumulada','NUMERO DA LEITURA ACUMULADA DO HIDROMETRO',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (37764,201,SYSDATE,'hidr_tmultimaalteracao','DATA/HORA DA ULTIMA ALTERACAO',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (42539,201,SYSDATE,'hila_id','ID DO LOCAL DE ARMAZENAGEM DO HIDRÔMETRO (TABELA HIDROMETRO_LOCAL_ARMAZENAGEM)',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (37762,201,SYSDATE,'himb_id','ID DO MOTIVO BAIXA DO HIDROMETRO (TABELA HIDROMETRO_MOTIVO_BAIXA)',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (42555,201,SYSDATE,'himc_id','ID DA MARCA DE HIDROMETRO (TABELA HIDROMETRO_MARCA)',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (42541,201,SYSDATE,'hist_id','ID DA SITUACAO DO HIDROMETRO (TABELA HIDROMETRO_SITUACAO)',2,null);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (42544,201,SYSDATE,'hitp_id','ID DO TIPO DE HIDROMETRO (TABELA HIDROMETRO_TIPO)',2,null);

-- Isaac Silva
delete from TABELA_COLUNA where TABE_ID = 439;
insert into tabela_coluna values (46041, 439, sysdate, 'sesg_id', 'ID DO SISTEMA DE ESGOTO', 1, null);
insert into tabela_coluna values (46042, 439, sysdate, 'sesg_dssistemaesgoto', 'DESCRICAO DO SISTEMA DE ESGOTO', 2, null);
insert into tabela_coluna values (46043, 439, sysdate, 'sesg_dsabreviado', 'DESCRICAO ABREVIADA DO SISTEMA DE ESGOTO', 2, null);
insert into tabela_coluna values (46044, 439, sysdate, 'dves_id', 'ID DA DIVISAO ESGOTO', 2, null);
insert into tabela_coluna values (46045, 439, sysdate, 'sett_id', 'TIPO DE TRATAMENTO DE ESGOTO', 2, null);
INSERT INTO TABELA_COLUNA VALUES (46046, 439, SYSDATE, 'sesg_icuso', 'INDICADOR DE USO. 1 - ATIVO (DEFAULT) 2 - INATIVO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46047, 439, SYSDATE, 'sesg_tmultimaalteracao', 'DATA/HORA DA ULTIMA ALTERACAO', 2, NULL);

-- Isaac Silva
delete from TABELA_COLUNA where TABE_ID = 265;
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43204,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'UNEG_ID','ID DA UNIDADE DE NEGOCIO (TABELA UNIDADE_NEGOCIO)',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43196,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LPOR_ID','ID DO PORTE DA LOCALIDADE (TABELA LOCALIDADE_PORTE)',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43183,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LOGR_ID','ID DO LOGRADOURO (TABELA LOGRADOURO)',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43199,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LOCA_TMULTIMAALTERACAO','DATA/HORA DA ULTIMA ALTERACAO',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43184,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LOCA_NNIMOVEL','NUMERO DO IMOVEL',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43189,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LOCA_NNFONERAMAL','NUMERO DO RAMAL TELEFONICO',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43188,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LOCA_NNFONE','NUMERO DO TELEFONE',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43190,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LOCA_NNFAX','NUMERO DO FAX',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43192,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LOCA_NNCONSUMOGRANDEUSUARIO','LIMITE DE CONSUMO PARA GRANDE CONSUMIDOR',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43182,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LOCA_NMLOCALIDADE','NOME DA LOCALIDADE',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43181,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LOCA_ID','ID DA LOCALIDADE',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43197,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LOCA_ICUSO','INDICADOR DE USO.1 - ATIVO (DEFAULT)2 - INATIVO',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43205,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LOCA_ICINFORMATIZADA','INDICADOR DE LOCALIDADE INFORMATIZADA.1 - SIM 2 - NAO',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43191,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LOCA_DSEMAIL','E-MAIL',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43185,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LOCA_DSCOMPLEMENTOENDERECO','COMPLEMENTODO ENDERECO',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43202,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LOCA_CDICMS','CODIGO DO ICMS',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43193,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LOCA_CDELO','CODIGO DO ELO (TABELA LOCALIDADE)',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43203,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LOCA_CDCENTROCUSTO','CODIGO DO CENTRO DE CUSTO',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43201,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LGCP_ID','ID DO LOGRADOURO/CEP DO ENDERECO INFORMADO (TABELA LOGRADORO_CEP)',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43200,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LGBR_ID','ID DO LOGRADOURO/BAIRRO DO ENDERECO INFORMADO (TABELA LOGRADORO_BAIRRO)',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43195,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'LCLA_ID','ID DA CLASSE DA LOCALIDADE (TABELA LOCALIDADE_CLASSE)',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43207,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'HILA_ID','ID DO LOCAL DE ARMAZENAGM DE HIDROMETROS (TABEL HIDROMETRO_LOCAL_ARMAZENAGEM)',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43194,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'GREG_ID','ID DA REGENCIA REGIONAL (TABELA GERENCIA_REGIONAL)',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43186,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'EDRF_ID','ID DO DA REFERENCIA DO ENDERECO (TABELA ENDERECO_REFERENCIA)',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43206,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'CLIE_ID','ID DO CLIENTE (TABELA CLIENTE)',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43187,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'CEP_ID','ID DO CODIGO DE ENDERECAMENTO POSTAL (TABELA CEP)',2,null);
Insert into TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) values (43198,265,to_timestamp('13/11/08 08:21:54,935000000','DD/MM/RR HH24:MI:SS,FF'),'BAIR_ID','ID DOBAIRRO (TABELA BAIRRO)',2,null);

-- Isaac Silva
INSERT INTO TABELA_COLUNA VALUES (46106, 663, SYSDATE, 'clrs_id', 'ID DA RELACAO CLIENTE/RESPONSAVEL', 1, NULL);
INSERT INTO TABELA_COLUNA VALUES (46107, 663, SYSDATE, 'clie_id', 'CODIGO DO CLIENTE', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46108, 663, SYSDATE, 'clrs_icmulta', 'INDICADOR DE COBRANCA DE MULTA. 1 - SIM 2 - NAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46109, 663, SYSDATE, 'clrs_icjuros', 'INDICADOR DE COBRANCA DE JUROS. 1 - SIM 2 - NAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46110, 663, SYSDATE, 'clrs_iccorrecao', 'INDICADOR DE COBRANCA DE CORRECAO. 1 - SIM 2 - NAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46111, 663, SYSDATE, 'clrs_icimpostofederal', 'INDICADOR DE IMPOSTO FEDERAL DESTACADO. 1 - SIM 2 - NAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46112, 663, SYSDATE, 'agen_id', 'ID DA AGENCIA BANCARIA DO RESPONSAVEL', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46113, 663, SYSDATE, 'clrs_nncontabancaria', 'NUMERO DA CONTA BANCARIA DO RESPONSAVEL', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46114, 663, SYSDATE, 'clrs_icuso', 'INDICADOR DE USO. 1 - ATIVO (DEFAULT) 2 - INATIVO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46115, 663, SYSDATE, 'clrs_dtultimaalteracao', 'DATA/HORA DA ULTIMA ALTERACAO', 2, NULL);

-- Isaac Silva
INSERT INTO TABELA_COLUNA VALUES (46116, 33, SYSDATE, 'cles_id', 'ID DO CLIENTE TIPO ESPECIAL', 2, NULL);

-- Ailton Sousa
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
	VALUES (46180,632,current_timestamp,'stcv_id','ID DO SETOR COMERCIAL VENCIMENTO',1,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
	VALUES (46181,632,current_timestamp,'loca_id','ID DA LOCALIDADE',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
	VALUES (46182,632,current_timestamp,'stcm_id','ID DO SETOR COMERCIAL',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
	VALUES (46183,632,current_timestamp,'stcv_diavencimento','DIA DE VENCIMENTO PARA O SETOR',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
	VALUES (46184,632,current_timestamp,'stcv_icuso','INDICADOR DE USO. 1 - ATIVO (DEFAULT) 2 - INATIVO',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) 
	VALUES (46185,632,current_timestamp,'stcv_tmultimaalteracao','DATA/HORA DA ULTIMA ALTERACAO',2,NULL);
	
-- Bruno Ferreira dos Santos
INSERT INTO TABELA_COLUNA VALUES (46158, 205, SYSDATE, 'hidr_id', 'IDENTIFICACAO DO HIDROMETRO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46159, 205, SYSDATE, 'hidi_dtinstalacaohidrometro', 'DATA INSTALAÇÃO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46160, 205, SYSDATE, 'medt_id', 'IDENTIFICAÇÃO DO TIPO DE MEDIÇÃO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46161, 205, SYSDATE, 'rttp_id', 'IDENTIFICAÇÃO DO TIPO DE RATEIO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46162, 205, SYSDATE, 'hili_id', 'IDENTIFICAÇÃO DO LOCAL DE INSTALAÇÃO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46163, 205, SYSDATE, 'hipr_id', 'IDENTIFICAÇÃO DA PROTEÇÃO DO HIDROMETRO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46164, 205, SYSDATE, 'hidi_nnleiturainstalacaohidrom', 'NUMERO DA LEITURA DA INSTALAÇÃO DO HIDROMETRO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46165, 205, SYSDATE, 'hidi_dtretiradahidrometro', 'DATA DE RETIRADA DO HIDROMETRO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46166, 205, SYSDATE, 'hidi_nnleituraretiradahidromet', 'NUMERO DA LEITURA DA RETIRADA DO HIDROMETRO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46167, 205, SYSDATE, 'hidi_dtinstalacaohidrometrosis', 'DATA DE INTALAÇÃO DO SISTEMA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46168, 205, SYSDATE, 'hidi_nnleituracorte', 'NUMERO DA LEITURA DE CORTE', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46169, 205, SYSDATE, 'hidi_iccavalete', 'INDICADOR DE CAVALETE', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46170, 205, SYSDATE, 'hidi_icinstalacaosubstituicao', 'INDICADOR DE SUBSTITUIÇÃO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46171, 205, SYSDATE, 'hidi_nnleiturasupressao', 'NUMERO DA LEITURA DE SUPRESSÃO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46172, 205, SYSDATE, 'hidi_tmultimaalteracao', 'DATA DA ULTIMA ALTERAÇÃO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46173, 205, SYSDATE, 'imov_id', 'IDENTIFICAÇÃO DO IMÓVEL', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46174, 205, SYSDATE, 'lagu_id', 'IDENTIFICAÇÃO DA LIGAÇÃO DE AGUA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46175, 205, SYSDATE, 'hidi_nnselo', 'NUMERO DO SELO DO HIDROMETRO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46176, 205, SYSDATE, 'hidi_nnhidrometro', 'NUMERO DO HIDROMETRO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46177, 205, SYSDATE, 'hidi_ictrocaprotecao', 'INDICADOR DE TROCA DE PROTEÇÃO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46178, 205, SYSDATE, 'hidi_ictrocaregistro', 'INDICADOR DE TROCA DE REGISTRO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (46179, 205, SYSDATE, 'hidi_id', 'IDENTIFICADOR DE HIDROMETRO INSTALAÇÃO HISTÓRICO', 1, NULL);

-- Isaac Silva
-- Imovel
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 503, SYSDATE, 'imov_nmimovel', 'NOME IMOVEL', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 503, SYSDATE, 'imov_nnareaconstruida', 'AREA CONSTRUIDA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 503, SYSDATE, 'imov_nncontratoenergia', 'NUMERO CELPE', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 503, SYSDATE, 'imov_nniptu', 'NUMERO IPTU', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 503, SYSDATE, 'imov_nnleituraexcecao', 'NUMERO LEITURA EXCECAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 503, SYSDATE, 'imov_nnmoradortrabalhador', 'NUMERO MORADOR TRABALHADOR', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 503, SYSDATE, 'imov_nnparcelamento', 'NUMERO PARCELAMENTO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 503, SYSDATE, 'imov_nnreparcelamento', 'NUMERO REPARCELAMENTO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 503, SYSDATE, 'imov_nnreparcelamentoconsecuti', 'NUMERO REPARCELAMENTO CONSECUTIVO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 503, SYSDATE, 'imov_nnretificacao', 'NUMERO RETIFICACAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 503, SYSDATE, 'imov_tmultimaalteracao', 'ULTIMA ALTERACAO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 503, SYSDATE, 'imov_voreservatorioinferior', 'VOLUME RESERVATORIO INFERIOR', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 503, SYSDATE, 'logr_id', 'LOGRADOURO', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 503, SYSDATE, 'ltan_id', 'LEITURA ANORMALIDADE', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 503, SYSDATE, 'qdra_nnquadra', 'NUMERO QUADRA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 503, SYSDATE, 'rend_id', 'FAIXA RENDA FAMILIAR', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 503, SYSDATE, 'resv_idreservatorioinferior', 'RESERVATORIO VOLUME FAIXA INFERIOR', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.nextVal, 503, SYSDATE, 'stcm_cdsetorcomercial', 'CODIGO SETOR COMERCIAL', 2, NULL);

-- Péricles Tavares
-- Registro Atendimento Solicitante
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 398, SYSDATE, 'cltp_id', 'TIPO DE CLIENTE', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 398, SYSDATE, 'raso_nncpf', 'NUMERO DO CPF - PESSOA FISICA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 398, SYSDATE, 'raso_nnrg', 'NUMERO DO RG - PESSOA FISICA', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 398, SYSDATE, 'oerg_id', 'ORGAO EXPEDIDOR DO RG', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 398, SYSDATE, 'unfe_id', 'UNIDADE DE FEDERACAO DO ORGAO EXPEDIDOR/INSCRICAO ESTADUAL ', 2, NULL);
INSERT INTO TABELA_COLUNA VALUES (SQ_TABELA_COLUNA.NEXTVAL, 398, SYSDATE, 'raso_nncnpj', 'NUMERO DO CNPJ - PESSOA JURIDICA', 2, NULL);

-- Hebert Falcão
-- CR81410
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (SQ_TABELA_COLUNA.NEXTVAL,630,SYSDATE,'baci_nnaducao','ADUÇÃO (M3/H)',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (SQ_TABELA_COLUNA.NEXTVAL,630,SYSDATE,'baci_nndemandaenergia','DEMANDA DE ENERGIA (KW)',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (SQ_TABELA_COLUNA.NEXTVAL,630,SYSDATE,'baci_nnlatitude','LATITUDE',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (SQ_TABELA_COLUNA.NEXTVAL,630,SYSDATE,'baci_nnlongitude','LONGITUDE',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (SQ_TABELA_COLUNA.NEXTVAL,630,SYSDATE,'baci_nnimovel','NUMERO DO IMOVEL',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (SQ_TABELA_COLUNA.NEXTVAL,630,SYSDATE,'baci_dscomplementoendereco','COMPLEMENTO DO ENDERECO',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (SQ_TABELA_COLUNA.NEXTVAL,630,SYSDATE,'edrf_id','ENDERECO',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (SQ_TABELA_COLUNA.NEXTVAL,630,SYSDATE,'lgbr_id','BAIRRO',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (SQ_TABELA_COLUNA.NEXTVAL,630,SYSDATE,'lgcp_id','CEP',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (SQ_TABELA_COLUNA.NEXTVAL,630,SYSDATE,'baci_nncota','ALTITUDE',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (SQ_TABELA_COLUNA.NEXTVAL,630,SYSDATE,'baci_nnunidade','UNIDADE (M3/H)',2,NULL);

-- Hebert Falcão
-- CR81411
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (SQ_TABELA_COLUNA.NEXTVAL,627,SYSDATE,'sbac_nnextensao','EXTENSAO',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (SQ_TABELA_COLUNA.NEXTVAL,627,SYSDATE,'sbac_nndiametro','DIAMETRO',2,NULL);
INSERT INTO TABELA_COLUNA (TBCO_ID,TABE_ID,TBCO_TMULTIMAALTERACAO,TBCO_NMCOLUNA,TBCO_DSCOLUNA,TBCO_ICPRIMARYKEY,TBCO_NMABREVIADO) VALUES (SQ_TABELA_COLUNA.NEXTVAL,627,SYSDATE,'mrde_id','MATERIAL',2,NULL);
