/*
 * Copyright (C) 2007-2007 the GSAN – Sistema Integrado de Gestão de Serviços de Saneamento
 *
 * This file is part of GSAN, an integrated service management system for Sanitation
 *
 * GSAN is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License.
 *
 * GSAN is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place – Suite 330, Boston, MA 02111-1307, USA
 */

package gcom.contabil;

import gcom.interceptor.ObjetoTransacao;
import gcom.seguranca.acesso.Modulo;
import gcom.seguranca.transacao.Tabela;
import gcom.util.ErroRepositorioException;
import gcom.util.RepositorioUtilHBM;
import gcom.util.SistemaException;
import gcom.util.filtro.Filtro;

import java.util.Date;

/**
 * <p>
 * Title: GCOM
 * </p>
 * <p>
 * Description: Sistema de Gestão Comercial
 * </p>
 * <p>
 * Copyright: Copyright (c) 2004
 * </p>
 * 
 * @author Genival Barbosa
 * @created 7 de Julho de 2011
 * @version 1.0
 */
public class EventoComercial
				extends ObjetoTransacao {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3531961234356691933L;

	private int id;

	private String descricao;

	private Modulo modulo;

	private Tabela tabelaReferencia;

	private String indicadorComplemento;

	private Short indicadorUso;

	private Date ultimaAlteracao;

	private String codigoConstante;

	// Constantes

	public static Integer EVENTO_COMERCIAL_INCLUIR_CONTA_AGUA;

	public static Integer EVENTO_COMERCIAL_INCLUIR_CONTA_ESGOTO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_CONTA_DEBITO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_CONTA_CREDITO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_CONTA_PARCELAMENTO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_CONTA_IMPOSTO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_AGUA;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_ESGOTO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_DEBITO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_CREDITO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_PARCELAMENTO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_IMPOSTO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_DEBITO_A_COBRAR_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_DEBITO_A_COBRAR_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_DEBITO_A_COBRAR_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_DEBITO_A_COBRAR_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_TRANSFERENCIA_DEBITO_LONGO_PARA_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_CREDITO_A_REALIZAR_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_CREDITO_A_REALIZAR_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CREDITO_A_REALIZAR_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CREDITO_A_REALIZAR_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_TRANSFERENCIA_CREDITO_LONGO_PARA_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_AGUA;

	public static Integer EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_ESGOTO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_DEBITO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_CREDITO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_PARCELAMENTO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_IMPOSTO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_GUIA_PAGAMENTO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_GUIA_PAGAMENTO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_AGUA;

	public static Integer EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_ESGOTO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_DEBITO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_CREDITO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_PARCELAMENTO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_IMPOSTO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_NAO_IDENTIFICADO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_AGUA_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_ESGOTO_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_PARCELAMENTO_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_FINANCIAMENTO_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_AGUA_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_ESGOTO_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_PARCELAMENTO_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_FINANCIAMENTO_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_JUROS_CORRECAO_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_TRANSFERENCIA_PARCELAMENTO_LONGO_PARA_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_AGUA_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_ESGOTO_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PARCELAMENTO_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_FINANCIAMENTO_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_AGUA_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_ESGOTO_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PARCELAMENTO_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_FINANCIAMENTO_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_JUROS_CORRECAO_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_GUIA_PAGAMENTO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_DEBITO_A_COBRAR;

	public static Integer EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_GUIA_PAGAMENTO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_DEBITO_A_COBRAR;

	public static Integer EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_AGUA;

	public static Integer EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_ESGOTO;

	public static Integer EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_DEBITO;

	public static Integer EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_CREDITO;

	public static Integer EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_PARCELAMENTO;

	public static Integer EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_IMPOSTO;

	public static Integer EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_GUIA_PAGAMENTO;

	public static Integer EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_DEBITO_A_COBRAR;

	public static Integer EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_NAO_IDENTIFICADO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_PARCELAMENTO_SALDO_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_PARCELAMENTO_SALDO_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_JUROS_CORRECAO_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_JUROS_CORRECAO_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PDD_FAIXA1;

	public static Integer EVENTO_COMERCIAL_PDD_FAIXA2;

	public static Integer EVENTO_COMERCIAL_PDD_FAIXA3;

	public static Integer EVENTO_COMERCIAL_PDD_FAIXA1_MISTO;

	public static Integer EVENTO_COMERCIAL_PDD_FAIXA2_MISTO;

	public static Integer EVENTO_COMERCIAL_PDD_FAIXA3_MISTO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_AGUA;

	public static Integer EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_ESGOTO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_DEBITO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_CREDITO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_PARCELAMENTO;

	public static Integer EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_IMPOSTO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_APT_AGUA;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_APT_ESGOTO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_APT_DEBITO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_APT_CREDITO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_APT_PARCELAMENTO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_APT_IMPOSTO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_AGUA;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_ESGOTO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_DEBITO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_CREDITO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_PARCELAMENTO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_IMPOSTO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_AGUA;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_ESGOTO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_DEBITO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_CREDITO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_PARCELAMENTO;

	public static Integer EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_IMPOSTO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_AGUA_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_ESGOTO_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_PARCELAMENTO_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_FINANCIAMENTO_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_AGUA_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_ESGOTO_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_PARCELAMENTO_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_FINANCIAMENTO_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_JUROS_CORRECAO_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_TRANSFERENCIA_PARCELAMENTO_PREFEITURA_LONGO_PARA_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_AGUA_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_ESGOTO_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_PARCELAMENTO_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_FINANCIAMENTO_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_AGUA_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_ESGOTO_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_PARCELAMENTO_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_FINANCIAMENTO_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_JUROS_CORRECAO_CURTO_PRAZO;

	public static Integer EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_JUROS_CORRECAO_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_JUROS_CORRECAO_LONGO_PRAZO;

	public static Integer EVENTO_COMERCIAL_BAIXA_CONTA_DUPLICIDADE_EXCESSO;

	public static Integer EVENTO_COMERCIAL_BAIXA_CONTA_INEXISTENTE;

	public static Integer EVENTO_COMERCIAL_BAIXA_GUIA_PAGAMENTO_DUPLICIDADE_EXCESSO;

	public static Integer EVENTO_COMERCIAL_BAIXA_GUIA_PAGAMENTO_INEXISTENTE;

	public static Integer EVENTO_COMERCIAL_BAIXA_DEBITO_A_COBRAR_DUPLICIDADE_EXCESSO;

	public static Integer EVENTO_COMERCIAL_BAIXA_DEBITO_A_COBRAR_INEXISTENTE;

	public static Integer EVENTO_COMERCIAL_PDD_FAIXA1_PUBLICO_ESTADUAL;

	public static Integer EVENTO_COMERCIAL_PDD_FAIXA2_PUBLICO_ESTADUAL;

	public static Integer EVENTO_COMERCIAL_PDD_FAIXA3_PUBLICO_ESTADUAL;

	public static Integer EVENTO_COMERCIAL_PDD_FAIXA1_BAIXA;

	public static Integer EVENTO_COMERCIAL_PDD_FAIXA2_BAIXA;

	public static Integer EVENTO_COMERCIAL_PDD_FAIXA3_BAIXA;

	public String getDescricao(){

		return descricao;
	}

	public void setDescricao(String descricao){

		this.descricao = descricao;
	}

	public Modulo getModulo(){

		return modulo;
	}

	public void setModulo(Modulo modulo){

		this.modulo = modulo;
	}

	public Tabela getTabelaReferencia(){

		return tabelaReferencia;
	}

	public void setTabelaReferencia(Tabela tabelaReferencia){

		this.tabelaReferencia = tabelaReferencia;
	}

	public void setIndicadorComplemento(String indicadorComplemento){

		this.indicadorComplemento = indicadorComplemento;
	}

	public String getIndicadorComplemento(){

		return indicadorComplemento;
	}

	@Override
	public Date getUltimaAlteracao(){

		return ultimaAlteracao;
	}

	@Override
	public Filtro retornaFiltro(){

		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setUltimaAlteracao(Date ultimaAlteracao){

		this.ultimaAlteracao = ultimaAlteracao;

	}

	@Override
	public String[] retornaCamposChavePrimaria(){

		// TODO Auto-generated method stub
		return null;
	}

	public void setId(int id){

		this.id = id;
	}

	public int getId(){

		return id;
	}

	public void setIndicadorUso(Short indicadorUso){

		this.indicadorUso = indicadorUso;
	}

	public Short getIndicadorUso(){

		return indicadorUso;
	}

	public String getCodigoConstante(){

		return codigoConstante;
	}

	public void setCodigoConstante(String codigoConstante){

		this.codigoConstante = codigoConstante;
	}

	/**
	 * Método criado para inicializar as constantes.
	 * 
	 * @author Hugo Lima
	 * @date 26/06/2012
	 */
	public static void inicializarConstantes(){

		EVENTO_COMERCIAL_INCLUIR_CONTA_AGUA = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_CONTA_AGUA.getId();
		EVENTO_COMERCIAL_INCLUIR_CONTA_ESGOTO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_CONTA_ESGOTO.getId();
		EVENTO_COMERCIAL_INCLUIR_CONTA_DEBITO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_CONTA_DEBITO.getId();
		EVENTO_COMERCIAL_INCLUIR_CONTA_CREDITO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_CONTA_CREDITO.getId();
		EVENTO_COMERCIAL_INCLUIR_CONTA_PARCELAMENTO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_CONTA_PARCELAMENTO.getId();
		EVENTO_COMERCIAL_INCLUIR_CONTA_IMPOSTO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_CONTA_IMPOSTO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_AGUA = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_AGUA.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_ESGOTO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_ESGOTO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_DEBITO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_DEBITO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_CREDITO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_CREDITO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_PARCELAMENTO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_PARCELAMENTO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_IMPOSTO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_IMPOSTO.getId();
		EVENTO_COMERCIAL_INCLUIR_DEBITO_A_COBRAR_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_DEBITO_A_COBRAR_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_INCLUIR_DEBITO_A_COBRAR_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_DEBITO_A_COBRAR_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_CANCELAR_DEBITO_A_COBRAR_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_DEBITO_A_COBRAR_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_CANCELAR_DEBITO_A_COBRAR_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_DEBITO_A_COBRAR_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_TRANSFERENCIA_DEBITO_LONGO_PARA_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_TRANSFERENCIA_DEBITO_LONGO_PARA_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_INCLUIR_CREDITO_A_REALIZAR_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_CREDITO_A_REALIZAR_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_INCLUIR_CREDITO_A_REALIZAR_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_CREDITO_A_REALIZAR_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_CANCELAR_CREDITO_A_REALIZAR_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CREDITO_A_REALIZAR_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_CANCELAR_CREDITO_A_REALIZAR_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CREDITO_A_REALIZAR_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_TRANSFERENCIA_CREDITO_LONGO_PARA_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_TRANSFERENCIA_CREDITO_LONGO_PARA_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_AGUA = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_AGUA.getId();
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_ESGOTO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_ESGOTO.getId();
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_DEBITO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_DEBITO.getId();
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_CREDITO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_CREDITO.getId();
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_PARCELAMENTO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_PARCELAMENTO.getId();
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_IMPOSTO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_IMPOSTO.getId();
		EVENTO_COMERCIAL_INCLUIR_GUIA_PAGAMENTO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_GUIA_PAGAMENTO.getId();
		EVENTO_COMERCIAL_CANCELAR_GUIA_PAGAMENTO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_GUIA_PAGAMENTO.getId();
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_AGUA = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_AGUA.getId();
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_ESGOTO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_ESGOTO
						.getId();
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_DEBITO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_DEBITO
						.getId();
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_CREDITO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_CREDITO
						.getId();
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_PARCELAMENTO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_PARCELAMENTO
						.getId();
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_IMPOSTO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_IMPOSTO
						.getId();
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_NAO_IDENTIFICADO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_NAO_IDENTIFICADO
						.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_AGUA_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_AGUA_CURTO_PRAZO.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_ESGOTO_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_ESGOTO_CURTO_PRAZO.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_PARCELAMENTO_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_PARCELAMENTO_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_FINANCIAMENTO_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_FINANCIAMENTO_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_AGUA_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_AGUA_LONGO_PRAZO.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_ESGOTO_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_ESGOTO_LONGO_PRAZO.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_PARCELAMENTO_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_PARCELAMENTO_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_FINANCIAMENTO_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_FINANCIAMENTO_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_JUROS_CORRECAO_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_JUROS_CORRECAO_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_TRANSFERENCIA_PARCELAMENTO_LONGO_PARA_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_TRANSFERENCIA_PARCELAMENTO_LONGO_PARA_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_AGUA_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_AGUA_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_ESGOTO_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_ESGOTO_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PARCELAMENTO_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PARCELAMENTO_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_FINANCIAMENTO_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_FINANCIAMENTO_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_AGUA_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_AGUA_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_ESGOTO_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_ESGOTO_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PARCELAMENTO_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PARCELAMENTO_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_FINANCIAMENTO_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_FINANCIAMENTO_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_JUROS_CORRECAO_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_JUROS_CORRECAO_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_GUIA_PAGAMENTO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_GUIA_PAGAMENTO.getId();
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_DEBITO_A_COBRAR = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_DEBITO_A_COBRAR.getId();
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_GUIA_PAGAMENTO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_GUIA_PAGAMENTO
						.getId();
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_DEBITO_A_COBRAR = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_DEBITO_A_COBRAR
						.getId();
		EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_AGUA = EventoComercialEnum.EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_AGUA.getId();
		EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_ESGOTO = EventoComercialEnum.EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_ESGOTO.getId();
		EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_DEBITO = EventoComercialEnum.EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_DEBITO.getId();
		EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_CREDITO = EventoComercialEnum.EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_CREDITO.getId();
		EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_PARCELAMENTO = EventoComercialEnum.EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_PARCELAMENTO.getId();
		EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_IMPOSTO = EventoComercialEnum.EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_IMPOSTO.getId();
		EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_GUIA_PAGAMENTO = EventoComercialEnum.EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_GUIA_PAGAMENTO.getId();
		EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_DEBITO_A_COBRAR = EventoComercialEnum.EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_DEBITO_A_COBRAR
						.getId();
		EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_NAO_IDENTIFICADO = EventoComercialEnum.EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_NAO_IDENTIFICADO
						.getId();
		EVENTO_COMERCIAL_CANCELAR_PARCELAMENTO_SALDO_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_PARCELAMENTO_SALDO_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_CANCELAR_PARCELAMENTO_SALDO_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_PARCELAMENTO_SALDO_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_JUROS_CORRECAO_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_JUROS_CORRECAO_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_JUROS_CORRECAO_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_JUROS_CORRECAO_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_PDD_FAIXA1 = EventoComercialEnum.EVENTO_COMERCIAL_PDD_FAIXA1.getId();
		EVENTO_COMERCIAL_PDD_FAIXA2 = EventoComercialEnum.EVENTO_COMERCIAL_PDD_FAIXA2.getId();
		EVENTO_COMERCIAL_PDD_FAIXA3 = EventoComercialEnum.EVENTO_COMERCIAL_PDD_FAIXA3.getId();
		EVENTO_COMERCIAL_PDD_FAIXA1_MISTO = EventoComercialEnum.EVENTO_COMERCIAL_PDD_FAIXA1_MISTO.getId();
		EVENTO_COMERCIAL_PDD_FAIXA2_MISTO = EventoComercialEnum.EVENTO_COMERCIAL_PDD_FAIXA2_MISTO.getId();
		EVENTO_COMERCIAL_PDD_FAIXA3_MISTO = EventoComercialEnum.EVENTO_COMERCIAL_PDD_FAIXA3_MISTO.getId();
		EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_AGUA = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_AGUA.getId();
		EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_ESGOTO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_ESGOTO.getId();
		EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_DEBITO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_DEBITO.getId();
		EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_CREDITO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_CREDITO.getId();
		EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_PARCELAMENTO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_PARCELAMENTO.getId();
		EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_IMPOSTO = EventoComercialEnum.EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_IMPOSTO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_APT_AGUA = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_APT_AGUA.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_APT_ESGOTO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_APT_ESGOTO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_APT_DEBITO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_APT_DEBITO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_APT_CREDITO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_APT_CREDITO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_APT_PARCELAMENTO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_APT_PARCELAMENTO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_APT_IMPOSTO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_APT_IMPOSTO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_AGUA = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_AGUA.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_ESGOTO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_ESGOTO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_DEBITO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_DEBITO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_CREDITO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_CREDITO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_PARCELAMENTO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_PARCELAMENTO
						.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_IMPOSTO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_IMPOSTO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_AGUA = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_AGUA.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_ESGOTO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_ESGOTO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_DEBITO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_DEBITO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_CREDITO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_CREDITO.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_PARCELAMENTO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_PARCELAMENTO
						.getId();
		EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_IMPOSTO = EventoComercialEnum.EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_IMPOSTO.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_AGUA_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_AGUA_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_ESGOTO_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_ESGOTO_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_PARCELAMENTO_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_PARCELAMENTO_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_FINANCIAMENTO_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_FINANCIAMENTO_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_AGUA_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_AGUA_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_ESGOTO_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_ESGOTO_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_PARCELAMENTO_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_PARCELAMENTO_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_FINANCIAMENTO_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_FINANCIAMENTO_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_JUROS_CORRECAO_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_JUROS_CORRECAO_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_TRANSFERENCIA_PARCELAMENTO_PREFEITURA_LONGO_PARA_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_TRANSFERENCIA_PARCELAMENTO_PREFEITURA_LONGO_PARA_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_AGUA_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_AGUA_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_ESGOTO_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_ESGOTO_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_PARCELAMENTO_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_PARCELAMENTO_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_FINANCIAMENTO_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_FINANCIAMENTO_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_AGUA_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_AGUA_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_ESGOTO_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_ESGOTO_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_PARCELAMENTO_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_PARCELAMENTO_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_FINANCIAMENTO_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_FINANCIAMENTO_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_JUROS_CORRECAO_CURTO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_JUROS_CORRECAO_CURTO_PRAZO
						.getId();
		EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_JUROS_CORRECAO_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_JUROS_CORRECAO_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_JUROS_CORRECAO_LONGO_PRAZO = EventoComercialEnum.EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_JUROS_CORRECAO_LONGO_PRAZO
						.getId();
		EVENTO_COMERCIAL_BAIXA_CONTA_DUPLICIDADE_EXCESSO = EventoComercialEnum.EVENTO_COMERCIAL_BAIXA_CONTA_DUPLICIDADE_EXCESSO.getId();
		EVENTO_COMERCIAL_BAIXA_CONTA_INEXISTENTE = EventoComercialEnum.EVENTO_COMERCIAL_BAIXA_CONTA_INEXISTENTE.getId();
		EVENTO_COMERCIAL_BAIXA_GUIA_PAGAMENTO_DUPLICIDADE_EXCESSO = EventoComercialEnum.EVENTO_COMERCIAL_BAIXA_GUIA_PAGAMENTO_DUPLICIDADE_EXCESSO
						.getId();
		EVENTO_COMERCIAL_BAIXA_GUIA_PAGAMENTO_INEXISTENTE = EventoComercialEnum.EVENTO_COMERCIAL_BAIXA_GUIA_PAGAMENTO_INEXISTENTE.getId();
		EVENTO_COMERCIAL_BAIXA_DEBITO_A_COBRAR_DUPLICIDADE_EXCESSO = EventoComercialEnum.EVENTO_COMERCIAL_BAIXA_DEBITO_A_COBRAR_DUPLICIDADE_EXCESSO
						.getId();
		EVENTO_COMERCIAL_BAIXA_DEBITO_A_COBRAR_INEXISTENTE = EventoComercialEnum.EVENTO_COMERCIAL_BAIXA_DEBITO_A_COBRAR_INEXISTENTE.getId();
		EVENTO_COMERCIAL_PDD_FAIXA1_PUBLICO_ESTADUAL = EventoComercialEnum.EVENTO_COMERCIAL_PDD_FAIXA1_PUBLICO_ESTADUAL.getId();
		EVENTO_COMERCIAL_PDD_FAIXA2_PUBLICO_ESTADUAL = EventoComercialEnum.EVENTO_COMERCIAL_PDD_FAIXA2_PUBLICO_ESTADUAL.getId();
		EVENTO_COMERCIAL_PDD_FAIXA3_PUBLICO_ESTADUAL = EventoComercialEnum.EVENTO_COMERCIAL_PDD_FAIXA3_PUBLICO_ESTADUAL.getId();
		EVENTO_COMERCIAL_PDD_FAIXA1_BAIXA = EventoComercialEnum.EVENTO_COMERCIAL_PDD_FAIXA1_BAIXA.getId();
		EVENTO_COMERCIAL_PDD_FAIXA2_BAIXA = EventoComercialEnum.EVENTO_COMERCIAL_PDD_FAIXA2_BAIXA.getId();
		EVENTO_COMERCIAL_PDD_FAIXA3_BAIXA = EventoComercialEnum.EVENTO_COMERCIAL_PDD_FAIXA3_BAIXA.getId();
	}

	/**
	 * Enumeração criado para dar suporte ao carregamento de constantes da classe em tempo de
	 * execução.Caso a constante não seja utilizada por um determinado cliente será atribuído -1 ao
	 * seu valor.
	 * 
	 * @author Hugo Lima
	 * @date 26/06/2012
	 */
	public static enum EventoComercialEnum {
		EVENTO_COMERCIAL_INCLUIR_CONTA_AGUA, EVENTO_COMERCIAL_INCLUIR_CONTA_ESGOTO, EVENTO_COMERCIAL_INCLUIR_CONTA_DEBITO,
		EVENTO_COMERCIAL_INCLUIR_CONTA_CREDITO, EVENTO_COMERCIAL_INCLUIR_CONTA_PARCELAMENTO, EVENTO_COMERCIAL_INCLUIR_CONTA_IMPOSTO,
		EVENTO_COMERCIAL_CANCELAR_CONTA_AGUA, EVENTO_COMERCIAL_CANCELAR_CONTA_ESGOTO, EVENTO_COMERCIAL_CANCELAR_CONTA_DEBITO,
		EVENTO_COMERCIAL_CANCELAR_CONTA_CREDITO, EVENTO_COMERCIAL_CANCELAR_CONTA_PARCELAMENTO, EVENTO_COMERCIAL_CANCELAR_CONTA_IMPOSTO,
		EVENTO_COMERCIAL_INCLUIR_DEBITO_A_COBRAR_CURTO_PRAZO, EVENTO_COMERCIAL_INCLUIR_DEBITO_A_COBRAR_LONGO_PRAZO,
		EVENTO_COMERCIAL_CANCELAR_DEBITO_A_COBRAR_CURTO_PRAZO, EVENTO_COMERCIAL_CANCELAR_DEBITO_A_COBRAR_LONGO_PRAZO,
		EVENTO_COMERCIAL_TRANSFERENCIA_DEBITO_LONGO_PARA_CURTO_PRAZO, EVENTO_COMERCIAL_INCLUIR_CREDITO_A_REALIZAR_CURTO_PRAZO,
		EVENTO_COMERCIAL_INCLUIR_CREDITO_A_REALIZAR_LONGO_PRAZO, EVENTO_COMERCIAL_CANCELAR_CREDITO_A_REALIZAR_CURTO_PRAZO,
		EVENTO_COMERCIAL_CANCELAR_CREDITO_A_REALIZAR_LONGO_PRAZO, EVENTO_COMERCIAL_TRANSFERENCIA_CREDITO_LONGO_PARA_CURTO_PRAZO,
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_AGUA, EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_ESGOTO, EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_DEBITO,
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_CREDITO, EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_PARCELAMENTO,
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_IMPOSTO, EVENTO_COMERCIAL_INCLUIR_GUIA_PAGAMENTO, EVENTO_COMERCIAL_CANCELAR_GUIA_PAGAMENTO,
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_AGUA, EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_ESGOTO,
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_DEBITO, EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_CREDITO,
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_PARCELAMENTO, EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_IMPOSTO,
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_NAO_IDENTIFICADO, EVENTO_COMERCIAL_PARCELAMENTO_AGUA_CURTO_PRAZO,
		EVENTO_COMERCIAL_PARCELAMENTO_ESGOTO_CURTO_PRAZO, EVENTO_COMERCIAL_PARCELAMENTO_PARCELAMENTO_CURTO_PRAZO,
		EVENTO_COMERCIAL_PARCELAMENTO_FINANCIAMENTO_CURTO_PRAZO, EVENTO_COMERCIAL_PARCELAMENTO_AGUA_LONGO_PRAZO,
		EVENTO_COMERCIAL_PARCELAMENTO_ESGOTO_LONGO_PRAZO, EVENTO_COMERCIAL_PARCELAMENTO_PARCELAMENTO_LONGO_PRAZO,
		EVENTO_COMERCIAL_PARCELAMENTO_FINANCIAMENTO_LONGO_PRAZO, EVENTO_COMERCIAL_PARCELAMENTO_JUROS_CORRECAO_CURTO_PRAZO,
		EVENTO_COMERCIAL_TRANSFERENCIA_PARCELAMENTO_LONGO_PARA_CURTO_PRAZO, EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_AGUA_CURTO_PRAZO,
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_ESGOTO_CURTO_PRAZO, EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PARCELAMENTO_CURTO_PRAZO,
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_FINANCIAMENTO_CURTO_PRAZO, EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_AGUA_LONGO_PRAZO,
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_ESGOTO_LONGO_PRAZO, EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PARCELAMENTO_LONGO_PRAZO,
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_FINANCIAMENTO_LONGO_PRAZO,
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_JUROS_CORRECAO_CURTO_PRAZO, EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_GUIA_PAGAMENTO,
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_DEBITO_A_COBRAR, EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_GUIA_PAGAMENTO,
		EVENTO_COMERCIAL_INCLUIR_PAGAMENTO_POSTERIOR_DEBITO_A_COBRAR, EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_AGUA,
		EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_ESGOTO, EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_DEBITO,
		EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_CREDITO, EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_PARCELAMENTO,
		EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_IMPOSTO, EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_GUIA_PAGAMENTO,
		EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_DEBITO_A_COBRAR, EVENTO_COMERCIAL_ESTORNAR_PAGAMENTO_NAO_IDENTIFICADO,
		EVENTO_COMERCIAL_CANCELAR_PARCELAMENTO_SALDO_CURTO_PRAZO, EVENTO_COMERCIAL_CANCELAR_PARCELAMENTO_SALDO_LONGO_PRAZO,
		EVENTO_COMERCIAL_PARCELAMENTO_JUROS_CORRECAO_LONGO_PRAZO, EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_JUROS_CORRECAO_LONGO_PRAZO,
		EVENTO_COMERCIAL_PDD_FAIXA1, EVENTO_COMERCIAL_PDD_FAIXA2, EVENTO_COMERCIAL_PDD_FAIXA3, EVENTO_COMERCIAL_PDD_FAIXA1_MISTO,
		EVENTO_COMERCIAL_PDD_FAIXA2_MISTO, EVENTO_COMERCIAL_PDD_FAIXA3_MISTO, EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_AGUA,
		EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_ESGOTO, EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_DEBITO,
		EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_CREDITO, EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_PARCELAMENTO,
		EVENTO_COMERCIAL_INCLUIR_CONTA_BATCH_IMPOSTO, EVENTO_COMERCIAL_CANCELAR_CONTA_APT_AGUA, EVENTO_COMERCIAL_CANCELAR_CONTA_APT_ESGOTO,
		EVENTO_COMERCIAL_CANCELAR_CONTA_APT_DEBITO, EVENTO_COMERCIAL_CANCELAR_CONTA_APT_CREDITO,
		EVENTO_COMERCIAL_CANCELAR_CONTA_APT_PARCELAMENTO, EVENTO_COMERCIAL_CANCELAR_CONTA_APT_IMPOSTO,
		EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_AGUA, EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_ESGOTO,
		EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_DEBITO, EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_CREDITO,
		EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_PARCELAMENTO, EVENTO_COMERCIAL_CANCELAR_CONTA_PREFEITURA_IMPOSTO,
		EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_AGUA, EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_ESGOTO,
		EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_DEBITO, EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_CREDITO,
		EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_PARCELAMENTO, EVENTO_COMERCIAL_CANCELAR_CONTA_PRESCRICAO_IMPOSTO,
		EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_AGUA_CURTO_PRAZO, EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_ESGOTO_CURTO_PRAZO,
		EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_PARCELAMENTO_CURTO_PRAZO,
		EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_FINANCIAMENTO_CURTO_PRAZO, EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_AGUA_LONGO_PRAZO,
		EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_ESGOTO_LONGO_PRAZO, EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_PARCELAMENTO_LONGO_PRAZO,
		EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_FINANCIAMENTO_LONGO_PRAZO,
		EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_JUROS_CORRECAO_CURTO_PRAZO,
		EVENTO_COMERCIAL_TRANSFERENCIA_PARCELAMENTO_PREFEITURA_LONGO_PARA_CURTO_PRAZO,
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_AGUA_CURTO_PRAZO,
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_ESGOTO_CURTO_PRAZO,
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_PARCELAMENTO_CURTO_PRAZO,
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_FINANCIAMENTO_CURTO_PRAZO,
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_AGUA_LONGO_PRAZO,
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_ESGOTO_LONGO_PRAZO,
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_PARCELAMENTO_LONGO_PRAZO,
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_FINANCIAMENTO_LONGO_PRAZO,
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_JUROS_CORRECAO_CURTO_PRAZO,
		EVENTO_COMERCIAL_PARCELAMENTO_PREFEITURA_JUROS_CORRECAO_LONGO_PRAZO,
		EVENTO_COMERCIAL_DESFAZER_PARCELAMENTO_PREFEITURA_JUROS_CORRECAO_LONGO_PRAZO, EVENTO_COMERCIAL_BAIXA_CONTA_DUPLICIDADE_EXCESSO,
		EVENTO_COMERCIAL_BAIXA_CONTA_INEXISTENTE, EVENTO_COMERCIAL_BAIXA_GUIA_PAGAMENTO_DUPLICIDADE_EXCESSO,
		EVENTO_COMERCIAL_BAIXA_GUIA_PAGAMENTO_INEXISTENTE, EVENTO_COMERCIAL_BAIXA_DEBITO_A_COBRAR_DUPLICIDADE_EXCESSO,
		EVENTO_COMERCIAL_BAIXA_DEBITO_A_COBRAR_INEXISTENTE, EVENTO_COMERCIAL_PDD_FAIXA1_PUBLICO_ESTADUAL,
		EVENTO_COMERCIAL_PDD_FAIXA2_PUBLICO_ESTADUAL, EVENTO_COMERCIAL_PDD_FAIXA3_PUBLICO_ESTADUAL, EVENTO_COMERCIAL_PDD_FAIXA1_BAIXA,
		EVENTO_COMERCIAL_PDD_FAIXA2_BAIXA, EVENTO_COMERCIAL_PDD_FAIXA3_BAIXA;

		private Integer id = -1;

		private EventoComercialEnum() {

			try{
				EventoComercial eventoComercial = RepositorioUtilHBM.getInstancia().pesquisarPorCodigo(name(), EventoComercial.class);

				if(eventoComercial != null){
					id = eventoComercial.getId();
				}
			}catch(ErroRepositorioException e){
				e.printStackTrace();
				throw new SistemaException(e, e.getMessage());
			}
		}

		public Integer getId(){

			return id;
		}
	}

}
