
package gcom.micromedicao.consumo;

// Generated 18/03/2009 15:46:52 by Hibernate Tools 3.2.1.GA

import gcom.util.tabelaauxiliar.abreviada.TabelaAuxiliarAbreviada;

import java.sql.Timestamp;

/**
 * ConsumoFixoUnidade generated by hbm2java
 */
public class ConsumoFixoUnidade
				extends TabelaAuxiliarAbreviada
				implements java.io.Serializable {

	/*
	 * private Integer id;
	 * private String descricao;
	 * private String descricaoAbreviada;
	 * private Short indicadorUso;
	 * private Timestamp ultimaAlteracao;
	 */
	public static final Integer UNIDADE_TIPO_AREA_CONSTRUIDA = Integer.valueOf(1);

	public static final Integer UNIDADE_TIPO_PISCINA = Integer.valueOf(2);

	public static final Integer UNIDADE_TIPO_MORADORES = Integer.valueOf(3);

	public static final Integer UNIDADE_TIPO_AREA_EXTERNA = Integer.valueOf(4);

	public static final Integer UNIDADE_TIPO_QUARTOS = Integer.valueOf(5);

	public static final Integer UNIDADE_TIPO_CONSUMO = Integer.valueOf(6);

	public static final Integer UNIDADE_TIPO_PONTOS_CONSUMO = Integer.valueOf(7);

	public static final Integer UNIDADE_TIPO_CONSUMO_HORA_MES = Integer.valueOf(8);

	public ConsumoFixoUnidade() {

	}

	public ConsumoFixoUnidade(Integer id, Timestamp ultimaAlteracao) {

		this.id = id;
		this.ultimaAlteracao = ultimaAlteracao;
	}

	@Override
	public String[] retornaCamposChavePrimaria(){

		// TODO Auto-generated method stub
		return null;
	}

	/*
	 * public ConsumoFixoUnidade(Integer id, String descricao, String descricaoAbreviada, Short
	 * indicadorUso, Timestamp ultimaAlteracao) {
	 * this.id = id;
	 * this.descricao = descricao;
	 * this.descricaoAbreviada = descricaoAbreviada;
	 * this.indicadorUso = indicadorUso;
	 * this.ultimaAlteracao = ultimaAlteracao;
	 * }
	 * public Integer getId(){
	 * return this.id;
	 * }
	 * public void setId(Integer id){
	 * this.id = id;
	 * }
	 * public String getDescricao(){
	 * return this.descricao;
	 * }
	 * public void setDescricao(String descricao){
	 * this.descricao = descricao;
	 * }
	 * public String getDescricaoAbreviada(){
	 * return this.descricaoAbreviada;
	 * }
	 * public void setDescricaoAbreviada(String descricaoAbreviada){
	 * this.descricaoAbreviada = descricaoAbreviada;
	 * }
	 * public Short getIndicadorUso(){
	 * return this.indicadorUso;
	 * }
	 * public void setIndicadorUso(Short indicadorUso){
	 * this.indicadorUso = indicadorUso;
	 * }
	 * public Timestamp getUltimaAlteracao(){
	 * return this.ultimaAlteracao;
	 * }
	 * public void setUltimaAlteracao(Timestamp ultimaAlteracao){
	 * this.ultimaAlteracao = ultimaAlteracao;
	 * }
	 */

}
