
package gcom.micromedicao.consumo;

// Generated 18/03/2009 15:46:52 by Hibernate Tools 3.2.1.GA

import java.sql.Timestamp;

/**
 * ConsumoFixoFaixa generated by hbm2java
 */
public class ConsumoFixoFaixa
				implements java.io.Serializable {

	private Integer id;

	private Integer numeroInicialFaixa;

	private Integer numeroFinalFaixa;

	private Integer volumeConsumoFixoFaixa;

	private Short indicadorUso;

	private Timestamp ultimaAlteracao;

	private ConsumoFixoUnidade consumoFixoUnidade;

	public ConsumoFixoFaixa() {

	}

	public ConsumoFixoFaixa(Integer numeroInicialFaixa, Integer numeroFinalFaixa, Integer volumeConsumoFixoFaixa, Timestamp ultimaAlteracao) {

		this.numeroInicialFaixa = numeroInicialFaixa;
		this.numeroFinalFaixa = numeroFinalFaixa;
		this.volumeConsumoFixoFaixa = volumeConsumoFixoFaixa;
		this.ultimaAlteracao = ultimaAlteracao;
	}

	public ConsumoFixoFaixa(Integer numeroInicialFaixa, Integer numeroFinalFaixa, Integer volumeConsumoFixoFaixa, Short indicadorUso,
							Timestamp ultimaAlteracao, ConsumoFixoUnidade consumoFixoUnidade) {

		this.numeroInicialFaixa = numeroInicialFaixa;
		this.numeroFinalFaixa = numeroFinalFaixa;
		this.volumeConsumoFixoFaixa = volumeConsumoFixoFaixa;
		this.indicadorUso = indicadorUso;
		this.ultimaAlteracao = ultimaAlteracao;
		this.consumoFixoUnidade = consumoFixoUnidade;
	}

	public Integer getId(){

		return this.id;
	}

	public void setId(Integer id){

		this.id = id;
	}

	public Integer getNumeroInicialFaixa(){

		return this.numeroInicialFaixa;
	}

	public void setNumeroInicialFaixa(Integer numeroInicialFaixa){

		this.numeroInicialFaixa = numeroInicialFaixa;
	}

	public Integer getNumeroFinalFaixa(){

		return this.numeroFinalFaixa;
	}

	public void setNumeroFinalFaixa(Integer numeroFinalFaixa){

		this.numeroFinalFaixa = numeroFinalFaixa;
	}

	public Integer getVolumeConsumoFixoFaixa(){

		return this.volumeConsumoFixoFaixa;
	}

	public void setVolumeConsumoFixoFaixa(Integer volumeConsumoFixoFaixa){

		this.volumeConsumoFixoFaixa = volumeConsumoFixoFaixa;
	}

	public Short getIndicadorUso(){

		return this.indicadorUso;
	}

	public void setIndicadorUso(Short indicadorUso){

		this.indicadorUso = indicadorUso;
	}

	public Timestamp getUltimaAlteracao(){

		return this.ultimaAlteracao;
	}

	public void setUltimaAlteracao(Timestamp ultimaAlteracao){

		this.ultimaAlteracao = ultimaAlteracao;
	}

	public ConsumoFixoUnidade getConsumoFixoUnidade(){

		return this.consumoFixoUnidade;
	}

	public void setConsumoFixoUnidade(ConsumoFixoUnidade consumoFixoUnidade){

		this.consumoFixoUnidade = consumoFixoUnidade;
	}

}
