  CREATE TABLE "GSAN_ADMIN"."PRE_PARCELAMENTO_OPCAO"
   (           "PPOP_ID" NUMBER(*,0) NOT NULL ENABLE,
                "PREP_ID" NUMBER(*,0) NOT NULL ENABLE,
                "PPOP_NNPOSICAO" NUMBER(*,0) NOT NULL ENABLE,
                "PPOP_VLENTRADA" NUMBER(13,2),
                "PPOP_VLJUROSPARCELAMENTO" NUMBER(13,2),
        "PPOP_NNPRESTACOES" NUMBER(*,0),
        "PPOP_VLPRESTACAO" NUMBER(13,2),
                "PPOP_PCDESCONTOACRESCIMOS" NUMBER(13,2),
                "PPOP_PCDESCONTOANTIGUIDADE" NUMBER(13,2),
        "PPOP_PCDESCONTOINATIVIDADE" NUMBER(13,2),
        "PPOP_VLATUALIZACAOMONETARIA" NUMBER(13,2),
        "PPOP_VLJUROSMORA" NUMBER(13,2),
        "PPOP_VLMULTA" NUMBER(13,2),
        "PPOP_VLDEBITOATUALIZADO" NUMBER(13,2),
        "PPOP_VLDESCONTOACRESCIMOS" NUMBER(13,2),
        "PPOP_VLDESCONTOANTIGUIDADE" NUMBER(13,2),
        "PPOP_VLDESCONTOINATIVIDADE" NUMBER(13,2),
        "PPOP_VLDESCONTOSANCAO" NUMBER(13,2),
        "PPOP_VLDESCONTOTARSOC" NUMBER(13,2),
        "PCPF_ID"                        NUMBER,
                "PPOP_TMULTIMAALTERACAO" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
                 CONSTRAINT "PRE_PARCELAMENTO_OPCAO" PRIMARY KEY ("PPOP_ID"),
                         CONSTRAINT "FK1_PRE_PARCELAMENTO" FOREIGN KEY ("PREP_ID")
                         REFERENCES "GSAN_ADMIN"."PRE_PARCELAMENTO" ("PREP_ID") ENABLE,
                         CONSTRAINT "FK9_PREPARCELAMENTOOPCAO" FOREIGN KEY ("PCPF_ID") REFERENCES "GSAN_ADMIN"."PARCELAMENTO_PERFIL" ("PCPF_ID") ENABLE);
                         

CREATE SEQUENCE GSAN_ADMIN.SQ_PRE_PARCELAMENTO_OPCAO MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
GRANT ALL PRIVILEGES ON GSAN_ADMIN.PRE_PARCELAMENTO_OPCAO to GSAN_OPER;
GRANT ALL PRIVILEGES ON GSAN_ADMIN.SQ_PRE_PARCELAMENTO_OPCAO to GSAN_OPER;
CREATE OR REPLACE PUBLIC SYNONYM SQ_PRE_PARCELAMENTO_OPCAO FOR GSAN_ADMIN.SQ_PRE_PARCELAMENTO_OPCAO;
CREATE OR REPLACE PUBLIC SYNONYM PRE_PARCELAMENTO_OPCAO FOR GSAN_ADMIN.PRE_PARCELAMENTO_OPCAO;
COMMIT;