-- Anderson Italo
delete from GRUPO_FUNCIONALIDADE_OPERACAO where FNCD_ID=524;
delete from GRUPO_FUNCIONALIDADE_OPERACAO where FNCD_ID = 434;
delete from GRUPO_FUNCIONALIDADE_OPERACAO where FNCD_ID = 795;
