CREATE TABLE CLIENTE_RESPONSAVEL (
  CLRS_ID NUMBER PRIMARY KEY NOT NULL,
  CLIE_ID NUMBER NOT NULL,
  CLRS_ICMULTA NUMBER(1),
  CLRS_ICJUROS NUMBER(1),
  CLRS_ICCORRECAO NUMBER(1),
  CLRS_ICIMPOSTOFEDERAL NUMBER(1),
  AGEN_ID NUMBER,
  CLRS_NNCONTABANCARIA VARCHAR(12),
  CLRS_ICUSO NUMBER(1),
  CLRS_DTULTIMAALTERACAO TIMESTAMP
);

--Ailton Sousa - Cliente_Responsavel
COMMENT ON COLUMN "GSAN_ADMIN"."CLIENTE_RESPONSAVEL"."CLRS_ID"
 IS 'ID DA RELACAO CLIENTE/RESPONSAVEL';
COMMENT ON COLUMN "GSAN_ADMIN"."CLIENTE_RESPONSAVEL"."CLIE_ID"
 IS 'CODIGO DO CLIENTE';
COMMENT ON COLUMN "GSAN_ADMIN"."CLIENTE_RESPONSAVEL"."CLRS_ICMULTA"
 IS 'INDICADOR DE COBRANCA DE MULTA.
 1 - SIM
 2 - NAO';
COMMENT ON COLUMN "GSAN_ADMIN"."CLIENTE_RESPONSAVEL"."CLRS_ICJUROS"
 IS 'INDICADOR DE COBRANCA DE JUROS.
 1 - SIM
 2 - NAO';
COMMENT ON COLUMN "GSAN_ADMIN"."CLIENTE_RESPONSAVEL"."CLRS_ICCORRECAO"
 IS 'INDICADOR DE COBRANCA DE CORRECAO.
 1 - SIM
 2 - NAO';
COMMENT ON COLUMN "GSAN_ADMIN"."CLIENTE_RESPONSAVEL"."CLRS_ICIMPOSTOFEDERAL"
 IS 'INDICADOR DE IMPOSTO FEDERAL DESTACADO.
 1 - SIM
 2 - NAO';
COMMENT ON COLUMN "GSAN_ADMIN"."CLIENTE_RESPONSAVEL"."AGEN_ID"
 IS 'ID DA AGENCIA BANCARIA DO RESPONSAVEL';
COMMENT ON COLUMN "GSAN_ADMIN"."CLIENTE_RESPONSAVEL"."CLRS_NNCONTABANCARIA"
 IS 'NUMERO DA CONTA BANCARIA DO RESPONSAVEL';
COMMENT ON COLUMN "GSAN_ADMIN"."CLIENTE_RESPONSAVEL"."CLRS_ICUSO"
 IS 'INDICADOR DE USO.
1 - ATIVO (DEFAULT)
2 - INATIVO';
COMMENT ON COLUMN "GSAN_ADMIN"."CLIENTE_RESPONSAVEL"."CLRS_DTULTIMAALTERACAO"
 IS 'DATA/HORA DA ULTIMA ALTERACAO';