CREATE TABLE "GSAN_ADMIN"."CONSUMO_FAIXA_AREA_CATEG"
  (
    "CFAC_ID"                 NUMBER NOT NULL ENABLE,
    "CATG_ID"                 NUMBER NOT NULL ENABLE,
    "CFAC_FAIXA_INICIAL_AREA" NUMBER(5,0) NOT NULL ENABLE,
    "CFAC_FAIXA_FINAL_AREA"   NUMBER(5,0) NOT NULL ENABLE,
    "CFAC_CONSUMO"            NUMBER(6,0) NOT NULL ENABLE,
    "CFAC_ICUSO"              NUMBER(1,0) NOT NULL ENABLE,
    "CFAC_TMULTIMAALTERACAO" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("CFAC_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "GSANCONDATA01" ENABLE,
    CONSTRAINT "FK1_CONSUMO_FAIXA_AREA_CATEG" FOREIGN KEY ("CATG_ID") REFERENCES "GSAN_ADMIN"."CATEGORIA" ("CATG_ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "GSANCONDATA01" ;
COMMENT ON COLUMN "GSAN_ADMIN"."CONSUMO_FAIXA_AREA_CATEG"."CFAC_ID"
IS
  'ID DA FAIXA DE CONSUMO – AREA/CATEGORIA';
  COMMENT ON COLUMN "GSAN_ADMIN"."CONSUMO_FAIXA_AREA_CATEG"."CATG_ID"
IS
  'ID DA CATEGORIA (TABELA CATEGORIA)';
  COMMENT ON COLUMN "GSAN_ADMIN"."CONSUMO_FAIXA_AREA_CATEG"."CFAC_FAIXA_INICIAL_AREA"
IS
  'FAIXA INICIAL DA AREA';
  COMMENT ON COLUMN "GSAN_ADMIN"."CONSUMO_FAIXA_AREA_CATEG"."CFAC_FAIXA_FINAL_AREA"
IS
  'FAIXA FINAL DA AREA';
  COMMENT ON COLUMN "GSAN_ADMIN"."CONSUMO_FAIXA_AREA_CATEG"."CFAC_CONSUMO"
IS
  'Consumo Faixa Area Categoria';
  COMMENT ON COLUMN "GSAN_ADMIN"."CONSUMO_FAIXA_AREA_CATEG"."CFAC_ICUSO"
IS
  'INDICADOR DE USO. 1 - ATIVO (DEFAULT) 2 - INATIVO';
  COMMENT ON COLUMN "GSAN_ADMIN"."CONSUMO_FAIXA_AREA_CATEG"."CFAC_TMULTIMAALTERACAO"
IS
  'DATA/HORA DA ULTIMA ALTERACAO';


grant all privileges on gsan_admin.CONSUMO_FAIXA_AREA_CATEG to gsan_oper;
CREATE OR REPLACE PUBLIC SYNONYM CONSUMO_FAIXA_AREA_CATEG FOR GSAN_ADMIN.CONSUMO_FAIXA_AREA_CATEG;