--PÉRICLES TAVARES
--DISTRITO_OPER_UNID_TIPO

CREATE TABLE GSAN_ADMIN.DISTRITO_OPERACIONAL_DADO 
(DIOD_ID NUMBER(4, 0) NOT NULL, 
  DIOP_ID NUMBER(*, 0) NOT NULL,
  DIOD_AMREFERENCIA NUMBER(6, 0) NOT NULL,
  DIOD_NNUNIDADE NUMBER(15, 4) NOT NULL,
  DIOD_NNADUCAO NUMBER(15, 4) NOT NULL,
  DIOD_NNVOLUME NUMBER(15, 4) NOT NULL,
  DIOD_NNEXTENSAO NUMBER(9, 4) NOT NULL,
  DIOD_NNDIAMETRO NUMBER(6, 4) NOT NULL,
  MRDA_ID NUMBER(*,0) NOT NULL,
  DIOD_NNDEMANDAENERGIA NUMBER(15,4) NOT NULL,
  DIOD_QTSULFATOALUMINIO NUMBER(15,4) NOT NULL,
  DIOD_QTCLOROGASOSO NUMBER(15,4) NOT NULL,
  DIOD_QTHIPOCLORITOSODIO NUMBER(15,4) NOT NULL,
  DIOD_QTFLUOR NUMBER(15,4) NOT NULL,
  DIOD_QTHORASPARALISADAS NUMBER(5,2) NOT NULL,
  USUR_ID NUMBER(*,0) NOT NULL,
  DIOD_TMULTIMAALTERACAO TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL, 
  CONSTRAINT DISTRITO_OPER_DADO_PKEY PRIMARY KEY (DIOD_ID) ENABLE,

  CONSTRAINT FK1_DISTRITO_OPER_DADO FOREIGN KEY (MRDA_ID) 
  REFERENCES GSAN_ADMIN.MATERIAL_REDE_AGUA (MRDA_ID) ENABLE,

  CONSTRAINT FK2_DISTRITO_OPER_DADO FOREIGN KEY (USUR_ID) 
  REFERENCES GSAN_ADMIN.USUARIO (USUR_ID) ENABLE);
 
COMMENT ON COLUMN DISTRITO_OPERACIONAL_DADO.DIOP_ID IS 'IDENTIFICADOR DO TIPO DE UNIDADE OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPERACIONAL_DADO.DIOD_AMREFERENCIA IS 'ANO MES DE REFERENCIA DO DADO DO DISTRITO OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPERACIONAL_DADO.DIOD_NNUNIDADE IS 'UNIDADE DA CAPACIDADE DO DADO DO DISTRITO OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPERACIONAL_DADO.DIOD_NNADUCAO IS 'ADUCAO DA CAPACIDADE DO DADO DO DISTRITO OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPERACIONAL_DADO.DIOD_NNVOLUME IS 'VOLUME DA CAPACIDADE DO DADO DO DISTRITO OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPERACIONAL_DADO.DIOD_NNEXTENSAO IS 'EXTENSAO DA ADUTORA DO DADO DO DISTRITO OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPERACIONAL_DADO.DIOD_NNDIAMETRO IS 'DIAMETRO DA ADUTORA DO DADO DO DISTRITO OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPERACIONAL_DADO.MRMA_ID IS 'MATERIAL DA ADUTORA DO DADO DO DISTRITO OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPERACIONAL_DADO.DIOD_NNDEMANDAENERGIA IS 'DEMANDA DE ENERGIA DO DADO DO DISTRITO OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPERACIONAL_DADO.DIOD_QTSULFATOALUMINIO IS 'QTIDADE DE SULTATO DE ALUMINIO DO DADO DO DISTRITO OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPERACIONAL_DADO.DIOD_QTCLOROGASOSO IS 'QTIDADE DE CLORO GASOSO DO DADO DO DISTRITO OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPERACIONAL_DADO.DIOD_QTHIPOCLORITOSODIO IS 'QTIDADE DE HIPOCLORITO DE SODIO DO DADO DO DISTRITO OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPERACIONAL_DADO.DIOD_QTFLUOR IS 'QTIDADE DE FLUOR DO DADO DO DISTRITO OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPERACIONAL_DADO.DIOD_QTHORASPARALISADAS IS 'HORAS PARALISADAS DO DADO DO DISTRITO OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPERACIONAL_DADO.USUR_ID IS 'ID DO USUARIO DO DADO DO DISTRITO OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPERACIONAL_DADO.DIOD_TMULTIMAALTERACAO IS 'DATA HORA ALTERACAO';
