--PÉRICLES TAVARES
--DISTRITO_OPER_UNID_TIPO

CREATE TABLE GSAN_ADMIN.DISTRITO_OPER_UNID_TIPO 
(DOUT_ID NUMBER(4, 0) NOT NULL, 
 DOUT_DSUNIDADEOPERACIONAL VARCHAR2(30 BYTE) NOT NULL, 
 DOUT_DSABREVIADO CHAR(10) NOT NULL, 
 DOUT_TMULTIMAALTERACAO TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL, 
 DOUT_ICUSO NUMBER(4,0) DEFAULT 1 NOT NULL, 
 CONSTRAINT DISTRITO_OPER_UNID_TIPO_PKEY PRIMARY KEY (DOUT_ID) ENABLE);
 
COMMENT ON COLUMN DISTRITO_OPER_UNID_TIPO.DOUT_ID IS 'IDENTIFICADOR DO TIPO DE UNIDADE OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPER_UNID_TIPO.DOUT_DSUNIDADEOPERACIONAL IS 'DESCRICAO DO TIPO DE UNIDADE OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPER_UNID_TIPO.DOUT_DSABREVIADO IS 'DESCRICA ABREVIADA DO TIPO DE UNIDADE OPERACIONAL';
COMMENT ON COLUMN DISTRITO_OPER_UNID_TIPO.DOUT_ICUSO IS 'INDICADOR DE USO';
COMMENT ON COLUMN DISTRITO_OPER_UNID_TIPO.DOUT_TMULTIMAALTERACAO IS 'DATA DA ULTIMA ALTERAÇÃO';
