--PÉRICLES TAVARES
--ESGOTO_TRATAMENTO_TIPO

CREATE TABLE GSAN_ADMIN.ESGOTO_TRATAMENTO_TIPO  
(ESTT_ID NUMBER(4, 0) NOT NULL, 
 ESTT_DSTRATAMENTOTIPO VARCHAR2(30 BYTE) NOT NULL, 
 ESTT_DSABREVIADO CHAR(10) NOT NULL, 
 ESTT_TMULTIMAALTERACAO TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL, 
 ESTT_ICUSO NUMBER(4,0) DEFAULT 1 NOT NULL, 
 CONSTRAINT ESGOTO_TRATAMENTO_TIPO_PKEY PRIMARY KEY (ESTT_ID) ENABLE);
 
COMMENT ON COLUMN ESGOTO_TRATAMENTO_TIPO.ESTT_ID IS 'IDENTIFICADOR DO ESGOTO TRATAMENTO TIPO';
COMMENT ON COLUMN ESGOTO_TRATAMENTO_TIPO.ESTT_DSTRATAMENTOTIPO IS 'DESCRICAO DO ESGOTO TRATAMENTO TIPO';
COMMENT ON COLUMN ESGOTO_TRATAMENTO_TIPO.ESTT_DSABREVIADO IS 'DESCRICA ABREVIADA DO ESGOTO TRATAMENTO TIPO';
COMMENT ON COLUMN ESGOTO_TRATAMENTO_TIPO.ESTT_ICUSO IS 'INDICADOR DE USO';
COMMENT ON COLUMN ESGOTO_TRATAMENTO_TIPO.ESTT_TMULTIMAALTERACAO IS 'DATA DA ULTIMA ALTERAÇÃO';
