CREATE TABLE "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"
  (
    "ESTR_ID"                     NUMBER(*,0) NOT NULL ENABLE,
    "STEP_ID"                     NUMBER(*,0) NOT NULL ENABLE,
    "LOCA_ID"                     NUMBER(*,0) ,
    "STCM_ID"       			  NUMBER(*,0) ,
    "BAIR_ID"               	  NUMBER(*,0) ,
    "SABS_ID"                     NUMBER(*,0) ,
    "DIOP_ID"                     NUMBER(*,0) ,
    "ZABS_ID"                     NUMBER(*,0) ,
    "STAB_ID"                     NUMBER(*,0) ,
    "SESG_ID"                     NUMBER(*,0) ,
    "SSES_ID"                     NUMBER(*,0) ,
    "BACI_ID"                     NUMBER(*,0) ,
    "SBAC_ID"                     NUMBER(*,0) ,
    "UNID_IDORIGEM"               NUMBER(*,0) ,
    "UNID_IDDESTINO"              NUMBER(*,0) ,
    "ESTR_ICUSO"                  NUMBER(*,0) NOT NULL ENABLE,
    "ESTR_TMULTIMAALTERACAO"      TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,

CONSTRAINT "ESPECIFICACAO_TRAMITE"      PRIMARY KEY ("ESTR_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "GSANCONINDEX01" ENABLE,
CONSTRAINT "FK1_ESPECIFICACAO_TRAMITE"  FOREIGN KEY ("STEP_ID")                                             REFERENCES "GSAN_ADMIN"."SOLICITACAO_TIPO_ESPECIFICACAO" ("STEP_ID") ENABLE,
CONSTRAINT "FK2_ESPECIFICACAO_TRAMITE"  FOREIGN KEY ("LOCA_ID")                                             REFERENCES "GSAN_ADMIN"."LOCALIDADE"                     ("LOCA_ID") ENABLE,
CONSTRAINT "FK3_ESPECIFICACAO_TRAMITE"  FOREIGN KEY ("SABS_ID")                                             REFERENCES "GSAN_ADMIN"."SISTEMA_ABASTECIMENTO"          ("SABS_ID") ENABLE,
CONSTRAINT "FK4_ESPECIFICACAO_TRAMITE"  FOREIGN KEY ("DIOP_ID")                                             REFERENCES "GSAN_ADMIN"."DISTRITO_OPERACIONAL"           ("DIOP_ID") ENABLE,
CONSTRAINT "FK5_ESPECIFICACAO_TRAMITE"  FOREIGN KEY ("ZABS_ID")                                             REFERENCES "GSAN_ADMIN"."ZONA_ABASTECIMENTO"             ("ZABS_ID") ENABLE,
CONSTRAINT "FK6_ESPECIFICACAO_TRAMITE"  FOREIGN KEY ("STAB_ID")                                             REFERENCES "GSAN_ADMIN"."SETOR_ABASTECIMENTO"            ("STAB_ID") ENABLE,
CONSTRAINT "FK7_ESPECIFICACAO_TRAMITE"  FOREIGN KEY ("SESG_ID")                                             REFERENCES "GSAN_ADMIN"."SISTEMA_ESGOTO"                 ("SESG_ID") ENABLE,
CONSTRAINT "FK8_ESPECIFICACAO_TRAMITE"  FOREIGN KEY ("SSES_ID")                                             REFERENCES "GSAN_ADMIN"."SUBSISTEMA_ESGOTO"              ("SSES_ID") ENABLE,
CONSTRAINT "FK9_ESPECIFICACAO_TRAMITE"  FOREIGN KEY ("BACI_ID")                                             REFERENCES "GSAN_ADMIN"."BACIA"                          ("BACI_ID") ENABLE,
CONSTRAINT "FK10_ESPECIFICACAO_TRAMITE" FOREIGN KEY ("SBAC_ID")                                             REFERENCES "GSAN_ADMIN"."SUBBACIA"                       ("SBAC_ID") ENABLE,
CONSTRAINT "FK11_ESPECIFICACAO_TRAMITE" FOREIGN KEY ("UNID_IDORIGEM")                                       REFERENCES "GSAN_ADMIN"."UNIDADE_ORGANIZACIONAL"  		 ("UNID_ID") ENABLE,
CONSTRAINT "FK12_ESPECIFICACAO_TRAMITE" FOREIGN KEY ("UNID_IDDESTINO")                                      REFERENCES "GSAN_ADMIN"."UNIDADE_ORGANIZACIONAL"  		 ("UNID_ID") ENABLE,
CONSTRAINT "FK13_ESPECIFICACAO_TRAMITE" FOREIGN KEY ("STCM_ID")                                      	  	REFERENCES "GSAN_ADMIN"."SETOR_COMERCIAL"  		 		 ("STCM_ID") ENABLE,
CONSTRAINT "FK14_ESPECIFICACAO_TRAMITE" FOREIGN KEY ("BAIR_ID")                                      		REFERENCES "GSAN_ADMIN"."BAIRRO"  		 				 ("BAIR_ID") ENABLE );

CREATE UNIQUE INDEX GSAN_ADMIN.XAK1_ESPECIFICACAO_TRAMITE ON GSAN_ADMIN.ESPECIFICACAO_TRAMITE (STEP_ID,LOCA_ID,STCM_ID,BAIR_ID,SABS_ID,DIOP_ID,ZABS_ID,STAB_ID, SESG_ID,SSES_ID,BACI_ID,SBAC_ID,UNID_IDORIGEM,UNID_IDDESTINO);
  
GRANT ALL PRIVILEGES ON GSAN_ADMIN.ESPECIFICACAO_TRAMITE to gsan_oper;
CREATE OR REPLACE PUBLIC SYNONYM    ESPECIFICACAO_TRAMITE FOR GSAN_ADMIN.ESPECIFICACAO_TRAMITE;

-- Comentários da Tabela
COMMENT ON COLUMN "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"."ESTR_ID"
IS
  'ID DO TRAMITE POR ESPECIFICACAO';
COMMENT ON COLUMN "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"."STEP_ID"
IS
  'ID DO SOLICITACAO TIPO ESPECIFICACAO';
COMMENT ON COLUMN "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"."LOCA_ID"
IS
  'ID DA LOCALIDADE';
COMMENT ON COLUMN "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"."STCM_ID"
IS
  'ID DO SETOR COMERCIAL';
COMMENT ON COLUMN "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"."BAIR_ID"
IS
  'ID DO BAIRRO';
COMMENT ON COLUMN "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"."SABS_ID"
IS
  'ID DO SISTEMA DE ABASTECIMENTO';
COMMENT ON COLUMN "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"."DIOP_ID"
IS
  'ID DO DISTRITO OPERACIONAL';
COMMENT ON COLUMN "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"."ZABS_ID"
IS
  'ID DA ZONA DE ABASTECIMENTO';
COMMENT ON COLUMN "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"."STAB_ID"
IS
  'ID DO SETOR DO ABASTECIMENTO';
COMMENT ON COLUMN "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"."SESG_ID"
IS
  'ID DO SISTEMA DE ESGOTO';
COMMENT ON COLUMN "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"."SSES_ID"
IS
  'ID DO SUB-SISTEMA DE ESGOTO';
COMMENT ON COLUMN "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"."BACI_ID"
IS
  'ID DA BACIA';
COMMENT ON COLUMN "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"."SBAC_ID"
IS
  'ID DA SUB-BACIA';
COMMENT ON COLUMN "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"."UNID_IDORIGEM"
IS
  'ID DA UNIDADE ORGANIZACIONAL DE ORIGEM';  
COMMENT ON COLUMN "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"."UNID_IDDESTINO"
IS
  'ID DA UNIDADE ORGANIZACIONAL DE DESTINO';
COMMENT ON COLUMN "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"."ESTR_ICUSO"
IS
  'INDICADOR DE USO.
1 - ATIVO (DEFAULT)
2 - INATIVO';
COMMENT ON COLUMN "GSAN_ADMIN"."ESPECIFICACAO_TRAMITE"."ESTR_TMULTIMAALTERACAO"
IS
  'DATA/HORA DA ULTIMA ALTERACAO';