CREATE TABLE FATURAMENTO_HIST_APT
(
 FHAT_ID NUMBER NOT NULL,
 IMOV_ID NUMBER,
 FHAT_TMHABILITACAOPROGRAMA TIMESTAMP,
 FHAT_ANO_MES_REFERENCIA NUMBER(6,0),
 FHAT_CDTARIFA NUMBER,
 FHAT_NNCONSUMOMES NUMBER(15,2),
 FHAT_VLCONSUMO NUMBER(15,2)
 );
 
COMMENT ON COLUMN FATURAMENTO_HIST_APT.FHAT_ID IS 'CODIGO DO IMOVEL';
COMMENT ON COLUMN FATURAMENTO_HIST_APT.FHAT_TMHABILITACAOPROGRAMA IS 'DATA DE HABILITAÇÃO DO PROGRAMA';
COMMENT ON COLUMN FATURAMENTO_HIST_APT.FHAT_ANO_MES_REFERENCIA IS 'ANO E ME DE REFERENCIA';
COMMENT ON COLUMN FATURAMENTO_HIST_APT.FHAT_CDTARIFA IS 'CODIGO DA TARIFA';
COMMENT ON COLUMN FATURAMENTO_HIST_APT.FHAT_NNCONSUMOMES IS 'NUMERO DE CONSUMO';
COMMENT ON COLUMN FATURAMENTO_HIST_APT.FHAT_VLCONSUMO IS 'VALOR DO CONSUMO';