CREATE TABLE IMOVEL_AGUA_PARA_TODOS
(
 IAPT_ID NUMBER NOT NULL, 
 IAPT_NNIDENTIFCONTRIBUINTE NUMBER(15,0) NOT NULL,
 IAPT_NMPARTICIPANTE VARCHAR(50),
 IAPT_USUARIO_ID_INCL NUMBER,
 IAPT_USUARIO_ID_EXCL NUMBER,
 IAPT_TMCADASTRAMENTOPROG TIMESTAMP,
 IAPT_TMHABILITACAOPROGRAMA TIMESTAMP,
 IAPT_TMEXCLUSAOPROGRAMA TIMESTAMP,
 IAPT_TMULTIMAALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 IAPT_ANO_MES_REFERENCIA_INI NUMBER(6,0),
 IAPT_ANO_MES_REFERENCIA_FIM NUMBER(6,0),
 IAPT_CDSITUACAO NUMBER(1),
 IAPT_CDMOTIVOEXCLUSAO NUMBER(1)
 );
 
 COMMENT ON COLUMN IMOVEL_AGUA_PARA_TODOS.IAPT_ID IS 'CODIGO DO IMOVEL';
 COMMENT ON COLUMN IMOVEL_AGUA_PARA_TODOS.IAPT_NNIDENTIFCONTRIBUINTE IS 'CODIGO DO CONTRIBUINTE';
 COMMENT ON COLUMN IMOVEL_AGUA_PARA_TODOS.IAPT_NMPARTICIPANTE IS 'NOME DO CONTRIBUINTE';
 COMMENT ON COLUMN IMOVEL_AGUA_PARA_TODOS.IAPT_USUARIO_ID_INCL IS 'USUARIO DE INCLUIU';
 COMMENT ON COLUMN IMOVEL_AGUA_PARA_TODOS.IAPT_USUARIO_ID_EXCL IS 'USUARIO DE EXCLUIU';
 COMMENT ON COLUMN IMOVEL_AGUA_PARA_TODOS.IAPT_TMCADASTRAMENTOPROG IS 'DATA DE CADASTRAMENTO NO PROGRAMA';
 COMMENT ON COLUMN IMOVEL_AGUA_PARA_TODOS.IAPT_TMHABILITACAOPROGRAMA IS 'DATA DE HABILITAÇÃO DO PROGRAMA';
 COMMENT ON COLUMN IMOVEL_AGUA_PARA_TODOS.IAPT_TMEXCLUSAOPROGRAMA IS 'DATA DE EXCLUSAO DO PROGRAMA';
 COMMENT ON COLUMN IMOVEL_AGUA_PARA_TODOS.IAPT_TMULTIMAALTERACAO IS 'DATA DA ULTIMA ALTERAÇÃO';
 COMMENT ON COLUMN IMOVEL_AGUA_PARA_TODOS.IAPT_ANO_MES_REFERENCIA_INI IS 'ANO E MES DE REFERENCIA INICIAL';
 COMMENT ON COLUMN IMOVEL_AGUA_PARA_TODOS.IAPT_ANO_MES_REFERENCIA_FIM IS 'ANO E MES DE REFERENCIA FINAL';
 COMMENT ON COLUMN IMOVEL_AGUA_PARA_TODOS.IAPT_CDSITUACAO IS 'CODIGO DA SITUAÇÃO';
 COMMENT ON COLUMN IMOVEL_AGUA_PARA_TODOS.IAPT_CDMOTIVOEXCLUSAO IS 'MOTIVO DA EXCLUSÃO';