CREATE TABLE GSAN_ADMIN.IMOVEL_CONSUMO_FAIXA_AREA_CAT
  (
    "CFAC_ID"       NUMBER NOT NULL ENABLE,
    "IMOV_ID"       NUMBER NOT NULL ENABLE,
    "CATG_ID"       NUMBER NOT NULL ENABLE,
    "ICFC_CFRENTE"  NUMBER(4,0) NOT NULL ENABLE,
    "ICFC_CLADO"    NUMBER(4,0) NOT NULL ENABLE,
    "ICFC_CTESTADA" NUMBER(4,0),
    "ICFC_NANDAR"   NUMBER(4,0),
    "ICFC_CANDAR"   NUMBER(4,0),
    "ICFC_AREA"     NUMBER(6,0) NOT NULL ENABLE,
    "ICFC_ICUSO"    NUMBER(1,0) NOT NULL ENABLE,
    "ICFC_TMULTIMAALTERACAO" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "IM_CONSUMO_FX_AREA_CAT_PKEY" PRIMARY KEY ("CFAC_ID", "IMOV_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "GSANCONDATA01" ENABLE,
    CONSTRAINT "FK1_IM_CONSUMO_FAIX_AREA_CAT" FOREIGN KEY ("CFAC_ID") REFERENCES "GSAN_ADMIN"."CONSUMO_FAIXA_AREA_CATEG" ("CFAC_ID") ENABLE,
    CONSTRAINT "FK2_IM_CONSUMO_FAIX_AREA_CAT" FOREIGN KEY ("IMOV_ID") REFERENCES "GSAN_ADMIN"."IMOVEL" ("IMOV_ID") ENABLE,
    CONSTRAINT "FK3_IM_CONSUMO_FAIX_AREA_CAT" FOREIGN KEY ("CATG_ID") REFERENCES "GSAN_ADMIN"."CATEGORIA" ("CATG_ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "GSANCONDATA01" ;
COMMENT ON COLUMN "GSAN_ADMIN"."IMOVEL_CONSUMO_FAIXA_AREA_CAT"."CFAC_ID"
IS
  'CODIGO DA FAIXA DE CONSUMO POR AREA E CATEGORIA';
  COMMENT ON COLUMN "GSAN_ADMIN"."IMOVEL_CONSUMO_FAIXA_AREA_CAT"."IMOV_ID"
IS
  'ID DA TABELA IMOVEL (MATRICULA DO IMOVEL)';
  COMMENT ON COLUMN "GSAN_ADMIN"."IMOVEL_CONSUMO_FAIXA_AREA_CAT"."CATG_ID"
IS
  'CODIGO DA CATEGORIA';
  COMMENT ON COLUMN "GSAN_ADMIN"."IMOVEL_CONSUMO_FAIXA_AREA_CAT"."ICFC_CFRENTE"
IS
  'COMPRIMENTO DA FRENTE';
  COMMENT ON COLUMN "GSAN_ADMIN"."IMOVEL_CONSUMO_FAIXA_AREA_CAT"."ICFC_CLADO"
IS
  'COMPRIMENTO  DO LADO';
  COMMENT ON COLUMN "GSAN_ADMIN"."IMOVEL_CONSUMO_FAIXA_AREA_CAT"."ICFC_CTESTADA"
IS
  'COMPRIMENTO DA TESTADA';
  COMMENT ON COLUMN "GSAN_ADMIN"."IMOVEL_CONSUMO_FAIXA_AREA_CAT"."ICFC_NANDAR"
IS
  'NUMERO DE ANDARES';
  COMMENT ON COLUMN "GSAN_ADMIN"."IMOVEL_CONSUMO_FAIXA_AREA_CAT"."ICFC_CANDAR"
IS
  'COMPRIMENTO DO ANDAR';
  COMMENT ON COLUMN "GSAN_ADMIN"."IMOVEL_CONSUMO_FAIXA_AREA_CAT"."ICFC_AREA"
IS
  'AREA CONSTRUIDA';
  COMMENT ON COLUMN "GSAN_ADMIN"."IMOVEL_CONSUMO_FAIXA_AREA_CAT"."ICFC_ICUSO"
IS
  'INDICADOR DE USO';
  COMMENT ON COLUMN "GSAN_ADMIN"."IMOVEL_CONSUMO_FAIXA_AREA_CAT"."ICFC_TMULTIMAALTERACAO"
IS
  'DATA DA ULTIMA ALTERACAO';

 
GRANT ALL PRIVILEGES ON GSAN_ADMIN.IMOVEL_CONSUMO_FAIXA_AREA_CAT TO GSAN_OPER;
CREATE OR REPLACE PUBLIC SYNONYM IMOVEL_CONSUMO_FAIXA_AREA_CAT FOR GSAN_ADMIN.IMOVEL_CONSUMO_FAIXA_AREA_CAT;

