-- IMOVEL_ESGOTO_JUDICIAL
-- Isaac Silva
CREATE TABLE "GSAN_ADMIN"."IMOVEL_ESGOTO_JUDICIAL"
(IMEJ_ID NUMBER PRIMARY KEY NOT NULL,
IMOV_ID NUMBER NOT NULL,
IMEJ_CDSITESGINC NUMBER(1,0) NOT NULL,
IMEJ_AMREFPROXFATINC NUMBER(6,0),
IMEJ_TMINC TIMESTAMP(6),
IMEJ_CDSITESGEXC NUMBER(1,0),
IMEJ_AMREFPROXFATEXC NUMBER(6,0),
IMEJ_TMEXC TIMESTAMP(6),
IMEJ_ICUSO NUMBER(1,0) NOT NULL,
IMEJ_TMULTIMAALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

ALTER TABLE "GSAN_ADMIN"."IMOVEL_ESGOTO_JUDICIAL"
ADD CONSTRAINT FK1_LIGACAO_ESGOTO_SITUA FOREIGN KEY (IMOV_ID)
REFERENCES "GSAN_ADMIN"."IMOVEL" (IMOV_ID) ENABLE;

ALTER TABLE "GSAN_ADMIN"."IMOVEL_ESGOTO_JUDICIAL"
ADD CONSTRAINT FK2_LIGACAO_ESGOTO_SITUA FOREIGN KEY (IMEJ_CDSITESGINC)
REFERENCES "GSAN_ADMIN"."LIGACAO_ESGOTO_SITUACAO" (LEST_ID) ENABLE;

ALTER TABLE "GSAN_ADMIN"."IMOVEL_ESGOTO_JUDICIAL"
ADD CONSTRAINT FK3_LIGACAO_ESGOTO_SITUA FOREIGN KEY (IMEJ_CDSITESGEXC)
REFERENCES "GSAN_ADMIN"."LIGACAO_ESGOTO_SITUACAO" (LEST_ID) ENABLE;

grant all privileges on gsan_admin.imovel_esgoto_judicial to gsan_oper;
CREATE OR REPLACE PUBLIC SYNONYM IMOVEL_ESGOTO_JUDICIAL FOR GSAN_ADMIN.IMOVEL_ESGOTO_JUDICIAL;