-- LOCALIDADE_DADO_OPERACIONAL
-- Isaac Silva
CREATE TABLE "GSAN_ADMIN"."LOCALIDADE_DADO_OPERACIONAL"
(LDOP_ID NUMBER PRIMARY KEY NOT NULL,
LDOP_AMREFERENCIA NUMBER,
LOCA_ID NUMBER NOT NULL,
LDOP_VOLUMEPRODUZIDO NUMBER(9,0),
LDOP_EXTENSAOREDEAGUA NUMBER(9,0),
LDOP_EXTENSAOREDEESGOTO NUMBER(9,0),
LDOP_QTFUNCADM NUMBER(6,0),
LDOP_QTFUNCADMTERCEIRO NUMBER(6,0),
LDOP_QTFUNCOPR NUMBER(6,0),
LDOP_QTFUNCOPRTERCEIRO NUMBER(6,0),
LDOP_QTSULFATOALUMINIO NUMBER(9,0),
LDOP_QTCLOROGASOSO NUMBER(9,0),
LDOP_QTHIPOCLORSODIO NUMBER(9,0),
LDOP_QTFLUOR NUMBER(9,0),
LDOP_QTCONSUMOENEERGIA NUMBER(9,0),
LDOP_QTHORASPARALIZADAS NUMBER(9,0),
LDOP_ICUSO NUMBER(1,0) NOT NULL,
LDOP_TMULTIMAALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

ALTER TABLE "GSAN_ADMIN"."LOCALIDADE_DADO_OPERACIONAL"
ADD CONSTRAINT FK1_LOCALIDADE_DADO_OPER FOREIGN KEY (LOCA_ID)
REFERENCES "GSAN_ADMIN"."LOCALIDADE" (LOCA_ID) ENABLE;

grant all privileges on gsan_admin.localidade_dado_operacional to gsan_oper;
CREATE OR REPLACE PUBLIC SYNONYM LOCALIDADE_DADO_OPERACIONAL FOR GSAN_ADMIN.LOCALIDADE_DADO_OPERACIONAL;