-- SETOR_ABASTECIMENTO
-- PÉRICLES TAVARES

CREATE TABLE "GSAN_ADMIN"."SETOR_ABASTECIMENTO"  (
  STAB_ID NUMBER PRIMARY KEY NOT NULL,
  STAB_CDSETORABASTECIMENTO NUMBER(2) NOT NULL,
  STAB_DSSETORABASTECIMENTO VARCHAR(30) NOT NULL, 
  STAB_DSABREVSETORABASTECIMENTO VARCHAR(6) NULL, 
  ZABS_ID NUMBER NOT NULL,
  SABS_ID NUMBER NOT NULL,
  UNOP_ID NUMBER NOT NULL,
  STAB_TMULTIMAALTERACAO TIMESTAMP,
  STAB_ICUSO NUMBER(1)
 );

COMMENT ON COLUMN SETOR_ABASTECIMENTO.STAB_ID IS 'ID DA TABELA SETOR_ABASTECIMENTO.';
COMMENT ON COLUMN SETOR_ABASTECIMENTO.STAB_CDSETORABASTECIMENTO IS 'CODIGO DA SETOR DE ABASTECIMENTO';
COMMENT ON COLUMN SETOR_ABASTECIMENTO.STAB_DSSETORABASTECIMENTO IS 'DESCRICAO DA UNIDADE OPERACIONAL';
COMMENT ON COLUMN SETOR_ABASTECIMENTO.STAB_DSABREVSETORABASTECIMENTO IS 'DESCRICAO ABREVIADA DO SETOR DE ABASTECIMENTO';
COMMENT ON COLUMN SETOR_ABASTECIMENTO.ZABS_ID IS 'ID DA ZONA DE ABASTECIMENTO';
COMMENT ON COLUMN SETOR_ABASTECIMENTO.SABS_ID IS 'ID DO SISTEMA DE ABASTECIMENTO';
COMMENT ON COLUMN SETOR_ABASTECIMENTO.UNOP_ID IS 'ID DO UNIDADE OPERACIONAL';
COMMENT ON COLUMN SETOR_ABASTECIMENTO.STAB_TMULTIMAALTERACAO IS	'DATA DA ULTIMA ALTERACAO';
COMMENT ON COLUMN SETOR_ABASTECIMENTO.STAB_ICUSO IS 'INDICADOR DE ATIVO  1 – ATIVO   2 – INATIVO';


