-- SETOR_COMERCIAL_VENCIMENTO
-- Isaac Silva
CREATE TABLE "GSAN_ADMIN"."SETOR_COMERCIAL_VENCIMENTO"
(STCV_ID NUMBER PRIMARY KEY NOT NULL, 
 LOCA_ID NUMBER NOT NULL,
 STCM_ID NUMBER NOT NULL,
 STCV_DIAVENCIMENTO NUMBER(2,0) NOT NULL,
 STCV_ICUSO NUMBER(1,0) NOT NULL,
 STCV_TMULTIMAALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

ALTER TABLE "GSAN_ADMIN"."SETOR_COMERCIAL_VENCIMENTO"
ADD CONSTRAINT FK1_SETOR_COMERCIAL_VENCIMENTO FOREIGN KEY (LOCA_ID)
REFERENCES "GSAN_ADMIN"."LOCALIDADE" (LOCA_ID) ENABLE;

ALTER TABLE "GSAN_ADMIN"."SETOR_COMERCIAL_VENCIMENTO"
ADD CONSTRAINT FK2_SETOR_COMERCIAL_VENCIMENTO FOREIGN KEY (STCM_ID)
REFERENCES "GSAN_ADMIN"."SETOR_COMERCIAL" (STCM_ID) ENABLE;

grant all privileges on gsan_admin.setor_comercial_vencimento to gsan_oper;
CREATE OR REPLACE PUBLIC SYNONYM SETOR_COMERCIAL_VENCIMENTO FOR GSAN_ADMIN.SETOR_COMERCIAL_VENCIMENTO;