CREATE TABLE "GSAN_ADMIN"."SOLICITACAO_TIPO_ESPECIF_MENS" (
  STEM_ID NUMBER PRIMARY KEY NOT NULL,
  STEM_DSMENSAGEM VARCHAR(200) NOT NULL,
  STEM_DSABREV VARCHAR(50),
  STEM_ICUSO NUMBER(1),
  STEM_TMULTIMAALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

grant all privileges on gsan_admin.solicitacao_tipo_especif_mens to gsan_oper;
CREATE OR REPLACE PUBLIC SYNONYM SOLICITACAO_TIPO_ESPECIF_MENS FOR GSAN_ADMIN.SOLICITACAO_TIPO_ESPECIF_MENS;

-- Comentários da Tabela
COMMENT ON COLUMN "GSAN_ADMIN"."SOLICITACAO_TIPO_ESPECIF_MENS"."STEM_ID"
IS
  'ID DO SUBSISTEMA DE ESGOTO';
COMMENT ON COLUMN "GSAN_ADMIN"."SOLICITACAO_TIPO_ESPECIF_MENS"."STEM_DSMENSAGEM"
IS
  'DESCRICAO DO SUBSISTEMA DE ESGOTO';
COMMENT ON COLUMN "GSAN_ADMIN"."SOLICITACAO_TIPO_ESPECIF_MENS"."STEM_DSABREV"
IS
  'DESCRICAO ABREVIADA DO SUBSISTEMA DE ESGOTO';
COMMENT ON COLUMN "GSAN_ADMIN"."SOLICITACAO_TIPO_ESPECIF_MENS"."STEM_ICUSO"
IS
  'INDICADOR DE USO.
1 - ATIVO (DEFAULT)
2 - INATIVO';
COMMENT ON COLUMN "GSAN_ADMIN"."SOLICITACAO_TIPO_ESPECIF_MENS"."STEM_TMULTIMAALTERACAO"
IS
  'DATA/HORA DA ULTIMA ALTERACAO';