CREATE TABLE SUBBACIA (
  SBAC_ID NUMBER PRIMARY KEY NOT NULL,
  SBAC_CDSUBBACIA NUMBER NOT NULL,
  SBAC_DSSUBBACIA VARCHAR(30) NOT NULL,
  SBAC_DSABREVSUBBACIA VARCHAR(6),
  BACI_ID NUMBER,
  SBAC_ICUSO NUMBER(1),
  SBAC_TMULTIMAALTERACAO TIMESTAMP DEFAULT SYSDATE
);

COMMENT ON COLUMN SUBBACIA.SBAC_ID IS 'IDENTIFICADOR DA SUBBACIA';
COMMENT ON COLUMN SUBBACIA.SBAC_CDSUBBACIA IS 'CODIGO DA SUBBACIA';
COMMENT ON COLUMN SUBBACIA.SBAC_DSSUBBACIA IS 'DESCRICAO DA SUBBACIA';
COMMENT ON COLUMN SUBBACIA.SBAC_DSABREVSUBBACIA IS 'DESCRICA ABREVIADA DA SUBBACIA';
COMMENT ON COLUMN SUBBACIA.BACI_ID IS 'IDENTIFICADOR DA BACIA ASSOCIADA A SUBBACIA';
COMMENT ON COLUMN SUBBACIA.SBAC_ICUSO IS 'INDICADOR DE USO';
COMMENT ON COLUMN SUBBACIA.SBAC_TMULTIMAALTERACAO IS 'DATA DA ULTIMA ALTERAÇÃO';