CREATE TABLE TRAMITE_MOTIVO
(
TRMT_ID                  NUMBER PRIMARY KEY NOT NULL,
TRMT_DSTRAMITEMOTIVO     VARCHAR(30),
TRMT_DSABREVIADO         VARCHAR(8),
TRMT_ICUSO               NUMBER DEFAULT 1,
TRMT_TMULTIMAALTERACAO   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON COLUMN TRAMITE_MOTIVO.TRMT_ID IS 'IDENTIFICA플O DO MOTIVO DO TRAMITE';
COMMENT ON COLUMN TRAMITE_MOTIVO.TRMT_DSTRAMITEMOTIVO IS 'DESCRI플O DO MOTIVO';
COMMENT ON COLUMN TRAMITE_MOTIVO.TRMT_DSABREVIADO IS 'DESCRI플O ABREVIADA DO MOTIVO';
COMMENT ON COLUMN TRAMITE_MOTIVO.TRMT_ICUSO IS 'INDICADOR DE USO';
COMMENT ON COLUMN TRAMITE_MOTIVO.TRMT_TMULTIMAALTERACAO IS 'DATA DE ULTIMA ALTERA플O';
