-- UNIDADE_OPERACIONAL
-- PÉRICLES TAVARES

CREATE TABLE "GSAN_ADMIN"."UNIDADE_OPERACIONAL"  (
  UNOP_ID NUMBER PRIMARY KEY NOT NULL,
  UNOP_CDUNIDADEOPRACIONAL NUMBER(3) NOT NULL,
  UNOP_DSUNIDADEOPERACIONAL VARCHAR(30) NOT NULL, 
  UNOP_DSABREVUNIDADEOPERACIONAL VARCHAR(6) NULL, 
  SABS_ID NUMBER NOT NULL,
  LOCA_ID NUMBER NOT NULL,
  UNOP_NNIMOVEL NUMBER NULL,
  UNOP_DSCOMPLEMENTOENDERECO VARCHAR(30) NULL,
  UNOP_NNFONE NUMBER(9) NULL,
  UNOP_NNFONERAMAL NUMBER(4) NULL,
  UNOP_NNFAX NUMBER(9) NULL,
  UNOP_DSEMAIL VARCHAR(40) NULL, 
  LOGR_ID NUMBER,
  BAIR_ID NUMBER,
  EDRF_ID NUMBER,
  CEP_ID NUMBER,
  UNOP_DSTIPOINSTALACAO VARCHAR(30) NULL,
  UNOP_NNCOTA NUMBER(9) NULL,
  UNOP_NNLATITUDE NUMBER(9) NULL,
  UNOP_NNLONGITUDE NUMBER(9) NULL,
  UNOP_TMULTIMAATERACAO TIMESTAMP,
  UNOP_ICUSO NUMBER(1)
 );

COMMENT ON COLUMN UNIDADE_OPERACIONAL.UNOP_ID IS 'ID DA TABELA UNIDADE_OPERACIONAL.';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.UNOP_CDUNIDADEOPRACIONAL IS 'CODIGO DA UNIDADE OPERACIONAL';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.UNOP_DSUNIDADEOPERACIONAL IS 'DESCRICAO DA UNIDADE OPERACIONAL';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.UNOP_DSABREVUNIDADEOPERACIONAL IS 'DESCRICAO ABREVIADA DA UNIDADE OPERACIONAL';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.SABS_ID IS 'CODIGO DO SISTEMA DE ABASTECIMENTO';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.LOCA_ID IS 'ID DA TABELA LOCALIDADE';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.UNOP_NNIMOVEL IS 'NUMERO DO IMOVEL';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.UNOP_NNFONE IS	'NUMERO DO TELEFONE';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.UNOP_NNFONERAMAL IS 'NUMERO DO RAMAL TELEFONICO';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.UNOP_NNFAX IS 'NUMERO FO FAX';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.UNOP_DSEMAIL IS 'EMAIL DA UNIDADE OPERACIONAL';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.LOGR_ID IS 'ID  DO LOGRADORO';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.BAIR_ID IS 'ID DA TABELA DE BAIRRO';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.CEP_ID IS 'ID DA TABELA CEP';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.UNOP_DSTIPOINSTALACAO IS 'DESCRICAO DO TIPO DE INSTALACAO';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.UNOP_NNCOTA IS 'NUMERO DA COTA';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.UNOP_NNLATITUDE IS 'LATITUDE';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.UNOP_NNLONGITUDE IS 'LONGITUDE';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.UNOP_TMULTIMAATERACAO IS	'DATA DA ULTIMA ALTERACAO';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.UNOP_ICUSO IS 'INDICADOR DE ATIVO  1 – ATIVO   2 – INATIVO';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.UNOP_DSCOMPLEMENTOENDERECO IS 'COMPLEMENTO DO ENDERECO';
COMMENT ON COLUMN UNIDADE_OPERACIONAL.EDRF_ID IS 'ID DA TABELA DE REFERENCIAS DE ENDERECOS';

