CREATE TABLE ZONA_ABASTECIMENTO (
  ZABS_ID NUMBER PRIMARY KEY NOT NULL,
  ZABS_CDZONAABASTECIMENTO NUMBER NOT NULL,
  ZABS_DSZONAABASTECIMENTO VARCHAR(30) NOT NULL,
  ZABS_DSABREVIADO VARCHAR(6),
  UNOP_ID NUMBER,
  ZABS_ICUSO NUMBER(1),
  ZABS_TMULTIMAALTERACAO TIMESTAMP DEFAULT SYSDATE,
  SABS_ID NUMBER,
  DIOP_ID NUMBER(*, 0) NOT NULL,
  LOCA_ID NUMBER(*, 0) NOT NULL,
  ZABS_NNFAIXAPRESSAOINF NUMBER(10,4) NOT NULL,
  ZABS_NNFAIXAPRESSAOSUP NUMBER(10,4) NOT NULL
);

ALTER TABLE GSAN_ADMIN.ZONA_ABASTECIMENTO 
ADD CONSTRAINT FK5_ZONA_ABASTECIMENTO FOREIGN KEY (DIOP_ID) 
REFERENCES GSAN_ADMIN.DISTRITO_OPERACIONAL (DIOP_ID) ENABLE;

ALTER TABLE GSAN_ADMIN.ZONA_ABASTECIMENTO 
ADD CONSTRAINT FK3_ZONA_ABASTECIMENTO FOREIGN KEY (LOCA_ID) 
REFERENCES GSAN_ADMIN.LOCALIDADE (LOCA_ID) ENABLE;

COMMENT ON COLUMN ZONA_ABASTECIMENTO.ZABS_ID IS 'IDENTIFICADOR DA ZONA DE ABASTECIMENTO';
COMMENT ON COLUMN ZONA_ABASTECIMENTO.ZABS_CDZONAABASTECIMENTO IS 'CODIGO DA ZONA DE ABASTECIMENTO';
COMMENT ON COLUMN ZONA_ABASTECIMENTO.ZABS_DSZONAABASTECIMENTO IS 'DESCRICAO DA ZONA DE ABASTECIMENTO';
COMMENT ON COLUMN ZONA_ABASTECIMENTO.ZABS_DSABREVZONAABASTECIMENTO IS 'DESCRICA ABREVIADA DA ZONA DE ABASTECIMENTO';
COMMENT ON COLUMN ZONA_ABASTECIMENTO.UNOP_ID IS 'IDENTIFICADOR DA UNIDADE OPERACIONAL ASSOCIADA A ZONA DE ABASTECIMENTO';
COMMENT ON COLUMN ZONA_ABASTECIMENTO.ZABS_ICUSO IS 'INDICADOR DE USO';
COMMENT ON COLUMN ZONA_ABASTECIMENTO.ZABS_TMULTIMAALTERACAO IS 'DATA DA ULTIMA ALTERAÇÃO';
COMMENT ON COLUMN ZONA_ABASTECIMENTO.SABS IS 'IDENTIFICADOR DA SISTEMA DE ABASTECIMENTO ASSOCIADA A ZONA DE ABASTECIMENTO';
COMMENT ON COLUMN ZONA_ABASTECIMENTO.DIOP_ID IS 'IDENTIFICADOR DO DISTRITO OPERACIONAL (TABELA DISTRITO_OPERACIONAL)';
COMMENT ON COLUMN ZONA_ABASTECIMENTO.LOCA_ID IS 'IDENTIFICADOR DA LOCALIDADE (TABELA LOCALIDADE)';
COMMENT ON COLUMN ZONA_ABASTECIMENTO.ZABS_NNFAIXAPRESSAOINF IS 'FAIXA PRESSAO INFERIOR DA ZONA DE ABASTECIMENTO';
COMMENT ON COLUMN ZONA_ABASTECIMENTO.ZABS_NNFAIXAPRESSAOSUP IS 'FAIXA PRESSAO SUPERIOR DA ZONA DE ABASTECIMENTO';