
package gcom.faturamento.conta;

// Generated 01/10/2008 18:43:11 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * MovimentoSegundaVia generated by hbm2java
 */
public class MovimentoSegundaVia
				implements java.io.Serializable {

	private Integer id;

	private Integer anoMesMovimentoReferencia;

	private String numeroInscricao;

	private Integer idImovel;

	private String nomeCliente;

	private String enderecoImovel;

	private String complementoEndereco;

	private String cep;

	private String bairro;

	private String municipio;

	private String zonaTerritorial;

	private Short quantidadeEconomiaResidencial;

	private Short quantidadeEconomiaComercial;

	private Short quantidadeEconomiaIndustrial;

	private Short quantidadeEconomiaPublica;

	private Integer idLigacaoAguaSituacao;

	private Integer idLigacaoEsgotoSituacao;

	private Short indicadorGrandeCliente;

	private String numeroHidrometro;

	private Integer idMedicaoTipo;

	private Integer numeroLeituraAnterior;

	private Date dataLeituraAnterior;

	private Integer numeroConsumoMedio;

	private Date dataVencimento;

	private Short indicadorEmissao;

	private String descricaoRubrica1;

	private String referenciaRubrica1;

	private BigDecimal valorRubrica1;

	private String descricaoRubrica2;

	private String referenciaRubrica2;

	private BigDecimal valorRubrica2;

	private String descricaoRubrica3;

	private String referenciaRubrica3;

	private BigDecimal valorRubrica3;

	private String descricaoRubrica4;

	private String referenciaRubrica4;

	private BigDecimal valorRubrica4;

	private String descricaoRubrica5;

	private String referenciaRubrica5;

	private BigDecimal valorRubrica5;

	private String descricaoRubrica6;

	private String referenciaRubrica6;

	private BigDecimal valorRubrica6;

	private String descricaoRubrica7;

	private String referenciaRubrica7;

	private BigDecimal valorRubrica7;

	private String descricaoRubrica8;

	private String referenciaRubrica8;

	private BigDecimal valorRubrica8;

	private String descricaoRubrica9;

	private String referenciaRubrica9;

	private BigDecimal valorRubrica9;

	private String descricaoRubrica10;

	private String referenciaRubrica10;

	private BigDecimal valorRubrica10;

	private String descricaoRubrica11;

	private String referenciaRubrica11;

	private BigDecimal valorRubrica11;

	private String descricaoRubrica12;

	private String referenciaRubrica12;

	private BigDecimal valorRubrica12;

	private String descricaoRubrica13;

	private String referenciaRubrica13;

	private BigDecimal valorRubrica13;

	private String descricaoRubrica14;

	private String referenciaRubrica14;

	private BigDecimal valorRubrica14;

	private String descricaoRubrica15;

	private String referenciaRubrica15;

	private BigDecimal valorRubrica15;

	private String referenciaConsumo1;

	private Integer numeroConsumo1;

	private Integer idAnormalidadeLeitura1;

	private String referenciaConsumo2;

	private Integer numeroConsumo2;

	private Integer idAnormalidadeLeitura2;

	private String referenciaConsumo3;

	private Integer numeroConsumo3;

	private Integer idAnormalidadeLeitura3;

	private String referenciaConsumo4;

	private Integer numeroConsumo4;

	private Integer idAnormalidadeLeitura4;

	private String referenciaConsumo5;

	private Integer numeroConsumo5;

	private Integer idAnormalidadeLeitura5;

	private String referenciaConsumo6;

	private Integer numeroConsumo6;

	private Integer idAnormalidadeLeitura6;

	private Date dataLeituraAtual;

	private Integer numeroLeituraAtual;

	private Integer numeroConsumoMedido;

	private Integer numeroConsumoFaturado;

	private Short numeroDiasConsumo;

	private BigDecimal valorAgua;

	private BigDecimal valorEsgoto;

	private BigDecimal valorDebitos;

	private BigDecimal valorCreditos;

	private BigDecimal valorImpostoFederal;

	private BigDecimal valorTotal;

	private Date dataEmissao;

	public MovimentoSegundaVia() {

	}

	public MovimentoSegundaVia(Integer id, Integer anoMesMovimentoReferencia, String numeroInscricao, Integer idImovel,
								Integer idLigacaoAguaSituacao, Integer idLigacaoEsgotoSituacao, BigDecimal valorAgua,
								BigDecimal valorEsgoto, BigDecimal valorDebitos, BigDecimal valorCreditos, BigDecimal valorImpostoFederal,
								BigDecimal valorTotal) {

		this.id = id;
		this.anoMesMovimentoReferencia = anoMesMovimentoReferencia;
		this.numeroInscricao = numeroInscricao;
		this.idImovel = idImovel;
		this.idLigacaoAguaSituacao = idLigacaoAguaSituacao;
		this.idLigacaoEsgotoSituacao = idLigacaoEsgotoSituacao;
		this.valorAgua = valorAgua;
		this.valorEsgoto = valorEsgoto;
		this.valorDebitos = valorDebitos;
		this.valorCreditos = valorCreditos;
		this.valorImpostoFederal = valorImpostoFederal;
		this.valorTotal = valorTotal;
	}

	public MovimentoSegundaVia(Integer id, Integer anoMesMovimentoReferencia, String numeroInscricao, Integer idImovel, String nomeCliente,
								String enderecoImovel, String complementoEndereco, String cep, String bairro, String municipio,
								String zonaTerritorial, Short quantidadeEconomiaResidencial, Short quantidadeEconomiaComercial,
								Short quantidadeEconomiaIndustrial, Short quantidadeEconomiaPublica, Integer idLigacaoAguaSituacao,
								Integer idLigacaoEsgotoSituacao, Short indicadorGrandeCliente, String numeroHidrometro,
								Integer idMedicaoTipo, Integer numeroLeituraAnterior, Date dataLeituraAnterior, Integer numeroConsumoMedio,
								Date dataVencimento, Short indicadorEmissao, String descricaoRubrica1, String referenciaRubrica1,
								BigDecimal valorRubrica1, String descricaoRubrica2, String referenciaRubrica2, BigDecimal valorRubrica2,
								String descricaoRubrica3, String referenciaRubrica3, BigDecimal valorRubrica3, String descricaoRubrica4,
								String referenciaRubrica4, BigDecimal valorRubrica4, String descricaoRubrica5, String referenciaRubrica5,
								BigDecimal valorRubrica5, String descricaoRubrica6, String referenciaRubrica6, BigDecimal valorRubrica6,
								String descricaoRubrica7, String referenciaRubrica7, BigDecimal valorRubrica7, String descricaoRubrica8,
								String referenciaRubrica8, BigDecimal valorRubrica8, String descricaoRubrica9, String referenciaRubrica9,
								BigDecimal valorRubrica9, String descricaoRubrica10, String referenciaRubrica10, BigDecimal valorRubrica10,
								String descricaoRubrica11, String referenciaRubrica11, BigDecimal valorRubrica11,
								String descricaoRubrica12, String referenciaRubrica12, BigDecimal valorRubrica12,
								String descricaoRubrica13, String referenciaRubrica13, BigDecimal valorRubrica13,
								String descricaoRubrica14, String referenciaRubrica14, BigDecimal valorRubrica14,
								String descricaoRubrica15, String referenciaRubrica15, BigDecimal valorRubrica15,
								String referenciaConsumo1, Integer numeroConsumo1, Integer idAnormalidadeLeitura1,
								String referenciaConsumo2, Integer numeroConsumo2, Integer idAnormalidadeLeitura2,
								String referenciaConsumo3, Integer numeroConsumo3, Integer idAnormalidadeLeitura3,
								String referenciaConsumo4, Integer numeroConsumo4, Integer idAnormalidadeLeitura4,
								String referenciaConsumo5, Integer numeroConsumo5, Integer idAnormalidadeLeitura5,
								String referenciaConsumo6, Integer numeroConsumo6, Integer idAnormalidadeLeitura6, Date dataLeituraAtual,
								Integer numeroLeituraAtual, Integer numeroConsumoMedido, Integer numeroConsumoFaturado,
								Short numeroDiasConsumo, BigDecimal valorAgua, BigDecimal valorEsgoto, BigDecimal valorDebitos,
								BigDecimal valorCreditos, BigDecimal valorImpostoFederal, BigDecimal valorTotal, Date dataEmissao) {

		this.id = id;
		this.anoMesMovimentoReferencia = anoMesMovimentoReferencia;
		this.numeroInscricao = numeroInscricao;
		this.idImovel = idImovel;
		this.nomeCliente = nomeCliente;
		this.enderecoImovel = enderecoImovel;
		this.complementoEndereco = complementoEndereco;
		this.cep = cep;
		this.bairro = bairro;
		this.municipio = municipio;
		this.zonaTerritorial = zonaTerritorial;
		this.quantidadeEconomiaResidencial = quantidadeEconomiaResidencial;
		this.quantidadeEconomiaComercial = quantidadeEconomiaComercial;
		this.quantidadeEconomiaIndustrial = quantidadeEconomiaIndustrial;
		this.quantidadeEconomiaPublica = quantidadeEconomiaPublica;
		this.idLigacaoAguaSituacao = idLigacaoAguaSituacao;
		this.idLigacaoEsgotoSituacao = idLigacaoEsgotoSituacao;
		this.indicadorGrandeCliente = indicadorGrandeCliente;
		this.numeroHidrometro = numeroHidrometro;
		this.idMedicaoTipo = idMedicaoTipo;
		this.numeroLeituraAnterior = numeroLeituraAnterior;
		this.dataLeituraAnterior = dataLeituraAnterior;
		this.numeroConsumoMedio = numeroConsumoMedio;
		this.dataVencimento = dataVencimento;
		this.indicadorEmissao = indicadorEmissao;
		this.descricaoRubrica1 = descricaoRubrica1;
		this.referenciaRubrica1 = referenciaRubrica1;
		this.valorRubrica1 = valorRubrica1;
		this.descricaoRubrica2 = descricaoRubrica2;
		this.referenciaRubrica2 = referenciaRubrica2;
		this.valorRubrica2 = valorRubrica2;
		this.descricaoRubrica3 = descricaoRubrica3;
		this.referenciaRubrica3 = referenciaRubrica3;
		this.valorRubrica3 = valorRubrica3;
		this.descricaoRubrica4 = descricaoRubrica4;
		this.referenciaRubrica4 = referenciaRubrica4;
		this.valorRubrica4 = valorRubrica4;
		this.descricaoRubrica5 = descricaoRubrica5;
		this.referenciaRubrica5 = referenciaRubrica5;
		this.valorRubrica5 = valorRubrica5;
		this.descricaoRubrica6 = descricaoRubrica6;
		this.referenciaRubrica6 = referenciaRubrica6;
		this.valorRubrica6 = valorRubrica6;
		this.descricaoRubrica7 = descricaoRubrica7;
		this.referenciaRubrica7 = referenciaRubrica7;
		this.valorRubrica7 = valorRubrica7;
		this.descricaoRubrica8 = descricaoRubrica8;
		this.referenciaRubrica8 = referenciaRubrica8;
		this.valorRubrica8 = valorRubrica8;
		this.descricaoRubrica9 = descricaoRubrica9;
		this.referenciaRubrica9 = referenciaRubrica9;
		this.valorRubrica9 = valorRubrica9;
		this.descricaoRubrica10 = descricaoRubrica10;
		this.referenciaRubrica10 = referenciaRubrica10;
		this.valorRubrica10 = valorRubrica10;
		this.descricaoRubrica11 = descricaoRubrica11;
		this.referenciaRubrica11 = referenciaRubrica11;
		this.valorRubrica11 = valorRubrica11;
		this.descricaoRubrica12 = descricaoRubrica12;
		this.referenciaRubrica12 = referenciaRubrica12;
		this.valorRubrica12 = valorRubrica12;
		this.descricaoRubrica13 = descricaoRubrica13;
		this.referenciaRubrica13 = referenciaRubrica13;
		this.valorRubrica13 = valorRubrica13;
		this.descricaoRubrica14 = descricaoRubrica14;
		this.referenciaRubrica14 = referenciaRubrica14;
		this.valorRubrica14 = valorRubrica14;
		this.descricaoRubrica15 = descricaoRubrica15;
		this.referenciaRubrica15 = referenciaRubrica15;
		this.valorRubrica15 = valorRubrica15;
		this.referenciaConsumo1 = referenciaConsumo1;
		this.numeroConsumo1 = numeroConsumo1;
		this.idAnormalidadeLeitura1 = idAnormalidadeLeitura1;
		this.referenciaConsumo2 = referenciaConsumo2;
		this.numeroConsumo2 = numeroConsumo2;
		this.idAnormalidadeLeitura2 = idAnormalidadeLeitura2;
		this.referenciaConsumo3 = referenciaConsumo3;
		this.numeroConsumo3 = numeroConsumo3;
		this.idAnormalidadeLeitura3 = idAnormalidadeLeitura3;
		this.referenciaConsumo4 = referenciaConsumo4;
		this.numeroConsumo4 = numeroConsumo4;
		this.idAnormalidadeLeitura4 = idAnormalidadeLeitura4;
		this.referenciaConsumo5 = referenciaConsumo5;
		this.numeroConsumo5 = numeroConsumo5;
		this.idAnormalidadeLeitura5 = idAnormalidadeLeitura5;
		this.referenciaConsumo6 = referenciaConsumo6;
		this.numeroConsumo6 = numeroConsumo6;
		this.idAnormalidadeLeitura6 = idAnormalidadeLeitura6;
		this.dataLeituraAtual = dataLeituraAtual;
		this.numeroLeituraAtual = numeroLeituraAtual;
		this.numeroConsumoMedido = numeroConsumoMedido;
		this.numeroConsumoFaturado = numeroConsumoFaturado;
		this.numeroDiasConsumo = numeroDiasConsumo;
		this.valorAgua = valorAgua;
		this.valorEsgoto = valorEsgoto;
		this.valorDebitos = valorDebitos;
		this.valorCreditos = valorCreditos;
		this.valorImpostoFederal = valorImpostoFederal;
		this.valorTotal = valorTotal;
		this.dataEmissao = dataEmissao;
	}

	public Integer getId(){

		return this.id;
	}

	public void setId(Integer id){

		this.id = id;
	}

	public Integer getAnoMesMovimentoReferencia(){

		return this.anoMesMovimentoReferencia;
	}

	public void setAnoMesMovimentoReferencia(Integer anoMesMovimentoReferencia){

		this.anoMesMovimentoReferencia = anoMesMovimentoReferencia;
	}

	public String getNumeroInscricao(){

		return this.numeroInscricao;
	}

	public void setNumeroInscricao(String numeroInscricao){

		this.numeroInscricao = numeroInscricao;
	}

	public Integer getIdImovel(){

		return this.idImovel;
	}

	public void setIdImovel(Integer idImovel){

		this.idImovel = idImovel;
	}

	public String getNomeCliente(){

		return this.nomeCliente;
	}

	public void setNomeCliente(String nomeCliente){

		this.nomeCliente = nomeCliente;
	}

	public String getEnderecoImovel(){

		return this.enderecoImovel;
	}

	public void setEnderecoImovel(String enderecoImovel){

		this.enderecoImovel = enderecoImovel;
	}

	public String getComplementoEndereco(){

		return this.complementoEndereco;
	}

	public void setComplementoEndereco(String complementoEndereco){

		this.complementoEndereco = complementoEndereco;
	}

	public String getCep(){

		return this.cep;
	}

	public void setCep(String cep){

		this.cep = cep;
	}

	public String getBairro(){

		return this.bairro;
	}

	public void setBairro(String bairro){

		this.bairro = bairro;
	}

	public String getMunicipio(){

		return this.municipio;
	}

	public void setMunicipio(String municipio){

		this.municipio = municipio;
	}

	public String getZonaTerritorial(){

		return this.zonaTerritorial;
	}

	public void setZonaTerritorial(String zonaTerritorial){

		this.zonaTerritorial = zonaTerritorial;
	}

	public Short getQuantidadeEconomiaResidencial(){

		return this.quantidadeEconomiaResidencial;
	}

	public void setQuantidadeEconomiaResidencial(Short quantidadeEconomiaResidencial){

		this.quantidadeEconomiaResidencial = quantidadeEconomiaResidencial;
	}

	public Short getQuantidadeEconomiaComercial(){

		return this.quantidadeEconomiaComercial;
	}

	public void setQuantidadeEconomiaComercial(Short quantidadeEconomiaComercial){

		this.quantidadeEconomiaComercial = quantidadeEconomiaComercial;
	}

	public Short getQuantidadeEconomiaIndustrial(){

		return this.quantidadeEconomiaIndustrial;
	}

	public void setQuantidadeEconomiaIndustrial(Short quantidadeEconomiaIndustrial){

		this.quantidadeEconomiaIndustrial = quantidadeEconomiaIndustrial;
	}

	public Short getQuantidadeEconomiaPublica(){

		return this.quantidadeEconomiaPublica;
	}

	public void setQuantidadeEconomiaPublica(Short quantidadeEconomiaPublica){

		this.quantidadeEconomiaPublica = quantidadeEconomiaPublica;
	}

	public Short getIndicadorGrandeCliente(){

		return this.indicadorGrandeCliente;
	}

	public void setIndicadorGrandeCliente(Short indicadorGrandeCliente){

		this.indicadorGrandeCliente = indicadorGrandeCliente;
	}

	public String getNumeroHidrometro(){

		return this.numeroHidrometro;
	}

	public void setNumeroHidrometro(String numeroHidrometro){

		this.numeroHidrometro = numeroHidrometro;
	}

	public Integer getIdMedicaoTipo(){

		return this.idMedicaoTipo;
	}

	public void setIdMedicaoTipo(Integer idMedicaoTipo){

		this.idMedicaoTipo = idMedicaoTipo;
	}

	public Integer getNumeroLeituraAnterior(){

		return this.numeroLeituraAnterior;
	}

	public void setNumeroLeituraAnterior(Integer numeroLeituraAnterior){

		this.numeroLeituraAnterior = numeroLeituraAnterior;
	}

	public Date getDataLeituraAnterior(){

		return this.dataLeituraAnterior;
	}

	public void setDataLeituraAnterior(Date dataLeituraAnterior){

		this.dataLeituraAnterior = dataLeituraAnterior;
	}

	public Integer getNumeroConsumoMedio(){

		return this.numeroConsumoMedio;
	}

	public void setNumeroConsumoMedio(Integer numeroConsumoMedio){

		this.numeroConsumoMedio = numeroConsumoMedio;
	}

	public Date getDataVencimento(){

		return this.dataVencimento;
	}

	public void setDataVencimento(Date dataVencimento){

		this.dataVencimento = dataVencimento;
	}

	public Short getIndicadorEmissao(){

		return this.indicadorEmissao;
	}

	public void setIndicadorEmissao(Short indicadorEmissao){

		this.indicadorEmissao = indicadorEmissao;
	}

	public String getDescricaoRubrica1(){

		return this.descricaoRubrica1;
	}

	public void setDescricaoRubrica1(String descricaoRubrica1){

		this.descricaoRubrica1 = descricaoRubrica1;
	}

	public String getReferenciaRubrica1(){

		return this.referenciaRubrica1;
	}

	public void setReferenciaRubrica1(String referenciaRubrica1){

		this.referenciaRubrica1 = referenciaRubrica1;
	}

	public BigDecimal getValorRubrica1(){

		return this.valorRubrica1;
	}

	public void setValorRubrica1(BigDecimal valorRubrica1){

		this.valorRubrica1 = valorRubrica1;
	}

	public String getDescricaoRubrica2(){

		return this.descricaoRubrica2;
	}

	public void setDescricaoRubrica2(String descricaoRubrica2){

		this.descricaoRubrica2 = descricaoRubrica2;
	}

	public String getReferenciaRubrica2(){

		return this.referenciaRubrica2;
	}

	public void setReferenciaRubrica2(String referenciaRubrica2){

		this.referenciaRubrica2 = referenciaRubrica2;
	}

	public BigDecimal getValorRubrica2(){

		return this.valorRubrica2;
	}

	public void setValorRubrica2(BigDecimal valorRubrica2){

		this.valorRubrica2 = valorRubrica2;
	}

	public String getDescricaoRubrica3(){

		return this.descricaoRubrica3;
	}

	public void setDescricaoRubrica3(String descricaoRubrica3){

		this.descricaoRubrica3 = descricaoRubrica3;
	}

	public String getReferenciaRubrica3(){

		return this.referenciaRubrica3;
	}

	public void setReferenciaRubrica3(String referenciaRubrica3){

		this.referenciaRubrica3 = referenciaRubrica3;
	}

	public BigDecimal getValorRubrica3(){

		return this.valorRubrica3;
	}

	public void setValorRubrica3(BigDecimal valorRubrica3){

		this.valorRubrica3 = valorRubrica3;
	}

	public String getDescricaoRubrica4(){

		return this.descricaoRubrica4;
	}

	public void setDescricaoRubrica4(String descricaoRubrica4){

		this.descricaoRubrica4 = descricaoRubrica4;
	}

	public String getReferenciaRubrica4(){

		return this.referenciaRubrica4;
	}

	public void setReferenciaRubrica4(String referenciaRubrica4){

		this.referenciaRubrica4 = referenciaRubrica4;
	}

	public BigDecimal getValorRubrica4(){

		return this.valorRubrica4;
	}

	public void setValorRubrica4(BigDecimal valorRubrica4){

		this.valorRubrica4 = valorRubrica4;
	}

	public String getDescricaoRubrica5(){

		return this.descricaoRubrica5;
	}

	public void setDescricaoRubrica5(String descricaoRubrica5){

		this.descricaoRubrica5 = descricaoRubrica5;
	}

	public String getReferenciaRubrica5(){

		return this.referenciaRubrica5;
	}

	public void setReferenciaRubrica5(String referenciaRubrica5){

		this.referenciaRubrica5 = referenciaRubrica5;
	}

	public BigDecimal getValorRubrica5(){

		return this.valorRubrica5;
	}

	public void setValorRubrica5(BigDecimal valorRubrica5){

		this.valorRubrica5 = valorRubrica5;
	}

	public String getDescricaoRubrica6(){

		return this.descricaoRubrica6;
	}

	public void setDescricaoRubrica6(String descricaoRubrica6){

		this.descricaoRubrica6 = descricaoRubrica6;
	}

	public String getReferenciaRubrica6(){

		return this.referenciaRubrica6;
	}

	public void setReferenciaRubrica6(String referenciaRubrica6){

		this.referenciaRubrica6 = referenciaRubrica6;
	}

	public BigDecimal getValorRubrica6(){

		return this.valorRubrica6;
	}

	public void setValorRubrica6(BigDecimal valorRubrica6){

		this.valorRubrica6 = valorRubrica6;
	}

	public String getDescricaoRubrica7(){

		return this.descricaoRubrica7;
	}

	public void setDescricaoRubrica7(String descricaoRubrica7){

		this.descricaoRubrica7 = descricaoRubrica7;
	}

	public String getReferenciaRubrica7(){

		return this.referenciaRubrica7;
	}

	public void setReferenciaRubrica7(String referenciaRubrica7){

		this.referenciaRubrica7 = referenciaRubrica7;
	}

	public BigDecimal getValorRubrica7(){

		return this.valorRubrica7;
	}

	public void setValorRubrica7(BigDecimal valorRubrica7){

		this.valorRubrica7 = valorRubrica7;
	}

	public String getDescricaoRubrica8(){

		return this.descricaoRubrica8;
	}

	public void setDescricaoRubrica8(String descricaoRubrica8){

		this.descricaoRubrica8 = descricaoRubrica8;
	}

	public String getReferenciaRubrica8(){

		return this.referenciaRubrica8;
	}

	public void setReferenciaRubrica8(String referenciaRubrica8){

		this.referenciaRubrica8 = referenciaRubrica8;
	}

	public BigDecimal getValorRubrica8(){

		return this.valorRubrica8;
	}

	public void setValorRubrica8(BigDecimal valorRubrica8){

		this.valorRubrica8 = valorRubrica8;
	}

	public String getDescricaoRubrica9(){

		return this.descricaoRubrica9;
	}

	public void setDescricaoRubrica9(String descricaoRubrica9){

		this.descricaoRubrica9 = descricaoRubrica9;
	}

	public String getReferenciaRubrica9(){

		return this.referenciaRubrica9;
	}

	public void setReferenciaRubrica9(String referenciaRubrica9){

		this.referenciaRubrica9 = referenciaRubrica9;
	}

	public BigDecimal getValorRubrica9(){

		return this.valorRubrica9;
	}

	public void setValorRubrica9(BigDecimal valorRubrica9){

		this.valorRubrica9 = valorRubrica9;
	}

	public String getDescricaoRubrica10(){

		return this.descricaoRubrica10;
	}

	public void setDescricaoRubrica10(String descricaoRubrica10){

		this.descricaoRubrica10 = descricaoRubrica10;
	}

	public String getReferenciaRubrica10(){

		return this.referenciaRubrica10;
	}

	public void setReferenciaRubrica10(String referenciaRubrica10){

		this.referenciaRubrica10 = referenciaRubrica10;
	}

	public BigDecimal getValorRubrica10(){

		return this.valorRubrica10;
	}

	public void setValorRubrica10(BigDecimal valorRubrica10){

		this.valorRubrica10 = valorRubrica10;
	}

	public String getDescricaoRubrica11(){

		return this.descricaoRubrica11;
	}

	public void setDescricaoRubrica11(String descricaoRubrica11){

		this.descricaoRubrica11 = descricaoRubrica11;
	}

	public String getReferenciaRubrica11(){

		return this.referenciaRubrica11;
	}

	public void setReferenciaRubrica11(String referenciaRubrica11){

		this.referenciaRubrica11 = referenciaRubrica11;
	}

	public BigDecimal getValorRubrica11(){

		return this.valorRubrica11;
	}

	public void setValorRubrica11(BigDecimal valorRubrica11){

		this.valorRubrica11 = valorRubrica11;
	}

	public String getDescricaoRubrica12(){

		return this.descricaoRubrica12;
	}

	public void setDescricaoRubrica12(String descricaoRubrica12){

		this.descricaoRubrica12 = descricaoRubrica12;
	}

	public String getReferenciaRubrica12(){

		return this.referenciaRubrica12;
	}

	public void setReferenciaRubrica12(String referenciaRubrica12){

		this.referenciaRubrica12 = referenciaRubrica12;
	}

	public BigDecimal getValorRubrica12(){

		return this.valorRubrica12;
	}

	public void setValorRubrica12(BigDecimal valorRubrica12){

		this.valorRubrica12 = valorRubrica12;
	}

	public String getDescricaoRubrica13(){

		return this.descricaoRubrica13;
	}

	public void setDescricaoRubrica13(String descricaoRubrica13){

		this.descricaoRubrica13 = descricaoRubrica13;
	}

	public String getReferenciaRubrica13(){

		return this.referenciaRubrica13;
	}

	public void setReferenciaRubrica13(String referenciaRubrica13){

		this.referenciaRubrica13 = referenciaRubrica13;
	}

	public BigDecimal getValorRubrica13(){

		return this.valorRubrica13;
	}

	public void setValorRubrica13(BigDecimal valorRubrica13){

		this.valorRubrica13 = valorRubrica13;
	}

	public String getDescricaoRubrica14(){

		return this.descricaoRubrica14;
	}

	public void setDescricaoRubrica14(String descricaoRubrica14){

		this.descricaoRubrica14 = descricaoRubrica14;
	}

	public String getReferenciaRubrica14(){

		return this.referenciaRubrica14;
	}

	public void setReferenciaRubrica14(String referenciaRubrica14){

		this.referenciaRubrica14 = referenciaRubrica14;
	}

	public BigDecimal getValorRubrica14(){

		return this.valorRubrica14;
	}

	public void setValorRubrica14(BigDecimal valorRubrica14){

		this.valorRubrica14 = valorRubrica14;
	}

	public String getDescricaoRubrica15(){

		return this.descricaoRubrica15;
	}

	public void setDescricaoRubrica15(String descricaoRubrica15){

		this.descricaoRubrica15 = descricaoRubrica15;
	}

	public String getReferenciaRubrica15(){

		return this.referenciaRubrica15;
	}

	public void setReferenciaRubrica15(String referenciaRubrica15){

		this.referenciaRubrica15 = referenciaRubrica15;
	}

	public BigDecimal getValorRubrica15(){

		return this.valorRubrica15;
	}

	public void setValorRubrica15(BigDecimal valorRubrica15){

		this.valorRubrica15 = valorRubrica15;
	}

	public String getReferenciaConsumo1(){

		return this.referenciaConsumo1;
	}

	public void setReferenciaConsumo1(String referenciaConsumo1){

		this.referenciaConsumo1 = referenciaConsumo1;
	}

	public Integer getNumeroConsumo1(){

		return this.numeroConsumo1;
	}

	public void setNumeroConsumo1(Integer numeroConsumo1){

		this.numeroConsumo1 = numeroConsumo1;
	}

	public Integer getIdAnormalidadeLeitura1(){

		return this.idAnormalidadeLeitura1;
	}

	public void setIdAnormalidadeLeitura1(Integer idAnormalidadeLeitura1){

		this.idAnormalidadeLeitura1 = idAnormalidadeLeitura1;
	}

	public String getReferenciaConsumo2(){

		return this.referenciaConsumo2;
	}

	public void setReferenciaConsumo2(String referenciaConsumo2){

		this.referenciaConsumo2 = referenciaConsumo2;
	}

	public Integer getNumeroConsumo2(){

		return this.numeroConsumo2;
	}

	public void setNumeroConsumo2(Integer numeroConsumo2){

		this.numeroConsumo2 = numeroConsumo2;
	}

	public Integer getIdAnormalidadeLeitura2(){

		return this.idAnormalidadeLeitura2;
	}

	public void setIdAnormalidadeLeitura2(Integer idAnormalidadeLeitura2){

		this.idAnormalidadeLeitura2 = idAnormalidadeLeitura2;
	}

	public String getReferenciaConsumo3(){

		return this.referenciaConsumo3;
	}

	public void setReferenciaConsumo3(String referenciaConsumo3){

		this.referenciaConsumo3 = referenciaConsumo3;
	}

	public Integer getNumeroConsumo3(){

		return this.numeroConsumo3;
	}

	public void setNumeroConsumo3(Integer numeroConsumo3){

		this.numeroConsumo3 = numeroConsumo3;
	}

	public Integer getIdAnormalidadeLeitura3(){

		return this.idAnormalidadeLeitura3;
	}

	public void setIdAnormalidadeLeitura3(Integer idAnormalidadeLeitura3){

		this.idAnormalidadeLeitura3 = idAnormalidadeLeitura3;
	}

	public String getReferenciaConsumo4(){

		return this.referenciaConsumo4;
	}

	public void setReferenciaConsumo4(String referenciaConsumo4){

		this.referenciaConsumo4 = referenciaConsumo4;
	}

	public Integer getNumeroConsumo4(){

		return this.numeroConsumo4;
	}

	public void setNumeroConsumo4(Integer numeroConsumo4){

		this.numeroConsumo4 = numeroConsumo4;
	}

	public Integer getIdAnormalidadeLeitura4(){

		return this.idAnormalidadeLeitura4;
	}

	public void setIdAnormalidadeLeitura4(Integer idAnormalidadeLeitura4){

		this.idAnormalidadeLeitura4 = idAnormalidadeLeitura4;
	}

	public String getReferenciaConsumo5(){

		return this.referenciaConsumo5;
	}

	public void setReferenciaConsumo5(String referenciaConsumo5){

		this.referenciaConsumo5 = referenciaConsumo5;
	}

	public Integer getNumeroConsumo5(){

		return this.numeroConsumo5;
	}

	public void setNumeroConsumo5(Integer numeroConsumo5){

		this.numeroConsumo5 = numeroConsumo5;
	}

	public Integer getIdAnormalidadeLeitura5(){

		return this.idAnormalidadeLeitura5;
	}

	public void setIdAnormalidadeLeitura5(Integer idAnormalidadeLeitura5){

		this.idAnormalidadeLeitura5 = idAnormalidadeLeitura5;
	}

	public String getReferenciaConsumo6(){

		return this.referenciaConsumo6;
	}

	public void setReferenciaConsumo6(String referenciaConsumo6){

		this.referenciaConsumo6 = referenciaConsumo6;
	}

	public Integer getNumeroConsumo6(){

		return this.numeroConsumo6;
	}

	public void setNumeroConsumo6(Integer numeroConsumo6){

		this.numeroConsumo6 = numeroConsumo6;
	}

	public Integer getIdAnormalidadeLeitura6(){

		return this.idAnormalidadeLeitura6;
	}

	public void setIdAnormalidadeLeitura6(Integer idAnormalidadeLeitura6){

		this.idAnormalidadeLeitura6 = idAnormalidadeLeitura6;
	}

	public Date getDataLeituraAtual(){

		return this.dataLeituraAtual;
	}

	public void setDataLeituraAtual(Date dataLeituraAtual){

		this.dataLeituraAtual = dataLeituraAtual;
	}

	public Integer getNumeroLeituraAtual(){

		return this.numeroLeituraAtual;
	}

	public void setNumeroLeituraAtual(Integer numeroLeituraAtual){

		this.numeroLeituraAtual = numeroLeituraAtual;
	}

	public Integer getNumeroConsumoMedido(){

		return this.numeroConsumoMedido;
	}

	public void setNumeroConsumoMedido(Integer numeroConsumoMedido){

		this.numeroConsumoMedido = numeroConsumoMedido;
	}

	public Integer getNumeroConsumoFaturado(){

		return this.numeroConsumoFaturado;
	}

	public void setNumeroConsumoFaturado(Integer numeroConsumoFaturado){

		this.numeroConsumoFaturado = numeroConsumoFaturado;
	}

	public Short getNumeroDiasConsumo(){

		return this.numeroDiasConsumo;
	}

	public void setNumeroDiasConsumo(Short numeroDiasConsumo){

		this.numeroDiasConsumo = numeroDiasConsumo;
	}

	public BigDecimal getValorAgua(){

		return this.valorAgua;
	}

	public void setValorAgua(BigDecimal valorAgua){

		this.valorAgua = valorAgua;
	}

	public BigDecimal getValorEsgoto(){

		return this.valorEsgoto;
	}

	public void setValorEsgoto(BigDecimal valorEsgoto){

		this.valorEsgoto = valorEsgoto;
	}

	public BigDecimal getValorDebitos(){

		return this.valorDebitos;
	}

	public void setValorDebitos(BigDecimal valorDebitos){

		this.valorDebitos = valorDebitos;
	}

	public BigDecimal getValorCreditos(){

		return this.valorCreditos;
	}

	public void setValorCreditos(BigDecimal valorCreditos){

		this.valorCreditos = valorCreditos;
	}

	public BigDecimal getValorImpostoFederal(){

		return this.valorImpostoFederal;
	}

	public void setValorImpostoFederal(BigDecimal valorImpostoFederal){

		this.valorImpostoFederal = valorImpostoFederal;
	}

	public BigDecimal getValorTotal(){

		return this.valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal){

		this.valorTotal = valorTotal;
	}

	public Date getDataEmissao(){

		return this.dataEmissao;
	}

	public void setDataEmissao(Date dataEmissao){

		this.dataEmissao = dataEmissao;
	}

	/**
	 * @return the idLigacaoAguaSituacao
	 */
	public Integer getIdLigacaoAguaSituacao(){

		return idLigacaoAguaSituacao;
	}

	/**
	 * @param idLigacaoAguaSituacao
	 *            the idLigacaoAguaSituacao to set
	 */
	public void setIdLigacaoAguaSituacao(Integer idLigacaoAguaSituacao){

		this.idLigacaoAguaSituacao = idLigacaoAguaSituacao;
	}

	/**
	 * @return the idLigacaoEsgotoSituacao
	 */
	public Integer getIdLigacaoEsgotoSituacao(){

		return idLigacaoEsgotoSituacao;
	}

	/**
	 * @param idLigacaoEsgotoSituacao
	 *            the idLigacaoEsgotoSituacao to set
	 */
	public void setIdLigacaoEsgotoSituacao(Integer idLigacaoEsgotoSituacao){

		this.idLigacaoEsgotoSituacao = idLigacaoEsgotoSituacao;
	}

}
