ALTER TABLE GSAN_ADMIN.PROGRAMACAO_ROTEIRO ADD (
	pgrt_icreprogramacao NUMBER (*,0)
);

INSERT INTO GSAN_ADMIN.FUNCIONALIDADE (FNCD_ID, MODU_ID, FNCD_DSFUNCIONALIDADE, FNCD_TMULTIMAALTERACAO, FNCD_DSCAMINHOMENU, FNCD_DSCAMINHOURL, FNCD_ICPONTOENTRADA, FNCD_DSABREVIADO, FNCD_NNORDEMMENU, FNCD_ICNOVAJANELA) 
VALUES (1122, 3, 'Reprogramar Ordem Serviço', CURRENT_TIMESTAMP, 'Gsan/Atendimento ao Publico/Ordem de Servico/Roteiro', 'exibirReprogramarOrdemServicoAction.do', 2, 'EROSA', 0, 1);

INSERT INTO GSAN_ADMIN.OPERACAO (OPER_ID, FNCD_ID, OPER_DSOPERACAO, OPER_DSABREVIADO, OPER_DSCAMINHOURL,OPER_TMULTIMAALTERACAO,OPER_IDOPERACAOPESQUISA,TBCO_ID,OPTP_ID,TBCO_IDARGUMENTO) 
values (2559, 1122, 'Reprogramar Ordem Serviço', 'EROSA', 'reprogramarOrdemServicoAction.do', CURRENT_TIMESTAMP, null, null, 3, null);

INSERT INTO GSAN_ADMIN.GRUPO_FUNCIONALIDADE_OPERACAO (GRUP_ID, OPER_ID, FNCD_ID, GFOP_TMULTIMAALTERACAO) 
values (1, 2559, 1122, CURRENT_TIMESTAMP);
commit;


